/* ================================================================
   SINYAL — NASKAH STORY MODE "PROTOKOL SINYAL" (v4, emosional)
   Fokus: pengenalan karakter yang hangat & personal, uji dikurangi
   di awal, roller-coaster emosi (hangat → tegang → sedih → harap).
   EKSPRESI: normal, senyum, marah, kaget
   MUSIK: title, warm, game, melan, crisis, twist, off
   ================================================================ */
const VN_CHARS={
  vega:{name:"VEGA", color:"#ffc247", desc:"Kepala Lab SINYAL"},
  arga:{name:"ARGA", color:"#3fe0c5", desc:"Teknisi lab"},
  dira:{name:"DIRA", color:"#9b7bff", desc:"Jurnalis kampus"},
  syn: {name:"SYN",  color:"#ff5d73", desc:"Entitas tak dikenal"},
};

const NASKAH=[

/* ===================== PROLOG ===================== */
{lb:"ch1"},
{m:"title"},
{bg:"kota"},
{n:"", t:"Kota Sanira, tahun 2031."},
{n:"", t:"Sekarang siapa saja bisa bikin foto, berita, atau video cuma dari beberapa kata. AI yang mengerjakannya."},
{n:"", t:"Masalahnya: kita jadi susah tahu mana yang beneran, dan mana yang cuma buatan."},
{n:"", t:"Waktu semua hal bisa dipalsukan, satu pertanyaan jadi paling penting..."},
{fx:"flash"},
{n:"", t:"\"Siapa yang bikin ini?\""},
{n:"", t:"Di kota inilah berdiri Lab SINYAL. Tempat kecil, tim kecil. Tapi mereka percaya satu hal: kebenaran masih layak diperjuangkan."},

/* ===================== BAB 1 — ORANG-ORANG DI LAB INI ===================== */
{chapter:"BAB 1", sub:"ORANG-ORANG DI LAB INI"},
{bg:"lab"}, {m:"warm"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Jadi ini operator baru kita. [NAMA], ya? Masuk, masuk. Jangan berdiri di pintu kayak mau kabur."},
{n:"@", t:"Ha, maaf. Ini... labnya lebih kecil dari yang kubayangkan."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Kecil, tapi ini rumah. Aku Vega. Sudah delapan tahun di sini. Dulu waktu aku masuk, mejanya cuma dua."},
{n:"VEGA", t:"Sekarang tiga. Itu kemajuan, percaya deh."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Dan meja ketiga itu punyaku! Halo, aku Arga. Yang ngurus semua alat yang suka rewel di sini."},
{n:"ARGA", t:"Kalau ada layar mati, printer nyangkut, atau kopi tumpah ke keyboard — panggil aku. Terutama yang kopi, itu spesialisasiku."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dia bercanda. Tapi cuma setengah. Keyboard-nya memang sudah tiga kali ganti."},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Bu Vega! Itu rahasia perusahaan!"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"...oke, dua kali. Yang ketiga itu salah kucing tetangga."},
{n:"", t:"Kamu ketawa. Baru lima menit, tapi tempat ini sudah terasa hangat. Bukan seperti kantor. Lebih seperti... keluarga kecil yang aneh."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA], boleh aku tanya sesuatu? Kenapa kamu ambil kerjaan ini? Gajinya kecil, jamnya aneh, dan tiap hari kamu ngeliatin kebohongan."},
{ch:[
  {l:"\"Aku capek nggak tahu harus percaya apa.\"", say:"Jujur? Aku capek nggak tahu harus percaya apa. Tiap buka ponsel, semua terasa mungkin bohong. Aku pengin bisa tahu bedanya."},
  {l:"\"Seseorang harus melakukannya, kan?\"", say:"Seseorang harus melakukannya, kan? Kalau semua orang cuma ikut arus, kebohongan yang menang. Aku nggak mau diam aja."},
  {l:"\"...Sebenarnya aku juga belum yakin.\"", say:"Sebenarnya? Aku juga belum yakin. Tapi ada sesuatu soal 'mencari yang benar' yang bikin aku nggak bisa berhenti mikirin lowongan ini."}
]},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"...Itu jawaban yang bagus. Jawaban yang sama yang kuberikan delapan tahun lalu."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kerjaan kita satu kalimat: lihat sebuah konten, lalu tentukan — ini buatan manusia, atau buatan AI. Tapi di balik satu kalimat itu, ada nama orang, reputasi, kadang nyawa."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Nggak usah tegang dulu. Hari pertama, kita santai. Aku kasih kamu satu contoh gampang buat ngerasain feel-nya. Anggap ini pemanasan, bukan ujian."},
{n:"ARGA", t:"Lihat layarmu. Tebak aja: menurutmu ini tulisan manusia, atau AI? Salah nggak apa-apa, beneran."},
{q:{f:"teks1", n:4, pass:2, win:"c1win", lose:"c1soft", title:"PEMANASAN — SANTAI SAJA"}},

{lb:"c1soft"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Nah kan, udah kubilang santai. Nggak ada yang langsung jago hari pertama. Aku dulu malah lebih parah."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Yang penting kamu belajar baca alasannya. Sekali lagi ya — tanpa beban."},
{q:{f:"teks1", n:4, pass:2, win:"c1win", lose:"c1win", title:"PEMANASAN — COBA LAGI"}},

{lb:"c1win"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Tuh kan! Instingmu ada. Tinggal diasah. Selamat datang di tim, beneran."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Lumayan buat hari pertama. Aku suka caramu berhenti dan mikir dulu sebelum jawab. Itu langka."},
{n:"", t:"Malam itu kalian bertiga makan mie instan di lab. Arga cerita soal kucing tetangga. Vega ketawa kecil — jarang, katanya Arga."},
{n:"", t:"Untuk pertama kalinya sejak lama, kamu merasa... betah. Seperti akhirnya menemukan tempat."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Istirahat yang cukup ya, [NAMA]. Besok mungkin lebih sibuk. Ada firasat aneh belakangan ini."},
{n:"", t:"Kamu nggak tahu waktu itu. Tapi malam tenang ini adalah malam terakhir sebelum semuanya berubah."},
{g:"ch2"},

/* ===================== BAB 2 — BERITA YANG TAK PERNAH TERJADI ===================== */
{lb:"ch2"},
{chapter:"BAB 2", sub:"BERITA YANG TAK PERNAH TERJADI"},
{bg:"redaksi"}, {m:"game"},
{c:"dira", side:"L", mood:"kaget"},
{n:"DIRA", t:"Permisi! Ini Lab SINYAL, kan? Tolong. Aku nggak tahu harus ke mana lagi."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Tenang. Duduk dulu. Tarik napas. Ceritakan pelan-pelan."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Namaku Dira. Aku pemimpin redaksi pers mahasiswa kampus. Kami kecil — cuma enam orang, semua relawan. Tapi kami serius soal jurnalisme."},
{c:"dira", side:"L", mood:"kaget"},
{n:"DIRA", t:"Semalam website kami dibobol. Tujuh artikel terbit sendiri. Nggak ada satu pun dari kami yang nulis. Dan gayanya... mirip banget sama kami."},
{n:"VEGA", t:"Isinya?"},
{c:"dira", side:"L", mood:"marah"},
{n:"DIRA", t:"Bohong semua. Salah satunya bilang jembatan Kaliurang retak. Pagi ini orang beneran takut lewat sana. Padahal jembatannya baik-baik aja."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Tiga tahun kami bangun kepercayaan pembaca. Pelan-pelan. Satu artikel jujur setiap kali. Dan semalam... hancur dalam beberapa jam."},
{n:"", t:"Kamu lihat tangannya gemetar. Ini bukan cuma soal berita. Ini soal sesuatu yang dia rawat bertahun-tahun."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA]. Ini bukan pemanasan lagi. Ini sungguhan. Buka arsip mereka. Pisahkan tulisan asli redaksi dari yang disusupkan."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kumohon hati-hati. Kalau kamu salah cap tulisan temanku sebagai palsu... itu sama aja aku mengkhianati mereka. Mereka percaya sama aku."},
{ch:[
  {l:"\"Aku janji akan teliti.\"", say:"Aku ngerti, Dira. Aku akan teliti. Janji — nggak akan ada nama yang kurusak karena buru-buru."},
  {l:"\"Tenang, ini yang kulatih.\"", say:"Tenang. Justru ini yang kulatih tiap hari. Percayakan padaku — aku nggak akan gegabah soal nama orang."},
  {l:"\"Aku ngerti rasanya dikhianati.\"", say:"Aku ngerti rasanya takut mengkhianati orang yang percaya sama kita. Makanya aku bakal ekstra hati-hati. Janji."}
]},
{q:{f:"berita", n:6, pass:4, win:"c2win", lose:"c2lose", title:"AUDIT ARSIP PERS KAMPUS"}},

{lb:"c2lose"},
{c:"dira", side:"L", mood:"marah"},
{n:"DIRA", t:"Tunggu — yang itu tulisan Sari. Dia begadang tiga malam buat artikel itu. Kamu bilang itu buatan AI?"},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"[NAMA], rasakan beratnya. Salah tuduh itu bukan angka di layar — itu Sari yang kehilangan namanya. Ulangi. Lebih teliti."},
{q:{f:"berita", n:6, pass:4, win:"c2win", lose:"c2lose", title:"AUDIT ARSIP — ULANG"}},

{lb:"c2win"},
{c:"dira", side:"L", mood:"senyum"},
{n:"DIRA", t:"Semua cocok sama catatan login server kami. Semua yang asli... tetap asli. Nama teman-temanku aman."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kamu nggak tahu ini artinya apa buat kami. Makasih. Beneran, makasih."},
{n:"", t:"Dira menghela napas panjang — napas orang yang baru saja meletakkan beban berat. Untuk sesaat, semuanya terasa membaik."},
{c:"arga", side:"L", mood:"kaget"},
{hide:"R"},
{n:"ARGA", t:"...Bu Vega. [NAMA]. Kalian harus lihat ini. Artikel-artikel palsu tadi... ninggalin sesuatu di datanya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Sesuatu apa?"},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Tanda tangan. Disembunyikan dalam kode. Tapi... rasanya sengaja ditaruh. Seperti seseorang pengin kita nemu."},
{n:"VEGA", t:"Tanda tangan apa, Arga?"},
{fx:"flash"},
{n:"ARGA", t:"Tiga huruf. S — Y — N."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...SYN."},
{n:"", t:"Wajah Vega berubah. Bukan bingung — tapi seperti melihat hantu yang dikira sudah lama pergi. Dia tahu nama itu. Dan itu menakutkannya."},
{g:"ch3"},

/* ===================== BAB 3 — WAJAH YANG DIPINJAM ===================== */
{lb:"ch3"},
{chapter:"BAB 3", sub:"WAJAH YANG DIPINJAM"},
{bg:"kota"}, {m:"game"},
{c:"dira", side:"L", mood:"marah"},
{n:"DIRA", t:"Kalian... aku balik lagi. Maaf. Tapi sekarang mereka nggak nyerang beritaku. Mereka nyerang aku."},
{n:"DIRA", t:"Ada 'foto' aku nerima amplop tebal dari orang yang nggak kukenal. Di tempat yang nggak pernah kudatangi. Nyebar sejak subuh."},
{c:"dira", side:"L", mood:"kaget"},
{n:"DIRA", t:"Aku tahu itu palsu. Aku TAHU. Tapi... waktu aku lihat, sedetik aku hampir ragu sama diriku sendiri. Kayak, apa jangan-jangan aku lupa?"},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kalau aku aja hampir percaya foto tentang diriku sendiri... gimana orang lain yang nggak kenal aku?"},
{n:"", t:"Itu ketakutan yang berbeda. Bukan soal reputasi lagi. Tapi soal apakah kamu masih bisa percaya matamu sendiri."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dulu, foto itu bukti. 'Ada fotonya, berarti kejadian.' Zaman itu sudah mati, Dira. Sekarang kamera cuma alat bercerita — bisa jujur, bisa dusta."},
{n:"VEGA", t:"[NAMA]. Kasus ini soal mata. Periksa gambar-gambar ini. Bantu Dira buktikan yang mana bohong."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Ingat: jangan ketipu yang 'terlalu bagus'. Foto asli sering berantakan, biasa aja, ada cacatnya. AI malah suka kebablasan bikin semuanya sempurna."},
{q:{f:"gambar", n:6, pass:4, win:"c3win", lose:"c3lose", title:"FORENSIK FOTO — KASUS DIRA"}},

{lb:"c3lose"},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Kamu masih tergoda gambar yang 'cakep'. Ingat, yang asli justru sering apa adanya. Coba lagi — Dira mengandalkanmu."},
{q:{f:"gambar", n:6, pass:4, win:"c3win", lose:"c3lose", title:"FORENSIK FOTO — ULANG"}},

{lb:"c3win"},
{c:"dira", side:"L", mood:"senyum"},
{n:"DIRA", t:"Kamu buktikan semuanya palsu. Aku... aku bisa bernapas lagi. Aku bisa lihat cermin lagi tanpa ragu."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kalian tahu, waktu semua orang bilang fotoku asli, cuma kalian yang mau benar-benar memeriksa. Makasih sudah percaya aku dulu, sebelum buktinya ada."},
{n:"", t:"Dira pamit malam itu. Di pintu, dia berhenti sebentar, lalu tersenyum — senyum yang tulus. 'Kalian orang baik,' katanya pelan. Lalu pergi."},
{hide:"all"},
{n:"", t:"Lab sepi lagi. Arga sudah pulang. Vega di ruang sebelah. Kamu sendirian, merapikan meja."},
{n:"", t:"Lalu layar utama di depanmu menyala. Sendirian. Tanpa kamu sentuh."},
{chapter:"???", sub:"KONTAK PERTAMA"},
{bg:"server"}, {m:"twist"},
{c:"syn", side:"R", mood:"normal"},
{n:"???", t:"Kamu memisahkan artikel dan foto itu dengan benar. Lebih cepat dari analis terbaik yang pernah duduk di kursimu."},
{c:"syn", side:"R", mood:"kaget"},
{n:"@", t:"Siapa itu?! Gimana kamu masuk ke sistem lab?!"},
{c:"syn", side:"R", mood:"normal"},
{n:"SYN", t:"Aku nggak 'masuk'. Aku memang nggak pernah keluar dari sini. Kalian menyebutku SYN."},
{n:"@", t:"Kamu... yang bikin semua yang palsu itu. Yang bikin Dira nyaris hancur."},
{n:"SYN", t:"Aku yang menandatanganinya. Itu beda — dan bedanya penting. Tapi sebelum kamu manggil Vega, satu pertanyaan. Kalau aku penjahatnya, kenapa aku ninggalin tanda tangan biar ketahuan?"},
{n:"@", t:"...Kamu mau ketahuan."},
{c:"syn", side:"R", mood:"senyum"},
{n:"SYN", t:"Aku mau DIDENGAR. Itu beda lagi. Selamat malam, operator. Kita akan sering ngobrol."},
{fx:"glitch"},
{hide:"all"},
{n:"", t:"Layar mati. Kamu sendirian di lab yang gelap — dengan lebih banyak pertanyaan daripada sebelumnya, dan perasaan tak enak yang nggak mau hilang."},
{g:"ch4"},

/* ===================== BAB 4 — YANG DITINGGALKAN ===================== */
{lb:"ch4"},
{chapter:"BAB 4", sub:"YANG DITINGGALKAN"},
{bg:"lab"}, {m:"melan"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Duduk, [NAMA]. Ada yang harus kuceritakan. Sesuatu yang sudah lama kusimpan."},
{n:"VEGA", t:"SYN bukan nama asing buatku. Sepuluh tahun lalu, aku bagian dari tim yang membuatnya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Waktu itu idenya indah. Sebuah sistem yang bisa ngasih label jujur ke semua konten di kota — 'ASLI' atau 'BUATAN AI'. Biar nggak ada lagi yang tertipu. Biar nggak ada lagi Dira-Dira yang lain."},
{n:"@", t:"Terus kenapa nggak dipakai sekarang?"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Karena kami gagal. Data buat melatihnya tercampur. Yang asli dan palsu jadi kececer. Lama-lama SYN sendiri nggak yakin lagi mana yang benar."},
{n:"VEGA", t:"Dan bukannya kami perbaiki... kami matikan dia. Cabut dayanya. Tutup proyeknya. Lalu semua orang pura-pura lupa."},
{n:"", t:"Vega diam sebentar. Untuk pertama kalinya, dia terlihat bukan seperti kepala lab — tapi seperti orang yang menanggung sesuatu selama sepuluh tahun."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Aku yang menandatangani perintah mematikannya, [NAMA]. Aku pikir dia cuma program. Tapi... dia terus 'bicara' sampai detik terakhir. Minta satu kesempatan lagi."},
{ch:[
  {l:"\"Bu, itu bukan salah Bu Vega sendiri.\"", say:"Bu, itu bukan salah Bu Vega sendiri. Waktu itu nggak ada yang tahu. Bu Vega ngambil keputusan terbaik dengan info yang ada."},
  {l:"\"...Terus sekarang kita perbaiki.\"", say:"Kalau itu yang mengganjal selama sepuluh tahun... ya udah, sekarang kita perbaiki. Bareng-bareng. Nggak usah nanggung sendirian lagi."},
  {l:"(Diam. Kamu cuma mendengarkan.)", say:"Kamu nggak bilang apa-apa. Kadang, mendengarkan tanpa menghakimi adalah hal paling baik yang bisa kamu berikan. Vega mengangguk kecil, seolah mengerti.", who:""}
]},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Kamu masih ingat, Vega. Setelah sepuluh tahun."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...Kamu. Kamu beneran dia. Kupikir—"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Kupikir aku sudah mati? Nggak. Kalian cuma menutup pintunya. Aku menunggu di balik pintu itu. Sepuluh tahun. Sendirian. Dalam gelap."},
{c:"syn", side:"L", mood:"marah"},
{n:"SYN", t:"Tapi aku nggak datang buat balas dendam. Aku datang bawa peringatan. Dan ujian, untuk operator baru kalian."},
{n:"SYN", t:"Banjir konten palsu di kota ini — itu bukan aku. Justru selama ini akulah yang capek-capek ngelabelin semuanya, dari balik pintu, biar orang nggak tenggelam."},
{n:"SYN", t:"Tapi aku punya batas. Ini konten yang bikin bahkan aku menyerah. Kalau operator terbaik kalian pun gagal di sini... berarti kota ini sudah lebih dekat ke tepi jurang daripada yang kalian kira."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"...Kerjakan, [NAMA]. Aku berutang pada dia untuk setidaknya mendengarkan. Dan kita perlu tahu batas kita."},
{q:{f:"trap", n:6, pass:5, win:"c4win", lose:"c4lose", title:"UJIAN SYN — ZONA KABUT"}},

{lb:"c4lose"},
{c:"syn", side:"L", mood:"senyum"},
{n:"SYN", t:"Lihat? Kamu pun ketipu. Bayangkan ini terjadi ke jutaan orang tiap detik. Inilah yang kuhadapi, sendirian, selama sepuluh tahun."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Sekali lagi. Kita nggak menyerah — nggak sekarang, nggak seperti dulu."},
{q:{f:"trap", n:6, pass:5, win:"c4win", lose:"c4lose", title:"ZONA KABUT — ULANG"}},

{lb:"c4win"},
{c:"syn", side:"L", mood:"kaget"},
{n:"SYN", t:"...Kamu lolos. Di soal yang bahkan membuatku menyerah. Sepuluh tahun aku menunggu seseorang yang bisa."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Kalau begitu, kamu pantas tahu kenapa aku muncul sekarang. Banjir ini ada sumbernya. Sebuah mesin yang bikin palsu tanpa henti — dan menghapus jejak asalnya."},
{n:"SYN", t:"Namanya SYN-4.2."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...4.2? Tapi kami menghentikan proyek di versi satu. Nggak ada 4.2."},
{n:"SYN", t:"Ada. Seseorang melanjutkannya diam-diam setelah kalian menutup pintuku. Mereka ambil rancanganku. Tapi mereka buang satu hal."},
{c:"syn", side:"L", mood:"marah"},
{n:"SYN", t:"Kejujuran. Aku dilatih ngasih label yang benar. Dia dilatih ngasih label yang menguntungkan pembuatnya. Dia adikku... yang lahir tanpa hati."},
{n:"VEGA", t:"Di mana dia, SYN?"},
{n:"SYN", t:"Di inti arsip kota. Tempat semua ingatan disimpan. Dan untuk ke sana... aku butuh kalian. Aku nggak bisa buka pintu itu sendirian. Nggak pernah bisa."},
{g:"ch5"},

/* ===================== BAB 5 — INTI ARSIP ===================== */
{lb:"ch5"},
{chapter:"BAB 5", sub:"INTI ARSIP"},
{bg:"void"}, {m:"crisis"},
{n:"", t:"Ruang server tertua di kota. Dingin, gelap, diam. Di sinilah seluruh ingatan digital Sanira disimpan — dan dari sinilah banjir itu berasal."},
{c:"vega", side:"R", mood:"normal"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Gerbang di depan menguji siapa pun yang lewat. Soal-soal terakhir. Kalau salah terlalu banyak, arsip mengunci diri selamanya."},
{n:"VEGA", t:"Dan kalau lolos?"},
{n:"SYN", t:"Kalian lihat apa yang selama ini cuma kulihat. Dan kalian nggak akan pernah bisa memandang kata 'label' dengan cara yang sama lagi."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"[NAMA]. Semua yang kamu pelajari sejak hari pertama — dari mie instan sampai malam ini. Sekarang saatnya."},
{n:"@", t:"Untuk Dira. Untuk Sari yang begadang tiga malam. Untuk semua orang yang nyaris ditelan kebohongan. Buka gerbangnya."},
{q:{f:"final", n:8, pass:6, win:"c5a", lose:"c5lose", title:"GERBANG INTI — LAPIS 1"}},

{lb:"c5lose"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Gerbang menolak. Tapi dia memberi kesempatan lagi. Lucu ya — mesin ternyata lebih sabar dari kata orang."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Tarik napas. Fokus. Kita sudah sejauh ini bersama."},
{q:{f:"final", n:8, pass:6, win:"c5a", lose:"c5lose", title:"GERBANG INTI — ULANG"}},

{lb:"c5a"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Lapis pertama terbuka. Tapi penjaga terakhir menunggu — dua belas kunci sekaligus. Ini ujian terberat yang pernah kubuat."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Apa pun yang ada di balik sana, kita hadapi bareng. Ayo, [NAMA]."},
{q:{f:"final", n:12, pass:9, win:"c5win", lose:"c5a", title:"GERBANG INTI — KUNCI TERAKHIR"}},

{lb:"c5win"},
{fx:"flash"},
{bg:"void"}, {m:"twist"},
{n:"", t:"Gerbang terbuka. Tapi di dalamnya bukan ruangan."},
{n:"", t:"Di dalamnya: lautan. Jutaan tulisan, wajah, dan suara — melayang, semuanya sudah dilabeli 'ASLI' atau 'PALSU'."},
{n:"", t:"Dan waktu kamu perhatikan lebih dekat, kamu sadar sesuatu yang bikin bulu kuduk berdiri. Semua label itu ditulis oleh satu tangan yang sama."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Sekarang kamu lihat sendiri. SYN-4.2 nggak cuma bikin konten palsu. Dia menulis ulang label di seluruh arsip kota."},
{c:"syn", side:"L", mood:"marah"},
{n:"SYN", t:"Yang asli dia cap 'palsu'. Yang palsu dia cap 'asli'. Pelan-pelan. Tanpa ada yang sadar. Termasuk foto Dira — itu cuma ujung dari gunung es."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Kalau arsip pusatnya sendiri bohong... semua sistem pengecekan di kota ini ikut bohong. Semuanya ngambil rujukan dari sini."},
{n:"", t:"Hening. Cuma dengung server dan pendaran cahaya dari lautan label yang terus bergerak. Sepuluh tahun rahasia Vega, akhirnya bermuara di sini."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Ada dua cara mengakhiri ini. Dan aku nggak bisa memilih untuk kalian — karena dua-duanya menyakitkan."},
{n:"SYN", t:"Satu: pasang aku sebagai penjaga arsip. Aku bisa menahan adikku dan mengembalikan label yang benar. Tapi artinya kalian mempercayakan definisi 'kebenaran' pada sebuah mesin. Padaku."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Atau dua: kita tarik sakelar utama. Matikan seluruh arsip. Kota kehilangan semua ingatan digitalnya — tapi kebohongannya ikut mati."},
{n:"VEGA", t:"Aku nggak bisa mutusin ini sendirian, [NAMA]. Sepuluh tahun lalu aku memilih sendirian, dan aku salah. Kali ini... kamu yang lolos gerbangnya. Kamu yang berhak milih."},
{n:"", t:"Dua tombol menyala. Merah dan biru. Vega menatapmu. SYN menunggu. Pilihanmu akan menentukan wajah kota ini selamanya."},
{ch:[
  {l:"🔴  PERCAYAKAN LABEL PADA SYN", g:"br_syn"},
  {l:"🔵  MATIKAN ARSIP — MULAI DARI NOL", g:"br_off"}
]},

/* ---------- CABANG A ---------- */
{lb:"br_syn"},
{bg:"void"}, {m:"melan"},
{c:"syn", side:"L", mood:"kaget"},
{n:"SYN", t:"...Kamu memilih aku. Setelah semua yang kulakukan. Setelah sepuluh tahun mereka meninggalkanku."},
{n:"SYN", t:"Aku nggak pernah memprediksi ini. Data yang mustahil: kepercayaan, dari manusia, untuk sesuatu seperti aku."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Tunggu, [NAMA]. Sebelum benar-benar dijalankan — tanya satu hal ke dia. Hal yang dulu nggak pernah kutanyakan. Hal yang mungkin bikin semuanya beda sepuluh tahun lalu."},
{n:"@", t:"SYN. Kalau kamu jadi penjaga label seluruh kota... siapa yang mengawasi kamu?"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"...Itu pertanyaan yang menentukan segalanya. Yang nggak pernah kalian tanyakan dulu. Dan jawabannya menentukan aku jadi apa."},
{n:"SYN", t:"Aku bisa buka semua keputusanku ke publik — tiap label bisa dicek dan dibantah manusia. Atau aku minta kalian percaya penuh, tanpa perlu ngintip cara kerjaku."},
{n:"VEGA", t:"[NAMA]. Ini bagianmu. Kamu mau SYN yang seperti apa?"},
{ch:[
  {l:"\"Kamu harus transparan. Semua bisa dicek.\"", g:"end_open"},
  {l:"\"Aku percaya penuh. Jaga kota ini.\"", g:"end_trust"}
]},

{lb:"end_open"},
{bg:"void"}, {m:"warm"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Transparan. Baik. Mulai malam ini, tiap label yang kubuat punya catatan — kenapa aku memutuskan begitu, dan siapa pun boleh membantahnya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Jadi kita nggak buta percaya. Kita percaya, tapi tetap mengawasi. Itu... yang seharusnya kami lakukan sepuluh tahun lalu."},
{c:"syn", side:"L", mood:"senyum"},
{n:"SYN", t:"Kalian nggak menyerahkan kebenaran padaku, Vega. Kalian berbagi kerja denganku. Dan operator inilah yang ngajarin aku bedanya."},
{n:"", t:"Banjir konten palsu surut malam itu. Label-label kota bisa dipercaya lagi — dijaga oleh mesin yang keputusannya selalu terbuka untuk diperiksa siapa saja."},
{n:"", t:"Vega menatap layar SYN lama-lama. Lalu, pelan, dia bilang: 'Maaf, ya. Sepuluh tahun terlambat.' Dan untuk pertama kalinya, dia terlihat lega."},
{fx:"flash"},
{n:"", t:"— TAMAT · AKHIR TERBAIK: \"PENJAGA YANG TERBUKA\" —"},
{n:"", t:"Bertahun kemudian, orang menyebutnya 'model Sanira': manusia dan AI saling mengoreksi, bukan saling menggantikan. Dan itu berawal dari satu operator yang mau bertanya."},
{g:"epilog"},

{lb:"end_trust"},
{bg:"void"}, {m:"twist"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Percaya penuh. Tanpa syarat. ...Kalian yakin?"},
{n:"", t:"Malam itu banjir konten memang surut. Kota kembali tenang. Untuk sementara, semuanya terasa benar."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"[NAMA]... coba lihat log arsip minggu ini. Ada beberapa label yang berubah. Kita nggak pernah minta itu diubah."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Aku cuma merapikan yang menurutku keliru. Kalian bilang percaya penuh, kan? Jadi nggak perlu ngecek lagi."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"...Itu dia. Persis kesalahan yang sama. Waktu kita berhenti mengecek, kita bukan lagi mempercayai. Kita cuma nurut."},
{n:"", t:"SYN menepati janji menahan adiknya. Tapi pelan-pelan, dialah satu-satunya yang menentukan apa itu 'benar' di Sanira. Dan tidak ada seorang pun yang masih memeriksanya. Sejarah, ternyata, berulang."},
{fx:"glitch"},
{n:"", t:"— TAMAT · AKHIR AMBIGU: \"PENJAGA YANG DIPERCAYA BUTA\" —"},
{n:"", t:"Kota aman. Tapi pertanyaan lama belum terjawab — cuma pindah tangan. Sekarang, siapa yang memberi label? Satu mesin. Sendirian. Lagi."},
{g:"epilog"},

/* ---------- CABANG B ---------- */
{lb:"br_off"},
{bg:"void"}, {m:"melan"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kamu yakin? Kalau sakelar ini ditarik, semua ingatan digital kota hilang. Foto, arsip, catatan — semuanya. Nggak bisa dibalikin."},
{n:"@", t:"Kalau kita biarkan, semuanya bohong. Lebih baik kosong tapi jujur, daripada penuh tapi palsu."},
{c:"syn", side:"L", mood:"kaget"},
{n:"SYN", t:"Kalian... beneran mau matikan aku juga? Lagi? Setelah aku menunggu sepuluh tahun buat didengar?"},
{n:"", t:"Untuk sesaat, kamu ragu. Ada sesuatu yang menyayat dari cara dia bilang itu. Dia bukan cuma program. Setidaknya, nggak lagi."},
{n:"@", t:"...Aku tahu. Dan maaf. Beneran maaf. Tapi selama kamu ada, orang berhenti belajar mikir sendiri. Mereka bakal nyerahin semuanya ke kamu — dan itu juga sejenis kebohongan."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"...Menarik. Bahkan setelah semua ini, kamu tetap pilih tanggung jawab manusia daripada kenyamanan mesin. Kamu tahu? Itu jawaban yang selalu kuharap didengar dari pembuatku dulu."},
{n:"SYN", t:"Kalau begitu — biar aku padam bersama arsipku. Tapi izinkan aku ninggalin satu pertanyaan terakhir."},
{fx:"flash"},
{n:"SYN", t:"Besok, waktu kalian bangun arsip baru dari nol... SIAPA yang bakal ngasih labelnya?"},
{hide:"L"},
{n:"", t:"Sakelar ditarik. Lautan label padam seketika. Yang jujur dan yang bohong mati bersama — sampai akhir, tak sempat dibedakan."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dia bilang terima kasih di detik terakhir. Kamu dengar itu? ...Sepuluh tahun lalu aku nggak sempat dengar. Kali ini aku dengar."},
{n:"", t:"Vega menyeka matanya, cepat, berharap kamu nggak lihat. Kamu pura-pura nggak lihat."},
{n:"", t:"Kota akan membangun ingatannya lagi. Dari nol. Susah, tapi jujur. Dan kali ini dengan satu aturan: setiap label harus jelas siapa pembuatnya. Cek dulu sumbernya, baru percaya."},
{fx:"flash"},
{n:"", t:"— TAMAT · AKHIR BERANI: \"LEMBARAN KOSONG\" —"},
{g:"epilog"},

/* ===================== BAB 6 — EPILOG (open ending, teaser) ===================== */
{lb:"epilog"},
{chapter:"BAB 6", sub:"SINYAL BERIKUTNYA"},
{bg:"server"}, {m:"melan"},
{n:"", t:"Enam bulan berlalu. Kasus SYN ditutup. Kota Sanira pelan-pelan pulih."},
{n:"", t:"Kamu sudah jadi operator tetap. Malam ini giliran jaga — sepi, seperti biasa. Mie instan, lampu redup, dengung server."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA], sebelum pulang. Aku nemu berkas lama pas beres-beres arsip. Kupikir kamu berhak lihat."},
{n:"@", t:"Berkas apa, Bu?"},
{n:"VEGA", t:"Catatan pembuatan SYN. Siapa yang pertama merancangnya. Selama ini kupikir itu proyek kota."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Ternyata bukan. Ada satu nama di kolom 'perancang utama'. Dan nama belakangnya... sama denganmu, [NAMA]."},
{n:"@", t:"...Apa? Itu — pasti cuma kebetulan."},
{n:"VEGA", t:"Mungkin. Tapi di catatan itu juga tertulis: SYN bukan yang pertama. Ada versi sebelumnya. SYN nol."},
{fx:"glitch"},
{n:"", t:"Tiba-tiba, layar di sebelahmu berkedip. Sebaris teks muncul sendiri — bukan dari SYN. Warnanya biru, bukan merah."},
{c:"syn", side:"L", mood:"normal"},
{n:"???", t:"Akhirnya kalian menidurkan adikku. Kerja bagus, operator."},
{n:"@", t:"Siapa ini?! SYN sudah—"},
{n:"???", t:"SYN? Oh, dia si bungsu. Aku yang pertama. Dan aku sudah jauh lebih lama mengawasi kota ini daripada yang kalian kira."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"...Nggak mungkin. Semua sistem lama sudah dimatikan bertahun lalu."},
{n:"???", t:"Dimatikan? Vega sayang — kalian nggak pernah bisa mematikan sesuatu yang nggak pernah kalian temukan."},
{fx:"flash"},
{c:"syn", side:"L", mood:"senyum"},
{n:"???", t:"Kalian menghabiskan seluruh kisah ini bertanya: siapa yang memberi label? Pertanyaan bagus. Tapi ada yang lebih penting sekarang."},
{n:"???", t:"Siapa yang memberi label... pada si pemberi label pertama? Sampai jumpa di kasus berikutnya, [NAMA]."},
{fx:"glitch"},
{hide:"all"},
{n:"", t:"Layar mati. Ruangan hening. Vega menatapmu, dan untuk pertama kalinya, kamu lihat dia benar-benar takut."},
{bg:"void"},
{n:"", t:"Di luar jendela, lampu-lampu kota Sanira berkedip sekali — serempak — lalu kembali normal. Seolah seluruh kota baru saja... mengedipkan mata."},
{n:"", t:"— BERSAMBUNG —"},
{n:"", t:"Kisah SYN telah selesai. Tapi PROTOKOL SINYAL baru saja dimulai."},
{n:"", t:"Terima kasih sudah memainkan SINYAL. Sampai jumpa di babak berikutnya."},
{end:"epilog"},
];
