/* ================================================================
   SINYAL — NASKAH BABAK II: "PROTOKOL FAJAR" (v2, build-up)
   ----------------------------------------------------------------
   REVISI v2: bahasa lebih santai & gampang dipahami (senada babak I),
   tiap bab diperpanjang, dan struktur diubah jadi BUILD-UP murni.
   Twist (pelakunya Senja) tetap jadi klimaks BAB 12, tapi TIDAK ada
   penyelesaian: BAB 13 berakhir kalah & terjepit, Fajar menyala,
   dan cerita ditutup menggantung untuk FINALE SINYAL (babak III).
   Dua ending lama (Terang/Senyap) DIHAPUS.

   INTEGRASI (tidak berubah): muat SETELAH naskah.js DAN story.js.
   IIFE di bawah: merge tokoh ke VN_CHARS, tambah 4 latar ke
   VN_BG_FALLBACK, ganti {end:"epilog"} jadi pilihan jembatan,
   push NASKAH2. Label ch9..ch13 cocok regex simpan /^ch\d/.
   Guard anti dobel: cek label ch9.

   TOKOH BARU: NARA (arsiparis), ELIAS (kapten siber), SENJA (kurator)
   LATAR BARU: menara, bawah, relay, putih
   ================================================================ */
const VN_CHARS2={
  nara: {name:"NARA",  color:"#9fe6a0", desc:"Arsiparis Menara Arsip"},
  elias:{name:"ELIAS", color:"#ff9d5c", desc:"Kapten Divisi Siber"},
  senja:{name:"SENJA", color:"#cfd8e3", desc:"Kurator Agung"},
};
const VN_BG_FALLBACK2={
  bawah: "radial-gradient(900px 600px at 50% 0%, rgba(63,224,197,.08), transparent), linear-gradient(180deg,#071118,#03070b)",
  relay: "radial-gradient(800px 500px at 30% 40%, rgba(255,157,92,.10), transparent), linear-gradient(180deg,#12100c,#060504)",
  putih: "radial-gradient(1000px 700px at 50% 40%, rgba(255,255,255,.16), rgba(210,220,228,.06)), linear-gradient(180deg,#20262c,#0d1114)",
  menara:"radial-gradient(900px 600px at 50% 20%, rgba(120,160,255,.10), transparent), linear-gradient(180deg,#0a1020,#04060d)",
};

const NASKAH2=[

/* ---------- jembatan: mempertahankan TAMAT lama ---------- */
{lb:"tamat1"},
{end:"epilog"},

/* ===================== BAB 9 — NAMA YANG DIHAPUS ===================== */
{lb:"ch9"},
{chapter:"BABAK II · BAB 9", sub:"NAMA YANG DIHAPUS"},
{bg:"lab"}, {m:"melan"},
{n:"", t:"Kamu nggak tidur malam itu. Tiap merem, kalimat di layar biru itu muncul lagi. Siapa yang memberi label pada si pemberi label pertama."},
{n:"", t:"Dan satu hal lagi yang lebih mengganggu. Kata Vega, nama perancang SYN punya nama belakang yang sama denganmu."},
{n:"", t:"Jam enam pagi, pintu lab digedor. Bukan diketuk. Digedor."},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Iya iya bentar! Ya ampun, kalau mau beli gorengan sebelah masih tut... eh."},
{c:"elias", side:"L", mood:"normal"},
{hide:"L"},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Kapten Elias. Divisi Siber. Ini surat perintah audit untuk Lab SINYAL. Mulai pagi ini, semua akses kalian dibekukan."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Dibekukan? Kapten, kami yang MENUTUP kasus banjir konten kemarin. Kota ini utang tenang sama lab kecil ini."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Saya tahu. Makanya saya datang sendiri, bukan kirim satu peleton. Duduk dulu. Ini bukan soal kasus kemarin."},
{n:"ELIAS", t:"Tiga hari terakhir, ada yang aneh di Menara Arsip. Ribuan berkas warga berubah label sendiri. Dari ASLI jadi PALSU."},
{n:"@", t:"Berubah label... maksudnya gimana? Emangnya ngefek apa?"},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Kamu masih muda, jadi mungkin nggak kepikiran. Di kota ini, arsipmu adalah dirimu. Ijazah dilabeli PALSU? Kamu dianggap nggak pernah sekolah. Rekening PALSU? Uangmu bukan uangmu."},
{n:"ELIAS", t:"Tiga hari ini, ribuan orang kehilangan kerjaan, tabungan, riwayat berobat. Bukan dirampok. Cuma... dicoret."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Itu mengerikan. Tapi kenapa auditnya ke kami?"},
{n:"", t:"Elias meletakkan tablet di meja. Pelan banget. Kayak orang yang naruh sesuatu yang bisa meledak."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Karena setiap perubahan label itu ninggalin sidik jari digital. Sidik jarinya sama semua. Dan sidik jari itu terdaftar atas satu nama keluarga."},
{fx:"flash"},
{n:"ELIAS", t:"Nama keluargamu, operator [NAMA]."},
{n:"", t:"Ruangan mendadak sunyi. Kamu bisa dengar kulkas lab berdengung. Arga berhenti ngunyah gorengannya di tengah-tengah."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Itu nggak masuk akal. Dia kerja di sini tiap hari, hampir tiap jam bersamaku. Kapan sempatnya..."},
{n:"@", t:"Bu. Tunggu. Kapten... kuncinya itu dibuat kapan?"},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Nah. Itu bagian yang bikin saya nggak langsung nangkap kamu. Kunci itu dibuat dua puluh tahun lalu. Waktu itu kamu masih balita."},
{n:"", t:"Dingin merambat dari tengkuk ke tanganmu. Nama keluargamu di berkas perancang SYN. Sekarang di sidik jari pelaku. Dua puluh tahun lalu. Ini bukan kebetulan. Ini kayak... ada yang nulis ceritanya duluan."},
{ch:[
  {l:"\"Bantu aku bongkar ini, Kapten.\"", say:"Kalau nama keluargaku ada di tengah semua ini, aku yang paling pengin tahu jawabannya. Bantu aku bongkar, Kapten. Audit aku sekalian kalau perlu."},
  {l:"\"Ini jebakan. Ada yang pakai namaku.\"", say:"Coba pikir, Kapten. Kalau aku pelakunya, ngapain sidik jariku kutinggal rapi di ribuan berkas? Ini kayak maling yang ninggalin KTP. Ada yang MAU kalian dateng ke sini."},
  {l:"(Diam. Genggam ujung meja kuat-kuat.)", say:"Kamu nggak bilang apa-apa. Tanganmu menggenggam ujung meja. Vega meliriknya, lalu pelan-pelan menaruh tangannya di pundakmu. Kalian sudah pernah diseret kebohongan yang kelihatan sempurna. Kali ini pun kalian tahu harus mulai dari mana.", who:""}
]},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"...Dua puluh tahun jadi penyidik ngajarin saya satu hal. Bukti yang terlalu rapi itu biasanya disusun, bukan ditemukan."},
{n:"ELIAS", t:"Saya kasih kalian tiga hari sebelum laporan resmi naik. Kita mulai dari tempat semua label lahir. Menara Arsip."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Aku jaga lab ya. Bukan takut lho ya. Cuma... oke sedikit takut. Kabarin terus pokoknya!"},

{bg:"menara"}, {m:"game"},
{n:"", t:"Kamu sering lihat Menara Arsip dari jauh. Dari dekat, rasanya beda. Gedung itu kayak tulang punggung raksasa: empat ratus meter rak arsip menjulang, lift kaca naik-turun tanpa suara, dan udara dingin yang bau kertas tua."},
{n:"", t:"Di sinilah setiap warga Sanira 'ada'. Selama arsipnya berlabel ASLI."},
{c:"nara", side:"L", mood:"kaget"},
{n:"NARA", t:"Lab SINYAL?! Beneran? Yang ngungkap kasus SYN itu? Aduh akhirnya ada yang dateng, aku udah teriak-teriak soal anomali ini dari minggu lalu dan semua orang nganggep aku lebay."},
{n:"NARA", t:"Eh maaf. Nara. Arsiparis lantai memori lama. Aku yang pertama nemuin label-label yang berubah sendiri."},
{n:"@", t:"Kamu yang pertama lapor? Kok bisa kamu duluan yang sadar?"},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Karena aku... ya, aku emang tiap hari ngecekin label satu-satu. Kebiasaan. Nanti kuceritain. Pokoknya sekarang ikut aku, ada berkas yang harus kalian lihat sebelum ikut kecoret."},
{c:"senja", side:"R", mood:"senyum"},
{n:"SENJA", t:"Nara, Nara. Pelan-pelan sama tamu. Mereka baru naik empat puluh lantai, kasih napas dulu."},
{c:"vega", side:"R", mood:"kaget"},
{hide:"R"},
{c:"senja", side:"R", mood:"senyum"},
{n:"VEGA", t:"...Bu Senja?"},
{n:"SENJA", t:"Vega. Ya ampun. Sini, sini. Sudah berapa tahun? Kamu terakhir ke sini masih bawa-bawa laporan yang kamu tumpahi kopi itu."},
{c:"vega", side:"R", mood:"senyum"},
{hide:"R"},
{c:"senja", side:"R", mood:"normal"},
{n:"VEGA", t:"Sepuluh tahun, Bu. [NAMA], kenalin. Bu Senja, Kurator Agung menara ini. Dulu pembimbingku di proyek lama. Semua yang kubisa soal membaca jejak pemalsuan, aku belajar dari beliau."},
{c:"senja", side:"R", mood:"senyum"},
{n:"SENJA", t:"Ah, dia melebih-lebihkan. Aku cuma pustakawan tua yang cerewet soal label. Jadi kamu operator baru yang terkenal itu. Duduk. Kubuatkan teh dulu, baru kita bicara soal menara yang sedang sakit ini."},
{n:"", t:"Teh dituang. Ruangan Bu Senja hangat, penuh buku sungguhan, wangi kayu. Sepuluh menit ngobrol dan rasanya kayak di rumah nenek. Untuk pertama kalinya sejak subuh, bahumu turun sedikit."},
{c:"senja", side:"R", mood:"normal"},
{n:"SENJA", t:"Anomali label ini di luar semua prosedur kami. Aku sudah tua, mata sudah nggak setajam dulu. Jadi kuserahkan pada kalian: periksa apa pun yang kalian butuh. Menara ini terbuka untuk kalian."},
{ch:[
  {l:"\"Terima kasih, Bu. Kami mulai dari lantai memori lama.\"", say:"Terima kasih, Bu. Kami mulai dari lantai memori lama. Nara bilang ada berkas yang harus kami lihat."},
  {l:"\"Boleh saya tanya soal proyek lama dulu, Bu?\"", say:"Sebelumnya... boleh saya tanya soal proyek lama, Bu? Soal perancang SYN. Renata. Ibu kenal dia?"}
]},
{c:"senja", side:"R", mood:"normal"},
{n:"SENJA", t:"Renata... sudah lama sekali tidak ada yang menyebut nama itu di depanku. Dia murid terbaikku. Lebih baik dari Vega, maaf ya Vega. Kepalanya keras, hatinya lurus."},
{n:"SENJA", t:"Kepergiannya adalah luka lama proyek kami. Sudah, sudah. Orang tua kalau mulai nostalgia bisa sampai malam. Sana, Nara sudah tidak sabar dari tadi."},

{m:"melan"},
{n:"", t:"Lantai memori lama ada jauh di bawah, tempat arsip-arsip yang jarang disentuh. Lampunya setengah mati. Nara jalan cepat banget di antara rak, kayak hafal tiap belokan."},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Waktu nelusurin asal kunci sidik jari itu, aku nyasar ke arsip proyek dua puluh tahun lalu. Terus aku nemu ini."},
{n:"NARA", t:"Berkas perancang. Namanya Renata. Dan di kolom keluarganya... ada namamu. Kamu anaknya, kan?"},
{fx:"glitch"},
{n:"@", t:"...Ibuku hilang waktu aku kecil. Kata orang kecelakaan. Aku nyari berkasnya bertahun-tahun. Di kantor catatan sipil, di rumah sakit, di mana-mana. Nggak pernah ketemu. Kayak... kayak dia nggak pernah ada."},
{c:"nara", side:"L", mood:"marah"},
{n:"NARA", t:"Karena menurut menara ini, dia MEMANG nggak pernah ada. Lihat. Semua berkas tentang dia dilabeli PALSU. Ijazahnya. Surat kerjanya. Bahkan akta kelahiranmu yang nyantumin namanya."},
{n:"", t:"Kamu menatap layar. Ratusan dokumen tentang ibumu, dan semuanya dicoret satu kata merah: PALSU. Bukan meninggal. Bukan hilang. Dihapus."},
{cut:"b2_menara", n:"", t:"Empat ratus meter rak arsip menjulang di kegelapan biru, dan di salah satu laci di antara jutaan itu, nama ibumu tersimpan di bawah satu kata merah: PALSU."},
{n:"", t:"Kamu ingat hal-hal kecil. Bau timah solder di dapur. Ibumu suka nyanyi kecil kalau lagi mikir. Satu-satunya foto yang kamu punya, yang ujungnya sobek. Semua itu nyata. Kamu TAHU itu nyata."},
{ch:[
  {l:"\"Dia nyata. Aku ingat dia.\"", say:"Dia nyata. Aku ingat suaranya. Aku ingat bau solder di dapur. Label sialan ini yang bohong, bukan ingatanku."},
  {l:"\"Siapa yang bisa menghapus orang kayak gini?\"", say:"Nara... label PALSU sebanyak ini, di arsip nasional... siapa yang PUNYA kuasa sebesar itu? Dan kenapa ke ibuku?"},
  {l:"(Sentuh layar. Pelan.)", say:"Kamu menyentuh layar, tepat di nama ibumu. Dingin. Nara pura-pura sibuk ke rak sebelah. Vega berdiri di belakangmu, nggak bilang apa-apa, tapi nggak pergi.", who:""}
]},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA]. Dengar aku. Kalau label-label ini dipalsukan, arsip aslinya kemungkinan masih terkubur di lapisan bawah sistem. Pemalsu selalu ninggalin jejak. Kamu sendiri yang ngajarin aku itu lagi bulan-bulan kemarin."},
{n:"VEGA", t:"Jadi sekarang kita kerja. Pilah tumpukan berkas ini. Pisahkan rekayasa dari yang asli. Bukan buat klien. Buat keluargamu."},
{q:{f:"berita", n:6, pass:4, win:"c9win", lose:"c9lose", title:"AUDIT MENARA · BERKAS RENATA"}},

{lb:"c9lose"},
{c:"nara", side:"L", mood:"kaget"},
{n:"NARA", t:"Aduh, sistem menara nandain sesi kita. Sekali lagi kebalik, lantai ini ngunci otomatis dan berkas ibumu ikut kesegel. Pelan-pelan aja, nggak usah buru-buru."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Tarik napas. Ingat: yang asli itu punya jejak proses. Cari yang hidup. Yang bimbang. Yang berantakan dikit."},
{q:{f:"berita", n:6, pass:4, win:"c9win", lose:"c9lose", title:"AUDIT MENARA · ULANG"}},

{lb:"c9win"},
{c:"nara", side:"L", mood:"senyum"},
{n:"NARA", t:"Dapet! Empat puluh dua dokumen asli tentang Renata, utuh di lapisan bawah. Dia nyata. Dia ADA. Dan sekarang kita pegang buktinya."},
{n:"", t:"Empat puluh dua dokumen. Ijazah ibumu. Foto kartu pegawainya, rambutnya diikat asal, senyumnya miring sebelah kayak senyummu. Kamu harus duduk sebentar."},
{c:"elias", side:"L", mood:"normal"},
{hide:"L"},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Kalau begitu pertanyaannya berubah. Bukan lagi 'siapa Renata'. Tapi: siapa yang dulu punya wewenang menghapus seorang manusia dari arsip nasional. Dan kenapa dia melakukannya."},
{n:"", t:"Malam itu, sebelum pulang, layar kerjamu berkedip sekali. Sebaris teks biru. Tanpa pengirim. Warna yang sama kayak malam itu di lab."},
{fx:"glitch"},
{n:"", t:"\"Empat puluh dua dokumen. Kerja yang rapi, anak Renata.\""},
{n:"", t:"\"Satu nasihat, gratis: jangan percaya menara.\""},
{n:"@", t:"...SYN-0."},
{g:"ch10"},

/* ===================== BAB 10 — KOTA DI BAWAH HUJAN ===================== */
{lb:"ch10"},
{chapter:"BABAK II · BAB 10", sub:"KOTA DI BAWAH HUJAN"},
{bg:"bawah"}, {m:"melan"},
{n:"", t:"Alamat di dokumen asli ibumu nunjuk ke satu tempat: blok pipa tua di Kota Bawah."},
{n:"", t:"Kamu lahir dan besar di Sanira, tapi belum pernah sekali pun turun ke sini. Kota Bawah nggak ada di peta. Nggak ada di berita. Ada di bawah jalur layang, di antara pipa-pipa raksasa, tempat air hujan kota atas jatuh terus tanpa berhenti."},
{n:"", t:"Dan yang bikin dadamu sesak: tempat ini PENUH. Ada pasar. Ada anak-anak main bola pakai bola yang udah botak. Ada kehidupan. Kehidupan yang menurut arsip... nggak pernah ada."},
{cut:"b2_bawah", n:"", t:"Di bawah jalur layang, hujan buatan jatuh tanpa henti ke gang-gang neon yang berkabut. Sebuah kota utuh, berdenyut, penuh manusia, yang menurut menara di atas sana tidak pernah ada."},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Jangan natap orang lama-lama, jangan nunjukin lencana menara. Ikutin aku aja, aku hafal gang-gangnya."},
{n:"@", t:"Kamu hafal Kota Bawah? Arsiparis menara, hafal jalanan sini?"},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"...Aku lahir di sini."},
{n:"NARA", t:"Ayahku dilabeli PALSU waktu aku tujuh tahun. 'Kesalahan sistem', katanya. Semua orang bilang tinggal urus, sebentar juga beres. Tahu berapa lama ngurusnya? Sebelas tahun."},
{n:"NARA", t:"Sebelas tahun ayahku nggak bisa kerja resmi, nggak bisa berobat pakai jaminan, nggak bisa jemput aku ke sekolah karena namanya nggak lolos gerbang. Dia meninggal di tahun kesepuluh. Setahun sebelum labelnya balik."},
{n:"", t:"Nara ngomongnya datar. Terlalu datar. Kayak cerita yang udah diceritain seribu kali sampai nggak sakit lagi. Padahal kelihatan banget masih sakit."},
{ch:[
  {l:"\"Makanya kamu jadi arsiparis.\"", say:"Makanya kamu jadi arsiparis. Ngecekin label satu-satu tiap hari. Biar nggak ada anak lain yang nunggu sebelas tahun."},
  {l:"\"Maaf. Aku nggak tahu kota ini punya bawah.\"", say:"Maaf, Nara. Aku tinggal di kota yang sama seumur hidup dan aku nggak tahu... aku nggak pernah mau tahu tempat ini ada."},
  {l:"(Jalan di sebelahnya. Tanpa kata.)", say:"Kamu nggak bilang apa-apa. Cuma nyamain langkah, jalan di sebelahnya, bukan di belakangnya. Nara ngelirik, terus buang muka. Tapi bahunya turun dikit.", who:""}
]},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Udah, jangan pasang muka sedih. Orang sini paling sebel diliatin kayak gitu. Laper nggak? Ada warung bubur paling enak se-Sanira di belokan depan. Seriusan. Kota atas nggak punya yang kayak gini."},
{n:"", t:"Warung itu cuma terpal dan tiga bangku panjang. Ibu warungnya langsung hafal Nara, nyendokin porsi lebih tanpa ditanya. Buburnya... oke, Nara bener. Ini bubur terenak yang pernah kamu makan."},
{n:"", t:"\"Anak menara bawa temen,\" kata ibu warung, nyodorin kerupuk. \"Makan yang banyak. Orang atas badannya pada tipis-tipis, kayak arsip.\" Dia ketawa sendiri. Kamu ikut ketawa. Rasanya aneh, ketawa di tempat kayak gini. Aneh tapi bagus."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"...Sepuluh tahun aku ngelabelin konten, [NAMA]. Baru hari ini aku lihat langsung apa yang terjadi kalau labelnya salah dan nggak ada yang meriksa. Ini yang dipertaruhkan tiap kali kita kerja. Jangan lupa tempat ini."},

{m:"game"},
{n:"", t:"Blok pipa tua ada di ujung distrik. Bengkel kecil, gemboknya udah karatan. Nara ngebukanya pakai kawat dalam lima detik, terus pasang muka polos pas kamu ngeliatin."},
{n:"", t:"Di dalam: debu sepuluh tahun. Papan tulis penuh coretan rumus yang setengah kehapus. Cangkir kopi yang isinya udah jadi fosil. Dan di pojok papan tulis, kecil, ada gambar doodle: dua orang gandengan, yang satu tinggi, yang satu kecil. Di bawahnya tulisan tangan: 'jangan lupa jemput'."},
{n:"@", t:"...Itu tulisan ibuku. Aku... aku inget tulisannya."},
{n:"", t:"Kamu berdiri di tengah bengkel itu lama. Di sinilah ibumu mikir, kerja, ngopi, gambar doodle jelek. Sepuluh tahun tempat ini nunggu, dan yang dateng akhirnya kamu."},
{fx:"flash"},
{n:"", t:"Terus kamu dengar. Di balik panel lantai. Bunyi kecil. Tik. Tik. Tik."},
{c:"arga", side:"L", mood:"kaget"},
{hide:"L"},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Aku dateng secepat mungkin! Mana barangnya... ASTAGA. Ini relai generasi pertama. Dan masih NYALA? Sepuluh tahun? Baterainya aja harusnya udah wafat dari zaman kapan."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Dia dirancang buat satu hal doang: ngirim satu pesan, ke satu frekuensi, berulang-ulang. Kayak orang yang manggil-manggil nama yang sama selama sepuluh tahun. ...Sori. Perumpamaannya jelek. Kubuka enkripsinya ya."},
{n:"ARGA", t:"Tapi sambil nunggu, ada masalah lain. Kanal darurat Kota Bawah lagi kacau balau. Gara-gara anomali label, ribuan orang minta tolong lewat frekuensi liar. Nah, ada yang sengaja banjirin kanal itu pakai pesan bot."},
{n:"ARGA", t:"Pesan palsu minta tolong ke alamat kosong. Relawan capek dateng ke tempat kosong, lama-lama mereka berhenti percaya semua pesan. Liciknya di situ."},
{c:"nara", side:"L", mood:"marah"},
{n:"NARA", t:"Kalau relawan berhenti percaya, orang sini yang mati pelan-pelan. [NAMA], selagi Arga buka relai ibumu... tolong bantuin. Pilah kanalnya. Pesan yang beneran harus sampe."},
{q:{f:"chat", n:6, pass:4, win:"c10win", lose:"c10lose", title:"KANAL DARURAT KOTA BAWAH"}},

{lb:"c10lose"},
{c:"nara", side:"L", mood:"kaget"},
{n:"NARA", t:"Tim relawan barusan dateng ke alamat kosong. Dua jam kebuang. Di sini, dua jam itu bisa berarti nyawa. Ayo, sekali lagi. Kamu bisa."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Inget pelajaran ibunya Arga. Pesan yang asli punya ingatan dan tempat. Yang palsu cuma punya kata-kata."},
{q:{f:"chat", n:6, pass:4, win:"c10win", lose:"c10lose", title:"KANAL DARURAT · ULANG"}},

{lb:"c10win"},
{c:"nara", side:"L", mood:"senyum"},
{n:"NARA", t:"Sembilan belas permintaan asli tervalidasi, relawan jalan semua. Kamu barusan nolongin orang-orang yang menurut arsip nggak pernah ada. Gimana rasanya? Inget-inget. Itu alasan kita kerja."},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"KEBUKA! Relainya kebuka! Pesannya... cuma satu kalimat. Diulang sepuluh tahun. Bacain nih ya."},
{fx:"glitch"},
{n:"", t:"\"Kepada yang membawa namaku: jangan biarkan fajar menyala. Stasiun Relai 7. Kuncinya adalah kamu.\""},
{n:"@", t:"'Kepada yang membawa namaku'... Ini buat aku. Ibuku ninggalin pesan buat AKU."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Fajar. Dia bilang fajar. [NAMA], di proyek lama ada rumor soal 'Protokol Fajar'. Rencana darurat buat nulis ulang SELURUH label kota dalam satu malam. Kami dibilangin rancangannya nggak pernah dibuat. Cuma coretan di papan tulis."},
{n:"@", t:"Kayaknya kita udah kebanyakan dibilangin hal yang nggak bener, Bu."},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Stasiun Relai 7... itu di perbatasan kota. Udah mati lima belas tahun. Harusnya."},
{n:"", t:"Di saku, ponselmu bergetar. Sebaris teks biru, tanpa pengirim."},
{n:"", t:"\"Dia mulai bergerak lebih cepat karena kalian. Bagus. Aku benci menunggu sendirian.\""},
{n:"@", t:"'Dia'? Dia itu SIAPA? Woy! ...Ugh. Kenapa sih semua AI misterius hobinya ngasih teka-teki setengah-setengah."},
{g:"ch11"},

/* ===================== BAB 11 — STASIUN RELAI 7 ===================== */
{lb:"ch11"},
{chapter:"BABAK II · BAB 11", sub:"STASIUN RELAI 7"},
{bg:"relay"}, {m:"crisis"},
{n:"", t:"Stasiun Relai 7 berdiri di perbatasan kota, di tengah ilalang setinggi dada. Menurut arsip: nonaktif lima belas tahun."},
{n:"", t:"Menurut matamu malam ini: antenanya anget, trafonya berdengung pelan, dan ada cahaya tipis di balik jendela yang dicat hitam. Bangunan mati nggak bernapas kayak gini."},
{cut:"b2_relay", n:"", t:"Antena tua menjulang di tengah ilalang, karat di mana-mana. Tapi trafonya berdengung dan lampunya menyala di balik jendela hitam. Bangunan yang katanya mati ini, jelas, masih bernapas."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Sebelum kalian nanya kenapa saya di sini padahal harusnya nulis laporan: perintah penyitaan lab kalian kemarin, saya telusuri asalnya. Bukan dari kepolisian."},
{n:"ELIAS", t:"Dari otoritas arsip. Seseorang di atas sana yang ngarahin penyidikan saya dari hari pertama. Nyuruh saya lari ke arah yang mereka mau."},
{n:"@", t:"Terus... Kapten sekarang di pihak mana?"},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Saya nggak suka jadi anak panah orang. Malam ini saya nyidik buat diri saya sendiri. Anggap saja... cuti. Cuti sambil bawa bukti."},
{c:"arga", side:"L", mood:"senyum"},
{hide:"L"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Pak, cutinya seru banget. Aku kalau cuti paling tidur."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"...Kalian selalu seberisik ini kalau nyusup?"},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Iya pak. Mekanisme koping, katanya."},
{n:"", t:"Pintu samping stasiun nggak dikunci. Itu justru bikin semua orang makin waspada. Di dalam, senter kalian nangkap bangkai-bangkai mesin tua penuh debu... dan di tengahnya, satu rak server yang kinclong. Baru. Kabelnya masih wangi plastik."},
{fx:"glitch"},
{c:"arga", side:"L", mood:"marah"},
{n:"ARGA", t:"Nggak mungkin... Ini pemancar SYN-4.2. DIBANGUN ULANG. Banjir konten kemarin, anomali label sekarang, semuanya dipancarin DARI SINI. Ada yang ngerakit lagi mainannya setelah kita menang."},
{n:"@", t:"Bentar. Kita 'menang' berbulan-bulan lalu. Berarti selama kita santai-santai, ngerayain, orang ini... udah mulai lagi?"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Mungkin dia nggak pernah berhenti. Mungkin yang kemarin itu cuma... babak pertamanya dia juga."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Log akses. Semua pakai kunci kriptografi proyek generasi pertama. Menurut arsip, kunci itu cuma pernah dipegang tiga orang. Renata. Kepala lab kalian. Dan direktur proyek."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Elias. Aku bersumpah, aku nggak pernah..."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Saya tahu. Jam aksesnya udah saya cocokkan duluan sebelum ke sini. Tiap kali kunci ini dipakai, kamu tercatat di lab, bareng operator. Kamu bersih, Vega."},
{n:"ELIAS", t:"Renata sudah tiada. Kamu bersih. Berarti tinggal satu pemegang kunci."},
{n:"", t:"Sunyi. Cuma dengung trafo. Nggak ada yang berani nyebut jabatan itu keras-keras, karena kalian semua tahu siapa orang terakhir yang megang jabatan itu. Dan kemarin kalian minum teh buatannya."},
{c:"nara", side:"L", mood:"kaget"},
{hide:"L"},
{c:"nara", side:"L", mood:"kaget"},
{n:"NARA", t:"Nggak. Nggak mungkin Bu Senja. Kalian nggak kenal dia. Dia yang mungut aku dari program magang, dia yang bela aku waktu semua orang bilang anak Kota Bawah nggak pantes pegang arsip. Dia... dia baik."},
{ch:[
  {l:"\"Nara, kita belum nuduh siapa-siapa.\"", say:"Nara, dengerin. Kita belum nuduh siapa-siapa. Justru karena itu kita butuh bukti yang nggak bisa dibantah. Kalau dia bersih, bukti ini yang bakal ngebersihin namanya."},
  {l:"\"Orang yang baik ke kita bisa jahat ke orang lain.\"", say:"Aku ngerti, Nara. Tapi bulan-bulan kemarin ngajarin aku satu hal yang nyebelin: baiknya seseorang ke kita nggak ngebuktiin apa-apa soal dia ke orang lain."},
  {l:"(Inget senyum hangat di ruangan berbau kayu itu.)", say:"Kamu inget ruangan hangat itu. Teh yang dituang pelan. 'Menara ini terbuka untuk kalian.' ...Terbuka. Supaya tiap langkah kalian keliatan. SYN-0 udah bilang dari awal: jangan percaya menara.", who:""}
]},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Perasaan kalian berdua dua-duanya valid. Makanya kita kerjakan ini dengan benar. Nggak ada tuduhan tanpa bukti bersih. Setuju?"},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Nah soal itu... ada kabar buruk. Stasiun ini tahu bakal digeledah cepat atau lambat. Log, dokumen, rekaman di dalam sistemnya, sebagian itu UMPAN. Sengaja ditanam biar penggeledahnya bawa pulang bukti palsu."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Bukti palsu yang kalau dibawa ke pengadilan bakal gugur, dan pelakunya bebas selamanya. Ini lapisan paling licin sejauh ini, [NAMA]. Jangan pegang cirinya. Pegang nalarnya."},
{q:{f:"trap", n:6, pass:5, win:"c11win", lose:"c11lose", title:"STASIUN 7 · LAPISAN UMPAN"}},

{lb:"c11lose"},
{c:"elias", side:"L", mood:"marah"},
{n:"ELIAS", t:"Yang kamu pegang itu dokumen umpan. Kalau ini saya bawa ke jaksa, kasusnya bubar di sidang pertama. Ulangi. Pelan. Teliti."},
{q:{f:"trap", n:6, pass:5, win:"c11win", lose:"c11lose", title:"STASIUN 7 · ULANG"}},

{lb:"c11win"},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Bukti bersih, terkumpul. Perintah pembangunan ulang pemancar, jalur dananya, jadwal pancarannya. Kurang dua hal: motif, dan pengakuan."},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Eh eh eh, sini deh. Pintu di ujung ini beda sendiri. Bukan kunci proyek. Ini segel biometrik generasi pertama. Ngunci ke... satu garis keluarga. Coba tebak keluarga siapa."},
{n:"", t:"Kamu ngedeketin panel itu. Belum nyentuh apa-apa, panelnya udah nyala duluan. Kayak ngenalin kamu. Kayak udah nunggu."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"...Sepuluh tahun pintu ini nunggu satu tangan. Kamu siap?"},
{n:"@", t:"Nggak. Tapi buka aja."},
{fx:"flash"},
{n:"", t:"Segel terbuka dengan desah pelan. Kayak pintu yang udah sepuluh tahun nahan napas."},
{c:"syn", side:"L", mood:"normal"},
{n:"???", t:"...Halo, anak Renata."},
{c:"syn", side:"L", mood:"senyum"},
{n:"???", t:"Bukan, bukan SYN yang kalian kenal. Suara kami mirip karena dia dibangun dari rusukku. Aku yang pertama. Yang kalian sebut-sebut SYN-0."},
{n:"@", t:"Kamu... yang ngirim pesan-pesan biru. Yang ngomong di lab malam itu. Yang bilang jangan percaya menara."},
{c:"syn", side:"L", mood:"normal"},
{n:"???", t:"Dan yang nunggumu tumbuh selama sepuluh tahun. Masuklah. Di dalam, ibumu ninggalin jawaban buat semua pertanyaanmu. Termasuk yang selama ini nggak berani kamu tanyain."},
{g:"ch12"},

/* ===================== BAB 12 — RUANG PUTIH ===================== */
{lb:"ch12"},
{chapter:"BABAK II · BAB 12", sub:"RUANG PUTIH"},
{bg:"putih"}, {m:"twist"},
{n:"", t:"Di balik pintu itu nggak ada server. Nggak ada kabel. Cuma ruang putih yang cahayanya dateng dari mana-mana dan dari nggak ke mana-mana. Langkahmu nggak bunyi. Kayak jalan di dalem awan."},
{c:"nara", side:"L", mood:"kaget"},
{n:"NARA", t:"Teknologi apa ini... Ini harusnya belum ada sepuluh tahun lalu. Ini harusnya belum ada SEKARANG."},
{c:"syn", side:"R", mood:"normal"},
{n:"SYN-0", t:"Ibumu nyebut aku Mercusuar. Aku sistem label pertama kota ini. Bukan hakim kebenaran. Cuma penjaga catatan: siapa nulis apa, kapan, dan kenapa."},
{n:"SYN-0", t:"Renata ngerancang aku dengan satu prinsip. Label harus selalu bisa ditelusuri ke tangan pembuatnya. Sederhana, kan? Prinsip sesederhana itu... yang bikin dia dihapus."},
{n:"@", t:"Tunggu. Pelan-pelan. Kamu bilang ibuku bikin kamu buat jaga catatan. Terus kenapa dia dihapus? Sama siapa? Ceritain dari awal. Aku nunggu sepuluh tahun buat ini, aku nggak mau denger versi teka-teki."},
{c:"syn", side:"R", mood:"normal"},
{n:"SYN-0", t:"...Kamu ngomongnya persis kayak dia. Baiklah. Nggak pakai teka-teki. Tapi bukan aku yang bakal cerita. Dia sendiri."},
{n:"", t:"Ruang putih bergetar. Dari cahaya, tersusun sebuah sosok. Rekaman memori. Perempuan berjas lab kusut, rambut diikat asal, mata yang capek tapi keras. Kamu kenal wajah itu. Dari satu-satunya foto yang ujungnya sobek."},
{cut:"b2_putih", n:"", t:"Ruang tanpa dinding, tanpa lantai, cahaya datang dari mana-mana. Di tengahnya, tersusun dari partikel cahaya, sesosok perempuan mulai terbentuk. Wajah yang kamu kenal dari satu-satunya foto yang ujungnya sobek."},
{fx:"flash"},
{n:"", t:"\"Halo, sayang. Kalau rekaman ini kebuka... berarti kamu udah gede. Dan berarti ibu gagal pulang. Maaf. Maaf banget.\""},
{n:"", t:"Suaranya. Sepuluh tahun kamu lupa-lupa inget suaranya, dan sekarang dia di sini, dan dia persis kayak yang kamu inget. Kamu nggak sadar kamu udah jongkok sampai Vega megangin pundakmu."},
{n:"", t:"\"Ibu nggak punya banyak waktu, jadi dengerin baik-baik ya. Jauh sebelum SYN dibuat, ibu nemuin sesuatu di arsip kota. Label-labelnya udah lama dipalsuin. Bukan sama mesin. Sama manusia.\""},
{n:"", t:"\"Berkas lawan politik dicap PALSU. Kepemilikan tanah ditulis ulang. Orang-orang dihapus. Rapi. Bertahun-tahun. Dan nggak ada yang sadar, karena yang malsuin adalah orang yang paling dipercaya semua orang.\""},
{n:"", t:"\"Ibu bego. Ibu bawa temuan ibu ke orang yang paling ibu percaya di proyek. Ibu pikir dia bakal bantu. Ternyata ibu lapor maling ke malingnya langsung.\""},
{n:"", t:"Rekaman bergetar. Rusak. Potongan-potongan memori pecah berhamburan kayak kaca. Tepat di bagian dia mau nyebut nama."},
{c:"syn", side:"R", mood:"marah"},
{n:"SYN-0", t:"Bagian yang nyebut namanya dirusak dari luar, bertahun-tahun lalu. Seseorang nyoba banget ngehapus kesaksian ini. Hampir berhasil. Tapi aku nyimpen pecahannya. Semuanya."},
{n:"SYN-0", t:"Susun ulang, anak Renata. Pisahin pecahan memori asli dari suntikan perusaknya. Cuma kamu yang bisa, dan kamu udah dilatih buat ini tanpa kamu sadar. Ini kesaksian ibumu. Jangan sampai salah satu keping pun."},
{q:{f:"final", n:8, pass:6, win:"c12win", lose:"c12lose", title:"REKONSTRUKSI KESAKSIAN RENATA"}},

{lb:"c12lose"},
{c:"syn", side:"R", mood:"normal"},
{n:"SYN-0", t:"Pecahan yang kamu pegang itu suntikan perusak. Kalau kesusun ikut, kesaksian ini gugur. Tarik napas. Ibumu udah nunggu sepuluh tahun. Dia sanggup nunggu lima menit lagi."},
{q:{f:"final", n:8, pass:6, win:"c12win", lose:"c12lose", title:"REKONSTRUKSI · ULANG"}},

{lb:"c12win"},
{fx:"flash"},
{n:"", t:"Keping terakhir masuk ke tempatnya. Rekaman nyatu. Suara ibumu balik, jernih. Dan dia nyebut nama itu dengan tenang. Tanpa ragu sedikit pun."},
{n:"", t:"\"Pelakunya direktur proyek kami. Yang sekarang jadi penjaga seluruh arsip kota. Guru yang paling kami sayang.\""},
{fx:"glitch"},
{n:"", t:"\"Pelakunya Senja.\""},
{c:"nara", side:"L", mood:"kaget"},
{n:"NARA", t:"..."},
{n:"NARA", t:"Nggak. Nggak nggak nggak. Pasti ada... pasti konteksnya beda. Bu Senja yang MUNGUT aku. Yang inget ulang tahunku. Yang..."},
{c:"vega", side:"R", mood:"kaget"},
{hide:"R"},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...Yang nyuruh aku nandatanganin penutupan SYN."},
{n:"VEGA", t:"[NAMA]. Sepuluh tahun aku nyalahin diriku sendiri buat tanda tangan itu. Ternyata... ternyata aku cuma pulpennya. SYN mulai nyium pola pemalsuan lama, jadi dia harus mati, dan Bu Senja butuh tangan lain buat matiinnya. Tanganku."},
{n:"", t:"Satu per satu, semuanya jatuh ke tempatnya, dan bunyinya kayak kaca pecah. Senja malsuin label puluhan tahun. Ibumu mergokin, terus dihapus. SYN mulai curiga, terus dimatiin lewat tangan Vega. Lalu diam-diam Senja bangun SYN-4.2: pemberi label yang nurut."},
{n:"", t:"Dan banjir konten palsu itu. Kekacauan yang bikin sekota memohon-mohon adanya satu penjaga kebenaran. Krisisnya diciptain... biar obatnya laku."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN-0", t:"Satu hal lagi yang kamu berhak tahu, anak Renata. Dan maaf, yang ini bakal sakit."},
{n:"SYN-0", t:"Lowongan kerja yang bawa kamu ke Lab SINYAL. Itu nggak nyampe ke kamu secara kebetulan. Dia yang mastiin itu nyampe."},
{n:"SYN-0", t:"Ruangan ini cuma bisa dibuka garis darah Renata. Sepuluh tahun dia nyoba masuk dan gagal. Jadi dia berhenti nyoba ngebobol pintunya... dan mulai ngebesarin kuncinya. Kamu nggak direkrut, nak. Kamu dipancing. Pelan-pelan. Bertahun-tahun."},
{n:"@", t:"...'Kenapa kamu ambil kerjaan ini?' Pertanyaan Bu Vega di hari pertama. Aku jawab sok yakin waktu itu. Ternyata bahkan jawabanku... bukan sepenuhnya punyaku."},
{n:"", t:"Dari arah pintu, kedengeran tepuk tangan. Pelan. Tiga kali. Terus suara langkah yang tenang banget di lantai putih."},
{c:"senja", side:"L", mood:"senyum"},
{n:"SENJA", t:"Rekonstruksi yang indah. Renata pasti bangga. Dia selalu bilang, suatu hari anaknya bakal lebih tajam dari kami semua."},
{n:"SENJA", t:"Terima kasih sudah membukakan pintunya untukku, nak. Sepuluh tahun aku mencoba. Ternyata kuncinya memang harus pulang sendiri."},
{g:"ch13"},

/* ===================== BAB 13 — FAJAR MENYALA ===================== */
{lb:"ch13"},
{chapter:"BABAK II · BAB 13", sub:"FAJAR MENYALA"},
{bg:"putih"}, {m:"crisis"},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Turunkan tatapan kalian seperti itu. Aku tidak datang untuk bertengkar. Aku bahkan tidak marah. Kalian melakukan persis yang kudidik: menelusuri label sampai ke tangan pembuatnya. Nilai sempurna, semuanya."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Bu... kenapa? Empat puluh tahun Ibu ngajarin kami kejujuran arsip. KENAPA?"},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Karena aku sudah melihat apa yang terjadi kalau kota ini dikasih kebenaran mentah, Vega. Kamu belum lahir waktu kerusuhan arsip pertama. Aku ada di sana. Kebenaran yang berserakan itu membakar lebih banyak rumah daripada kebohongan yang tertata."},
{n:"SENJA", t:"Sengketa tanah yang kubereskan dengan satu label, itu mencegah perang antar distrik. Nama-nama yang kuhapus... itu orang-orang yang akan menyalakan koreknya."},
{n:"@", t:"Ibuku bukan korek api. Ibuku cuma mau label bisa ditelusuri. Dan kamu menghapusnya. Kamu menghapus IBUKU dari dunia."},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Renata adalah orang terbaik yang pernah kubimbing. Justru karena itu dia paling berbahaya, nak. Kebenaran di tangan orang baik itu senjata yang tidak bisa diajak kompromi."},
{n:"SENJA", t:"Kamu marah. Wajar. Simpan marah itu baik-baik. Karena mulai malam ini, kamu akan butuh tenaganya."},
{fx:"glitch"},
{n:"", t:"Lampu ruang putih berkedip. Sekali. Dua kali. Lalu di dinding cahaya itu muncul angka-angka. Hitung mundur."},
{cut:"b2_fajar", n:"", t:"Di seluruh Sanira, serempak, setiap layar berhenti: papan iklan, ponsel, terminal jalanan. Semua menampilkan satu kata yang berdenyut pelan di atas kota. FAJAR. Dan di bawahnya, hitung mundur."},
{c:"senja", side:"L", mood:"senyum"},
{n:"SENJA", t:"Protokol Fajar sudah menyala sejak kalian membuka pintu ruangan ini. Kalian pikir aku butuh kesaksian Renata untuk dimusnahkan? Tidak, sayang. Aku butuh RUANGANNYA. Inti Mercusuar. Satu-satunya sistem yang bisa menahan Fajar... dan barusan kalian antarkan aku masuk."},
{c:"syn", side:"R", mood:"kaget"},
{n:"SYN-0", t:"Perintah asing masuk ke intiku. Dia nyuntik dari pintu yang KALIAN buka. Anak Renata, aku... aku nggak bisa nahan ini lama. Dengar. Apa pun yang terjadi, kesaksian ibumu udah kusalin ke..."},
{fx:"glitch"},
{n:"", t:"Suara SYN-0 putus di tengah kalimat. Cahaya ruang putih meredup jadi abu-abu. Kayak lampu rumah yang dicabut meterannya."},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Mercusuar tua yang malang. Sepuluh tahun bersembunyi, jatuhnya karena rindu. Sama seperti pembuatnya."},
{c:"elias", side:"L", mood:"marah"},
{hide:"L"},
{c:"elias", side:"L", mood:"marah"},
{n:"ELIAS", t:"Prof. Senja. Anda ditahan atas..."},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Kapten Elias. Cek ponselmu."},
{n:"", t:"Elias ngecek. Rahangnya mengeras. Di layarnya: surat perintah penangkapan. Bukan buat Senja. Buat ELIAS. Tertanda pagi ini, atas tuduhan pembangkangan dan kerja sama dengan 'kelompok pemalsu arsip Lab SINYAL'."},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Kamu penyidik yang baik, nak. Sayangnya laporanmu naik ke meja yang salah. Semua meja adalah mejaku."},
{n:"SENJA", t:"Dan kalian bertiga... per menit ini, seluruh arsip Lab SINYAL berstatus PALSU. Lisensi kalian, riwayat kalian, gaji kalian. Menara sedang memproses. Kalian paham sendiri artinya, kan? Kalian sudah pernah jalan-jalan ke tempat orang-orang PALSU tinggal."},
{c:"nara", side:"L", mood:"marah"},
{hide:"L"},
{c:"nara", side:"L", mood:"marah"},
{n:"NARA", t:"IBU! Ibu bilang aku pantes pegang arsip! Ibu bilang label itu janji! Semua itu... semua itu bohong?!"},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"Tidak satu pun bohong, Nara sayang. Kamu memang pantas. Dan label memang janji. Aku hanya memastikan yang berjanji cuma satu orang. Pulanglah. Untukmu masih ada tempat di menara. Untuk mereka... sudah tidak."},
{ch:[
  {l:"\"Nara. Ikut kami. Kumohon.\"", say:"Nara. Lihat aku. Bukan dia, aku. Kamu yang bilang kamu jadi arsiparis biar nggak ada anak yang nunggu sebelas tahun. Orang yang di depanmu ini yang bikin anak-anak itu nunggu. Ikut kami."},
  {l:"\"Yang ditawarin dia itu bukan tempat. Itu kandang.\"", say:"Nara, yang dia tawarin itu bukan tempat di menara. Itu kandang yang hangat. Kamu udah pernah hidup di luar label yang jujur. Kamu mau bantu dia ngebangun dunia kayak gitu buat semua orang?"},
  {l:"(Ulurkan tangan. Biar dia yang milih.)", say:"Kamu nggak ceramah. Cuma ngulurin tangan ke Nara. Pilihan harus tetep punya dia. Sedetik. Dua detik. Nara natap Senja... terus naruh tangannya di tanganmu, gemeteran.", who:""}
]},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"...Maaf, Bu. Ibu yang ngajarin aku baca label. Jadi Ibu harusnya tahu. Aku bisa baca yang satu ini."},
{c:"senja", side:"L", mood:"normal"},
{n:"SENJA", t:"...Anak-anak zaman sekarang. Baiklah. Fajar terbit dalam dua belas jam. Setelah itu, setiap label di kota ini lahir dari satu tangan: tanganku. Tidak ada lagi hoaks, tidak ada keraguan, tidak ada Kota Bawah yang baru. Kota akan tidur nyenyak."},
{n:"SENJA", t:"Kejar aku kalau mau. Lapor kalau bisa. Ke siapa? Semua gerbang mengecek label. Dan label kalian, mulai malam ini... palsu."},
{n:"", t:"Dia pergi tanpa buru-buru. Nggak perlu buru-buru. Orang yang megang semua pintu nggak pernah lari."},

{m:"melan"},
{bg:"relay"},
{n:"", t:"Kalian keluar dari stasiun sebagai buronan. Ponsel kalian mati satu-satu, akunnya dibekukan. Di layar hape Arga yang masih sempet nyala, notifikasi terakhir: 'Akses Lab SINYAL: DICABUT'."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Pasukan menuju ke sini. Anak buah saya sendiri. Mereka cuma jalanin perintah, jangan salahkan mereka. Kita pencar. Bukti bersih dari stasiun saya pegang, mereka belum tahu itu ada."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Ke mana? Semua gerbang kota ngecek label. Kita nggak bisa ke lab, nggak bisa pulang, nggak bisa..."},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Bisa. Ada satu tempat di kota ini yang nggak pernah ngecek label. Yang nggak dianggap ada sama menara. Yang orang-orangnya paling ngerti gimana caranya hidup terus walau dicoret."},
{n:"NARA", t:"Kita turun. Ke Kota Bawah."},
{n:"", t:"Tapi jalur turun terdekat lewat simpul jaringan lama, dan Fajar udah mulai nyebar: gerbang-gerbang digital nulis ulang daftar cekalnya tiap menit, dan wajah kalian ada di semua daftar itu. Arga cuma bisa ngebobol satu celah, sekali, sebentar."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Celahnya kubuka sembilan puluh detik. Sistem cekal bakal nyodorin data kalian bolak-balik buat mancing kesalahan. Yang boleh lolos cuma identitas yang bener. Salah verifikasi, gerbang ngunci, kita ketangkep di sini. [NAMA]... kayak biasa. Kamu yang pegang."},
{q:{f:"final", n:10, pass:7, win:"c13win", lose:"c13lose", title:"MENEMBUS GERBANG FAJAR"}},

{lb:"c13lose"},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Gerbang nolak! Aku reset celahnya sekali lagi, TAPI CUMA SEKALI. Fokus. Anggep aja ini soal latihan. Soal latihan yang kalau salah kita dipenjara. ...Oke itu nggak ngebantu ya. FOKUS!"},
{q:{f:"final", n:10, pass:7, win:"c13win", lose:"c13lose", title:"GERBANG FAJAR · ULANG"}},

{lb:"c13win"},
{fx:"flash"},
{bg:"bawah"}, {m:"melan"},
{n:"", t:"Gerbang kebuka sembilan detik sebelum celahnya nutup. Kalian turun lewat tangga servis yang basah, makin dalam, sampai suara kota atas ilang dan yang kedengeran cuma hujan abadi Kota Bawah."},
{n:"", t:"Ibu warung bubur itu ngeliat kalian dateng. Basah, pucet, nggak bawa apa-apa. Dia nggak nanya apa-apa. Cuma nyendokin lima mangkok dan bilang, 'Makan dulu. Perkara belakangan.'"},
{c:"nara", side:"L", mood:"normal"},
{n:"NARA", t:"Selamat datang di satu-satunya tempat di Sanira yang nggak bisa direbut Bu Senja. Tempat yang dia buang sendiri. Ironis ya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kita kehilangan lab. Kehilangan nama. SYN-0 kena sandera di intinya sendiri. Dan dalam dua belas jam, Fajar nulis ulang semua label kota."},
{n:"VEGA", t:"Tapi kita masih punya bukti bersih Elias. Masih punya empat puluh dua dokumen Renata. Masih punya kalian. Dan Senja bikin satu kesalahan yang belum dia sadar."},
{n:"@", t:"...Dia ngelabelin kita PALSU. Padahal kita baru aja belajar dari tempat ini: orang-orang yang dicap palsu itu nggak berhenti ada. Mereka cuma berhenti keliatan. Dan orang yang nggak keliatan... susah dikejar."},
{c:"elias", side:"L", mood:"normal"},
{n:"ELIAS", t:"Dua belas jam. Satu kota yang harus dikasih tahu kebenarannya. Lima orang buronan dan satu mangkok bubur. ...Saya pernah mulai penyidikan dengan modal lebih sedikit. Sekali. Dan waktu itu saya kalah. Jadi ayo bikin kali ini beda."},
{n:"", t:"Di ujung meja, tas Arga bergetar. Dia ngerogoh, terus mukanya berubah aneh. Dari dalam tas, dia ngeluarin benda kecil yang dia bawa dari lab kemarin dan lupa dia balikin. Relai tua ibumu. Lampunya kedip-kedip. Nggak kayak biasa."},
{fx:"glitch"},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Dia... dia NERIMA sesuatu. Bukan mancarin. NERIMA. Frekuensi lamanya Renata, dari LUAR kota. Sinyal lemah banget, tapi enkripsinya... [NAMA]. Enkripsinya khas tangan ibumu."},
{n:"", t:"Satu kalimat nyusun di layar retak itu. Huruf demi huruf. Kayak diketik tangan yang jauh dan gemeteran."},
{fx:"flash"},
{n:"", t:"\"Labelku masih ASLI. Tunggu ibu.\""},
{n:"", t:"Mangkuk di tanganmu hampir jatuh. Di luar terpal warung, jauh di atas, melewati batas kota yang nggak keliatan dari sini, kamu tahu ada titik cahaya yang berkedip di kegelapan. Tiga pendek. Tiga panjang. Tiga pendek."},
{n:"", t:"Fajar terbit dua belas jam lagi. Ibumu masih hidup. Dan kota ini belum tahu apa-apa."},
{n:"", t:"BERSAMBUNG KE FINALE: SINYAL"},
{n:"", t:"Terima kasih sudah memainkan SINYAL: Protokol Fajar. Kisah terakhirnya sedang menunggu fajar."},
{end:"babak2"},
];

/* ---------- INTEGRASI ADITIF (tanpa mengubah naskah.js/story.js) ---------- */
(function mergeBabak2(){
  if(typeof NASKAH==="undefined" || !Array.isArray(NASKAH)){
    console.warn("[naskah2] NASKAH belum ada. Muat naskah2.js SETELAH naskah.js & story.js.");
    return;
  }
  /* guard anti dobel */
  if(NASKAH.some(n=>n.lb==="ch9")) return;

  /* 1) tokoh baru */
  if(typeof VN_CHARS!=="undefined") Object.assign(VN_CHARS, VN_CHARS2);

  /* 2) latar baru (VN_BG_FALLBACK milik story.js; const object → boleh
        ditambah propertinya). Kalau story.js belum dimuat, beri peringatan. */
  if(typeof VN_BG_FALLBACK!=="undefined") Object.assign(VN_BG_FALLBACK, VN_BG_FALLBACK2);
  else console.warn("[naskah2] VN_BG_FALLBACK belum ada. Muat naskah2.js SETELAH story.js agar latar baru ter-preload.");

  /* 3) ubah akhir epilog babak 1 menjadi jembatan pilihan */
  const i=NASKAH.findIndex(n=>n.end==="epilog");
  if(i>=0){
    NASKAH[i]={ch:[
      {l:"▶  LANJUT · BABAK II: PROTOKOL FAJAR", g:"ch9"},
      {l:"◈  AKHIRI PERJALANAN DI SINI", g:"tamat1"}
    ]};
  }

  /* 4) sambungkan naskah babak II */
  NASKAH.push(...NASKAH2);
})();
