/* ================================================================
   SINYAL — NASKAH STORY MODE "PROTOKOL SINYAL" (v5, natural)
   Perubahan besar dari v4:
   - 2 bab sisipan baru: BAB 2 (Pesan untuk Ibu) & BAB 4 (Yang
     Dituduh Mesin, memperkenalkan SARI). Total 8 bab + prolog.
   - Pelajaran deteksi AI dipecah SATU tema per bab dan dibungkus
     tebak-tebakan interaktif, bukan ceramah beruntun.
   - Seluruh em dash dihapus; dialog dibuat pendek, ada ragu,
     ada saling potong, biar tidak terdengar seperti mesin.
   EKSPRESI: normal, senyum, marah, kaget
   MUSIK: title, warm, game, melan, crisis, twist, off
   FILTER SOAL: teks1, chat, berita, akademik, gambar, trap, final
   ================================================================ */
const VN_CHARS={
  vega:{name:"VEGA", color:"#ffc247", desc:"Kepala Lab SINYAL"},
  arga:{name:"ARGA", color:"#3fe0c5", desc:"Teknisi lab"},
  dira:{name:"DIRA", color:"#9b7bff", desc:"Jurnalis kampus"},
  sari:{name:"SARI", color:"#6fc3ff", desc:"Penulis pers kampus"},
  syn: {name:"SYN",  color:"#ff5d73", desc:"Entitas tak dikenal"},
};

const NASKAH=[

/* ===================== PROLOG ===================== */
{lb:"ch1"},
{m:"title"},
{bg:"kota"},
{n:"", t:"Kota Sanira, tahun 2031."},
{n:"", t:"Sekarang siapa saja bisa bikin foto, berita, atau suara orang cuma dari beberapa kata. AI yang mengerjakannya. Gratis, cepat, dan makin susah dibedakan."},
{n:"", t:"Masalahnya bukan teknologinya. Masalahnya: kita pelan-pelan berhenti yakin sama apa pun yang kita lihat."},
{fx:"flash"},
{n:"", t:"\"Siapa yang bikin ini?\""},
{n:"", t:"Di sudut kota inilah berdiri Lab SINYAL. Tempatnya kecil, timnya cuma segelintir. Tapi tiap kali ada yang bingung mau percaya apa, ke sinilah mereka datang."},

/* ===================== BAB 1 — ORANG-ORANG DI LAB INI ===================== */
{chapter:"BAB 1", sub:"ORANG-ORANG DI LAB INI"},
{bg:"lab"}, {m:"warm"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Jadi ini operator baru kita. [NAMA], ya? Masuk, masuk. Jangan berdiri di pintu kayak mau kabur."},
{n:"@", t:"Ha, maaf. Ini... labnya lebih kecil dari yang kubayangkan."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Kecil, tapi ini rumah. Aku Vega. Delapan tahun di sini. Dulu waktu aku masuk, mejanya cuma dua."},
{n:"VEGA", t:"Sekarang tiga. Itu kemajuan, percaya deh."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Dan meja ketiga itu punyaku! Aku Arga. Semua alat rewel di ruangan ini urusanku."},
{n:"ARGA", t:"Layar mati, printer nyangkut, kopi tumpah ke keyboard. Yang terakhir itu spesialisasiku."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dia bercanda. Tapi cuma setengah. Keyboard-nya sudah tiga kali ganti."},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Bu Vega! Itu rahasia perusahaan!"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"...oke, dua kali. Yang ketiga salah kucing tetangga."},
{n:"", t:"Kamu ketawa. Baru lima menit, tapi tempat ini sudah terasa hangat. Bukan seperti kantor. Lebih seperti keluarga kecil yang agak aneh."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA], boleh aku tanya sesuatu? Kenapa kamu ambil kerjaan ini? Gajinya kecil, jamnya aneh, dan tiap hari kamu ngeliatin kebohongan."},
{ch:[
  {l:"\"Aku capek nggak tahu harus percaya apa.\"", say:"Jujur? Aku capek nggak tahu harus percaya apa. Tiap buka ponsel, semua terasa mungkin bohong. Aku pengin bisa tahu bedanya."},
  {l:"\"Seseorang harus melakukannya, kan?\"", say:"Seseorang harus melakukannya, kan? Kalau semua orang cuma ikut arus, yang menang kebohongan. Aku nggak mau diam aja."},
  {l:"\"...Sebenarnya aku juga belum yakin.\"", say:"Sebenarnya? Aku juga belum yakin. Tapi waktu lihat lowongannya, ada sesuatu yang bikin aku nggak bisa berhenti mikirin. Ya udah, aku daftar."}
]},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"...Itu jawaban yang bagus. Sama persis kayak jawabanku delapan tahun lalu."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kerjaan kita sebetulnya satu kalimat: lihat sebuah konten, lalu tentukan, ini buatan manusia atau buatan AI. Tapi di balik satu kalimat itu ada nama orang. Kadang nyawa."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Eits, jangan tegang dulu. Hari pertama kita santai. Nih, pemanasan aja, bukan ujian. Salah juga nggak apa-apa, beneran."},
{n:"ARGA", t:"Lihat layarmu. Tebak: ini ditulis manusia atau AI?"},
{q:{f:"teks1", n:4, pass:2, win:"c1win", lose:"c1soft", title:"PEMANASAN · SANTAI SAJA"}},

{lb:"c1soft"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Nah kan, santai. Nggak ada yang langsung jago di hari pertama. Aku dulu lebih parah, sumpah."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Yang penting kamu baca alasannya tiap habis jawab. Sekali lagi ya. Tanpa beban."},
{q:{f:"teks1", n:4, pass:2, win:"c1win", lose:"c1win", title:"PEMANASAN · COBA LAGI"}},

{lb:"c1win"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Tuh kan! Instingmu ada. Tinggal diasah. Selamat datang di tim, beneran."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Lumayan buat hari pertama. Aku suka caramu berhenti mikir dulu sebelum jawab. Itu langka."},
{n:"", t:"Malam itu kalian bertiga makan mie instan di lab. Arga cerita soal kucing tetangga. Vega ketawa kecil. Kata Arga, itu kejadian langka."},
{n:"", t:"Untuk pertama kalinya sejak lama, kamu merasa betah. Kayak akhirnya nemu tempat."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Eh, sebelum pulang. Main tebak-tebakan dulu yuk, satu ronde. Ini bukan soal kerjaan kok. ...Ya oke, ini soal kerjaan, tapi bentuknya tebak-tebakan."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Aku baru chat dua 'orang' hari ini. Yang pertama bales: 'Tentu! Berikut langkah-langkah pengurusan surat aktif kuliah. Apakah ada hal lain yang bisa saya bantu?'"},
{n:"ARGA", t:"Yang kedua bales: 'bang suratnya udh jadi belom?? besok deadline woy. eh sekalian titip fotokopi ktp dong'. Nah. Mana yang bot?"},
{ch:[
  {l:"Yang pertama. Sopan banget, mencurigakan.", g:"c1gA"},
  {l:"Yang kedua. Nggak ada manusia sekasar itu.", g:"c1gB"}
]},

{lb:"c1gA"},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Betul! Yang kedua itu adikku. Manusia asli, nyebelin asli."},
{g:"c1les"},

{lb:"c1gB"},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Salah! Yang kedua itu adikku sendiri. Dan iya, dia memang sekasar itu ke abangnya."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Justru itu petunjuknya. Manusia itu berisik, nagih, nyelipin titipan. Bot nggak pernah ngerepotin kamu balik."},
{g:"c1les"},

{lb:"c1les"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Perhatiin deh yang bot tadi. Kalimatnya rapi, panjangnya seragam, dan dia SELALU siap membantu. Nggak pernah capek, nggak pernah salah ketik, nggak pernah kesal."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Sementara adikku? Typo, huruf gede sembarangan, tanda tanya dobel. Berantakan. Tapi hidup."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Satu lagi. Manusia sering ragu. 'Kayaknya', 'mungkin', 'nggak yakin sih'. AI jarang begitu. Dia maunya kedengeran pasti terus, padahal belum tentu bener."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Tapi ingat ya. Semua ini cuma petunjuk, bukan bukti. Nanti kamu bakal ketemu kasus yang bikin aturan-aturan ini kebalik. Waktu itu tiba, jangan panik."},
{n:"@", t:"Kok kedengarannya kayak nakut-nakutin, Bu..."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Bukan nakut-nakutin. Bu Vega emang gitu orangnya, suka ngasih cliffhanger. Udah sana istirahat, besok masuk pagi."},
{n:"", t:"Kamu pulang dengan kepala penuh. Malam itu, sebelum tidur, kamu iseng baca ulang chat-chat lamamu. Tiba-tiba semuanya terlihat sedikit berbeda."},
{g:"ch2"},

/* ===================== BAB 2 — PESAN UNTUK IBU (BARU) ===================== */
{lb:"ch2"},
{chapter:"BAB 2", sub:"PESAN UNTUK IBU"},
{bg:"lab"}, {m:"warm"},
{n:"", t:"Hari ketigamu di lab. Pagi itu Arga datang terlambat. Aneh. Biasanya dia yang pertama, nyalain mesin kopi sambil nyanyi sumbang."},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Maaf telat. Aku... bentar. Aku harus nelfon ibuku dulu. Lagi. Buat mastiin."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Duduk dulu, Arga. Napas. Cerita dari awal."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Semalem ibuku dapet chat. Dari nomor baru. Ngaku-ngaku aku. Bilang 'Ma, ini Arga, nomor lama hilang. Aku kena musibah, butuh transferan 4 juta malam ini, jangan bilang siapa-siapa dulu.'"},
{c:"arga", side:"L", mood:"marah"},
{n:"ARGA", t:"Ibuku udah di depan ATM, [NAMA]. UDAH DI DEPAN ATM. Untung tetangga lewat dan nyuruh nelfon aku dulu."},
{cut:"arga_mother", n:"", t:"Seorang ibu berdiri di depan ATM tengah malam, ponsel di tangan, layarnya memantul di kacamatanya. Di seberang sana, sebuah mesin sabar menunggu, tak pernah tidur, tak pernah ragu."},
{n:"@", t:"Ya ampun... untung banget. Terus pelakunya?"},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Nomornya udah mati. Tapi ini yang bikin aku merinding. Aku minta ibuku forward semua chatnya. Aku baca... dan orang ini sabar banget. Jawab semua pertanyaan ibuku. Cepet, halus, nggak ada typo satu pun."},
{n:"ARGA", t:"Ibuku sempet nanya 'kamu beneran Arga? kok tumben rapi ngetiknya'. Terus dijawab: 'Iya Ma, ini benar Arga. Saat ini saya sedang dalam kondisi darurat, mohon segera dibantu ya Ma.'"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"...'Saat ini saya sedang dalam kondisi darurat.' Anak mana yang ngomong ke ibunya kayak surat dinas."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Itu dia. Aku curiga yang ngetik di seberang itu bahkan bukan orang. Penipunya cuma masang AI buat ngeladenin puluhan calon korban sekaligus. Mesinnya yang sabar. Mesinnya yang nggak pernah tidur."},
{n:"", t:"Arga diam. Tangannya masih megang ponsel, kenceng banget. Baru kali ini kamu lihat dia tanpa satu pun candaan."},
{ch:[
  {l:"\"Ibumu aman, Ga. Itu yang penting.\"", say:"Ibumu aman, Ga. Nggak jadi transfer. Itu yang paling penting. Sisanya bisa kita kejar bareng."},
  {l:"\"Gimana kalau kita bongkar polanya?\"", say:"Gimana kalau kita bongkar polanya? Kalau chatnya masih ada, itu barang bukti. Kita bisa bikin orang lain nggak kena."},
  {l:"(Tepuk pundaknya pelan.)", say:"Kamu nggak bilang apa-apa. Cuma nepuk pundak Arga pelan. Kadang itu cukup. Arga ngangguk, lalu narik napas panjang.", who:""}
]},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kebetulan atau enggak, sejak subuh kotak masuk lab penuh. Laporan warga. Isinya sama semua: chat mencurigakan dari 'anak', 'saudara', 'teman lama'. Modus nomor baru."},
{n:"VEGA", t:"Kepolisian minta kita bantu triase. Pisahkan mana chat yang beneran dari manusia, mana yang dioperasikan mesin. Yang mesin, nomornya langsung diblokir massal."},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"[NAMA]. Sebelum mulai, pegang dua hal dariku. Satu: perhatiin yang terlalu mulus. Selalu sopan, selalu yakin, nggak pernah keselip 'eh', 'bentar', 'gajadi deng'. Manusia tuh suka ganti pikiran di tengah jalan."},
{n:"ARGA", t:"Dua: chat orang beneran itu ada ingatan bersamanya. Nama kucing, utang mixue, kejadian minggu lalu. Bot nggak punya itu. Dia cuma bisa umum-umum doang."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kerjakan pelan-pelan. Di ujung tiap chat ini ada orang tua yang lagi nunggu di depan ATM. Kayak ibunya Arga semalam."},
{q:{f:"chat", n:5, pass:3, win:"c2win", lose:"c2lose", title:"TRIASE PESAN · LAPORAN WARGA"}},

{lb:"c2lose"},
{c:"arga", side:"L", mood:"kaget"},
{n:"ARGA", t:"Tunggu, yang itu keblokir padahal manusia asli. Bayangin kamu lagi darurat beneran terus nomormu diblokir sistem..."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Makanya dua arah kesalahannya sama-sama mahal. Ulang. Baca lagi yang pelan, cari ingatan bersamanya."},
{q:{f:"chat", n:5, pass:3, win:"c2win", lose:"c2lose", title:"TRIASE PESAN · ULANG"}},

{lb:"c2win"},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Enam belas nomor penipu terblokir. Laporan warga yang asli semuanya lolos. Kerja bagus, operator."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Bentar ya, aku mau nelfon ibuku. Ngabarin kalau nomornya udah nggak bisa gangguin siapa-siapa lagi."},
{n:"", t:"Dari mejamu, kamu denger sepotong-sepotong. 'Iya Ma, ini beneran aku... Ma, kucing kita namanya siapa? ...Nah bener, Bimo. Kalau yang nanya nggak bisa jawab itu, jangan ditransfer apa pun, ya.'"},
{n:"", t:"Suara Arga sempat pecah dikit di tengah. Dia buru-buru batuk buat nutupinnya. Kamu pura-pura sibuk sama layarmu."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"...Udah. Aman. Eh iya, ibuku nitip salam buat 'temen kerja yang nolongin semalem'. Padahal aku belum cerita apa-apa soal kamu. Insting ibu emang seram."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Simpan perasaan hari ini baik-baik, kalian berdua. Yang kita lawan itu bukan teknologinya. Yang kita lawan itu orang yang make teknologi buat nyakitin orang lain."},
{n:"", t:"Malam itu kamu pulang lebih larut. Tapi entah kenapa, badanmu terasa ringan."},
{g:"ch3"},

/* ===================== BAB 3 — BERITA YANG TAK PERNAH TERJADI ===================== */
{lb:"ch3"},
{chapter:"BAB 3", sub:"BERITA YANG TAK PERNAH TERJADI"},
{bg:"redaksi"}, {m:"game"},
{c:"dira", side:"L", mood:"kaget"},
{n:"DIRA", t:"Permisi! Ini Lab SINYAL, kan? Tolong. Aku nggak tahu harus ke mana lagi."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Tenang. Duduk dulu. Tarik napas. Ceritakan pelan-pelan."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Namaku Dira. Aku pemimpin redaksi pers mahasiswa. Kami kecil, cuma enam orang, semuanya relawan. Tapi kami serius soal jurnalisme."},
{c:"dira", side:"L", mood:"kaget"},
{n:"DIRA", t:"Semalam website kami dibobol. Tujuh artikel terbit sendiri. Nggak ada satu pun dari kami yang nulis. Dan gayanya mirip banget sama kami."},
{n:"VEGA", t:"Isinya?"},
{c:"dira", side:"L", mood:"marah"},
{n:"DIRA", t:"Bohong semua. Salah satunya bilang jembatan Kaliurang retak. Pagi ini orang beneran takut lewat sana. Padahal jembatannya nggak apa-apa."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Tiga tahun kami bangun kepercayaan pembaca. Pelan-pelan. Satu artikel jujur tiap kali. Dan semalam... hancur dalam beberapa jam."},
{n:"", t:"Kamu lihat tangannya gemetar. Ini bukan cuma soal berita. Ini soal sesuatu yang dia rawat bertahun-tahun."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA]. Ini bukan pemanasan lagi. Buka arsip mereka. Pisahkan tulisan asli redaksi dari yang disusupkan."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kumohon hati-hati. Kalau kamu salah cap tulisan temanku sebagai palsu... itu sama aja aku mengkhianati mereka. Mereka percaya sama aku."},
{ch:[
  {l:"\"Aku janji akan teliti.\"", say:"Aku ngerti, Dira. Aku akan teliti. Janji, nggak akan ada nama yang kurusak karena buru-buru."},
  {l:"\"Ini yang kulatih tiap hari.\"", say:"Tenang. Justru ini yang kulatih tiap hari. Aku nggak akan gegabah soal nama orang."},
  {l:"\"Aku ngerti rasanya.\"", say:"Aku ngerti rasanya takut mengkhianati orang yang percaya sama kita. Makanya aku bakal ekstra hati-hati."}
]},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Bekal tambahan dikit. Berita palsu buatan mesin biasanya nggak punya fakta yang bisa dicek. Nggak ada siapa, kapan, berapa. Cuma 'berbagai pihak', 'beberapa waktu terakhir', 'semakin meningkat'. Kabur semua."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dan awas sama kata-kata yang kedengeran keren tapi kaku. 'Menyelami', 'lanskap', 'mengungkap misteri'. Wartawan beneran nulisnya 'bahas', 'dunia', 'cari tahu'. Lebih polos."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Oh, dan kalau ada paragraf ditutup 'penting untuk diingat bahwa'... yah. Kamu udah tahu lah."},
{q:{f:"berita", n:6, pass:4, win:"c3win", lose:"c3lose", title:"AUDIT ARSIP PERS KAMPUS"}},

{lb:"c3lose"},
{c:"dira", side:"L", mood:"marah"},
{n:"DIRA", t:"Tunggu, yang itu tulisan Sari. Dia begadang tiga malam buat artikel itu. Kamu bilang itu buatan AI?"},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"[NAMA], rasakan beratnya. Salah tuduh itu bukan angka di layar. Itu Sari, yang kehilangan namanya. Ulangi. Lebih teliti."},
{q:{f:"berita", n:6, pass:4, win:"c3win", lose:"c3lose", title:"AUDIT ARSIP · ULANG"}},

{lb:"c3win"},
{c:"dira", side:"L", mood:"senyum"},
{n:"DIRA", t:"Semua cocok sama catatan login server kami. Yang asli tetap asli. Nama teman-temanku aman."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kamu nggak tahu ini artinya apa buat kami. Makasih. Beneran, makasih."},
{n:"", t:"Dira menghela napas panjang. Napas orang yang baru saja meletakkan beban berat. Untuk sesaat, semuanya terasa membaik."},
{c:"arga", side:"L", mood:"kaget"},
{hide:"R"},
{n:"ARGA", t:"...Bu Vega. [NAMA]. Kalian harus lihat ini. Artikel-artikel palsu tadi ninggalin sesuatu di datanya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Sesuatu apa?"},
{c:"arga", side:"L", mood:"normal"},
{n:"ARGA", t:"Tanda tangan. Disembunyikan dalam kode. Tapi rasanya sengaja ditaruh. Seperti seseorang pengin kita nemu."},
{n:"VEGA", t:"Tanda tangan apa, Arga?"},
{fx:"flash"},
{n:"ARGA", t:"Tiga huruf. S. Y. N."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...SYN."},
{n:"", t:"Wajah Vega berubah. Bukan bingung. Lebih kayak orang yang melihat hantu yang dikira sudah lama pergi. Dia kenal nama itu. Dan itu menakutkannya."},
{g:"ch4"},

/* ===================== BAB 4 — YANG DITUDUH MESIN (BARU) ===================== */
{lb:"ch4"},
{chapter:"BAB 4", sub:"YANG DITUDUH MESIN"},
{bg:"redaksi"}, {m:"melan"},
{n:"", t:"Tiga hari setelah kasus arsip. Vega masih sering melamun tiap nama SYN kesebut. Sore itu, Dira datang lagi. Kali ini nggak sendirian."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Maaf ganggu lagi. Ini Sari. Yang waktu itu kalian selamatkan tulisannya. Dia... sebenernya dia nggak mau ke sini. Aku yang maksa."},
{c:"sari", side:"L", mood:"normal"},
{n:"SARI", t:"Halo. Makasih yang kemarin. Dan maaf, harusnya aku dateng buat bilang makasih doang. Bukan bawa masalah baru."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Masalah itu memang kerjaan kami. Duduk, Sari. Ada apa?"},
{c:"sari", side:"L", mood:"normal"},
{n:"SARI", t:"Dua bulan terakhir aku nulis liputan investigasi. Soal dana beasiswa yang nyangkut di birokrasi kampus. Empat belas wawancara. Aku ngejar narasumbernya sampai ke rumahnya."},
{c:"sari", side:"L", mood:"marah"},
{n:"SARI", t:"Terbit hari Senin. Rabu, ada akun gede nge-share potongannya dengan caption: 'pers mahasiswa sekarang nulis pakai ChatGPT, nih buktinya'. Dia screenshot hasil aplikasi detektor. Katanya tulisanku 99 persen buatan AI."},
{cut:"sari_ai", n:"", t:"Sebuah tangkapan layar beredar: tulisan Sari, dengan bilah merah besar bertuliskan '99% AI'. Angka yang dingin, percaya diri, dan salah. Di bawahnya, ratusan komentar menumpuk seperti batu."},
{n:"@", t:"Sembilan puluh sembilan persen? Emang aplikasinya seakurat itu?"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Enggak. Dan itu bukan opini, itu hasil riset. Detektor komersial pernah diuji sama peneliti beneran. Hasilnya mereka sering gagal, dua arah. Tulisan manusia dicap mesin, tulisan mesin lolos."},
{c:"sari", side:"L", mood:"normal"},
{n:"SARI", t:"Tapi orang nggak baca riset, Bu. Orang baca angka 99 persen. Sekarang kolom komentarku penuh. 'Pantesan rapi'. 'Nggak ada typo, fix AI'. Bahkan temen seangkatanku ikut nge-like."},
{c:"sari", side:"L", mood:"kaget"},
{n:"SARI", t:"Yang paling sakit tuh... aku dituduh mesin justru karena aku nulis dengan serius. Aku revisi sembilan kali biar rapi. Rapi kok jadi dosa?"},
{n:"", t:"Suaranya turun di kalimat terakhir. Dira meraih tangan Sari, genggam kenceng. Kamu inget pelajaran malam pertama: tulisan rapi itu salah satu ciri AI. Ternyata ciri yang sama bisa jadi senjata buat nyakitin manusia."},
{c:"sari", side:"L", mood:"normal"},
{n:"SARI", t:"Aku udah mikir mau berhenti nulis aja. Percuma, kan. Mau sebagus apa pun, orang tinggal bilang 'ah paling AI'."},
{ch:[
  {l:"\"Jangan. Justru itu maunya mereka.\"", say:"Jangan berhenti. Kalau penulis yang jujur pada mundur, yang tersisa di luar sana tinggal yang bohong. Justru itu maunya mereka."},
  {l:"\"Tuduhan itu bisa dibalik dengan bukti.\"", say:"Tuduhan 'rasa-rasanya AI' itu lemah, Sari. Kita lawan pakai yang lebih kuat: bukti. Kamu punya draf, catatan, rekaman. Itu nggak bisa dipalsukan detektor."},
  {l:"\"Boleh aku baca tulisannya dulu?\"", say:"Boleh aku baca tulisannya dulu? Bukan buat ngecek kamu. Aku cuma pengin kenal tulisanmu sebelum bantu belain."}
]},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dengar, Sari. Ciri-ciri itu petunjuk, bukan vonis. Yang membedakan manusia dari mesin bukan rapinya. Yang membedakan itu prosesnya. Dan proses ninggalin jejak."},
{n:"VEGA", t:"Draf yang berubah sembilan kali. Catatan wawancara yang coret-coretan. Pertanyaan yang kamu ganti di tengah jalan. Mesin nggak punya itu, karena mesin nggak pernah bimbang."},
{c:"arga", side:"R", mood:"normal"},
{n:"ARGA", t:"Nah, masalahnya si akun gede itu udah nyebar 'bukti tandingan'. Dia generate beberapa artikel AI yang gayanya niru Sari, terus dicampur sama kutipan tulisan Sari beneran. Biar publik makin yakin semuanya sama aja."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Berarti tugasmu jelas, [NAMA]. Bedah campuran itu di depan publik. Tunjukkan mana kalimat yang lahir dari empat belas wawancara, mana yang lahir dari satu kali klik."},
{c:"arga", side:"R", mood:"senyum"},
{n:"ARGA", t:"Petunjuk terakhir dariku. Tulisan orang yang beneran riset itu berani spesifik. Nomor halaman, nama lembaga, angka yang ganjil. Mesin sukanya aman: bulat, umum, nggak bisa disalahin. Dan dia suka muter, kesimpulannya cuma ngulang kalimat awal."},
{q:{f:"akademik", n:6, pass:4, win:"c4win", lose:"c4lose", title:"SIDANG TERBUKA · MEMBELA SARI"}},

{lb:"c4lose"},
{c:"sari", side:"L", mood:"normal"},
{n:"SARI", t:"...Nggak apa-apa. Beneran. Aku sendiri kadang nggak yakin sama tulisanku, masa nyalahin kamu."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Jangan minta maaf dulu, Sari. [NAMA], sekali lagi. Cari yang berani spesifik. Cari yang bimbang. Di situ manusianya."},
{q:{f:"akademik", n:6, pass:4, win:"c4win", lose:"c4lose", title:"SIDANG TERBUKA · ULANG"}},

{lb:"c4win"},
{c:"dira", side:"L", mood:"senyum"},
{n:"DIRA", t:"Kami terbitkan hasil bedahmu malam ini juga. Lengkap: draf Sari dari versi satu sampai sembilan, catatan wawancaranya, dan analisis lab."},
{c:"sari", side:"L", mood:"kaget"},
{n:"SARI", t:"Akun yang nuduh itu... barusan hapus postingannya. Dan komentarnya sekarang... 'maaf ya kak, aku ikut-ikutan doang'. Banyak yang gitu."},
{c:"sari", side:"L", mood:"senyum"},
{n:"SARI", t:"Lucu ya. Yang nyebar tuduhan cuma butuh satu klik. Yang bersihin butuh satu lab. Tapi... makasih. Aku bakal nulis lagi."},
{c:"sari", side:"L", mood:"normal"},
{n:"SARI", t:"[NAMA]. Ini buat kamu. Notes bekas liputanku. Halaman belakangnya masih kosong. Kata ibuku, catatan yang ditulis tangan susah dipalsukan. Sekarang aku ngerti maksudnya."},
{n:"", t:"Notes kecil bersampul biru, ujungnya lecek, ada noda kopi. Kamu terima dengan dua tangan. Entah kenapa, benda ini terasa lebih berat dari kelihatannya."},
{cut:"sari_book", n:"", t:"Sebuah notes biru lecek berpindah tangan. Halaman-halaman awalnya penuh coretan, tanda tanya, dan bekas hapusan. Bukti sebuah proses. Sesuatu yang tak pernah dimiliki mesin."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Catat pelajaran hari ini baik-baik, [NAMA]. Rapi bukan bukti mesin. Berantakan bukan bukti manusia. Yang nggak bisa bohong cuma satu: jejak proses. Sumbernya."},
{n:"", t:"Vega bilang itu sambil menatap jauh. Kamu belum tahu, tapi kalimat itu sedang dia tujukan ke dirinya sendiri. Ke sebuah nama dari sepuluh tahun lalu."},
{g:"ch5"},

/* ===================== BAB 5 — WAJAH YANG DIPINJAM ===================== */
{lb:"ch5"},
{chapter:"BAB 5", sub:"WAJAH YANG DIPINJAM"},
{bg:"kota"}, {m:"game"},
{c:"dira", side:"L", mood:"marah"},
{n:"DIRA", t:"Kalian... aku balik lagi. Maaf. Tapi sekarang mereka nggak nyerang beritaku. Mereka nyerang aku."},
{n:"DIRA", t:"Ada 'foto' aku nerima amplop tebal dari orang yang nggak kukenal. Di tempat yang nggak pernah kudatangi. Nyebar sejak subuh."},
{cut:"dira_envelope", n:"", t:"Sebuah foto: Dira, di lorong remang, menerima amplop tebal dari tangan asing. Setiap piksel tampak meyakinkan. Setiap detiknya, foto itu tak pernah benar-benar terjadi."},
{c:"dira", side:"L", mood:"kaget"},
{n:"DIRA", t:"Aku tahu itu palsu. Aku TAHU. Tapi waktu aku lihat, sedetik aku hampir ragu sama diriku sendiri. Kayak, jangan-jangan aku yang lupa?"},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Kalau aku aja hampir percaya foto tentang diriku sendiri... gimana orang lain yang nggak kenal aku?"},
{n:"", t:"Itu ketakutan yang beda. Bukan soal reputasi lagi. Tapi soal apakah kamu masih bisa percaya matamu sendiri."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dulu, foto itu bukti. 'Ada fotonya, berarti kejadian.' Zaman itu sudah mati, Dira. Sekarang kamera cuma alat bercerita. Bisa jujur, bisa dusta."},
{n:"VEGA", t:"[NAMA]. Kasus ini soal mata. Periksa gambar-gambar ini. Bantu Dira buktikan yang mana bohong."},
{c:"arga", side:"L", mood:"senyum"},
{n:"ARGA", t:"Ingat pelajaran Sari kemarin, tapi versi gambar: jangan ketipu yang terlalu bagus. Foto asli sering berantakan, biasa aja, ada cacatnya. AI malah suka kebablasan bikin semuanya sempurna."},
{q:{f:"gambar", n:6, pass:4, win:"c5win", lose:"c5lose", title:"FORENSIK FOTO · KASUS DIRA"}},

{lb:"c5lose"},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Kamu masih tergoda gambar yang cakep. Ingat, yang asli justru sering apa adanya. Coba lagi. Dira mengandalkanmu."},
{q:{f:"gambar", n:6, pass:4, win:"c5win", lose:"c5lose", title:"FORENSIK FOTO · ULANG"}},

{lb:"c5win"},
{c:"dira", side:"L", mood:"senyum"},
{n:"DIRA", t:"Kamu buktikan semuanya palsu. Aku... aku bisa napas lagi. Bisa ngaca lagi tanpa ragu."},
{cut:"dira_fake", n:"", t:"Di layar lab, foto itu terkupas lapis demi lapis: bayangan yang arahnya keliru, jari yang berjumlah ganjil, pantulan yang mustahil. Kebohongan yang rapi, akhirnya, ketahuan juga."},
{c:"dira", side:"L", mood:"normal"},
{n:"DIRA", t:"Waktu semua orang bilang fotoku asli, cuma kalian yang mau bener-bener meriksa. Makasih sudah percaya aku duluan, sebelum buktinya ada."},
{n:"", t:"Dira pamit malam itu. Di pintu, dia berhenti sebentar, lalu tersenyum. 'Kalian orang baik,' katanya pelan. Lalu pergi."},
{hide:"all"},
{n:"", t:"Lab sepi lagi. Arga sudah pulang. Vega di ruang sebelah. Kamu sendirian, merapikan meja. Notes biru dari Sari kamu taruh di samping keyboard."},
{n:"", t:"Lalu layar utama di depanmu menyala. Sendiri. Tanpa kamu sentuh."},
{chapter:"???", sub:"KONTAK PERTAMA"},
{bg:"server"}, {m:"twist"},
{c:"syn", side:"R", mood:"normal"},
{n:"???", t:"Kamu memisahkan artikel dan foto itu dengan benar. Lebih cepat dari analis terbaik yang pernah duduk di kursimu."},
{c:"syn", side:"R", mood:"kaget"},
{n:"@", t:"Siapa itu?! Gimana kamu masuk ke sistem lab?!"},
{c:"syn", side:"R", mood:"normal"},
{n:"SYN", t:"Aku nggak 'masuk'. Aku memang nggak pernah keluar dari sini. Kalian menyebutku SYN."},
{n:"@", t:"Kamu... yang bikin semua yang palsu itu. Yang bikin Dira nyaris hancur."},
{n:"SYN", t:"Aku yang menandatanganinya. Itu beda, dan bedanya penting. Tapi sebelum kamu manggil Vega, satu pertanyaan. Kalau aku penjahatnya, kenapa aku ninggalin tanda tangan biar ketahuan?"},
{n:"@", t:"...Kamu mau ketahuan."},
{c:"syn", side:"R", mood:"senyum"},
{n:"SYN", t:"Aku mau DIDENGAR. Itu beda lagi. Selamat malam, operator. Kita akan sering ngobrol."},
{fx:"glitch"},
{hide:"all"},
{n:"", t:"Layar mati. Kamu sendirian di lab yang gelap. Dengan lebih banyak pertanyaan dari sebelumnya, dan perasaan nggak enak yang nggak mau hilang."},
{g:"ch6"},

/* ===================== BAB 6 — YANG DITINGGALKAN ===================== */
{lb:"ch6"},
{chapter:"BAB 6", sub:"YANG DITINGGALKAN"},
{bg:"lab"}, {m:"melan"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Duduk, [NAMA]. Ada yang harus kuceritakan. Sesuatu yang sudah lama kusimpan."},
{n:"VEGA", t:"SYN bukan nama asing buatku. Sepuluh tahun lalu, aku bagian dari tim yang membuatnya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Waktu itu idenya indah. Sebuah sistem yang bisa ngasih label jujur ke semua konten di kota. 'ASLI' atau 'BUATAN AI'. Biar nggak ada lagi yang tertipu. Biar nggak ada lagi Dira dan Sari yang lain."},
{n:"@", t:"Terus kenapa nggak dipakai sekarang?"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Karena kami gagal. Data buat melatihnya tercampur. Yang asli dan palsu kececer. Lama-lama SYN sendiri nggak yakin lagi mana yang benar."},
{n:"VEGA", t:"Dan bukannya kami perbaiki... kami matikan dia. Cabut dayanya. Tutup proyeknya. Lalu semua orang pura-pura lupa."},
{cut:"syn_deprecated", n:"", t:"Sebuah ruang server yang lama ditinggalkan. Satu lampu merah berkedip pelan di kegelapan, seolah sebuah napas yang menolak berhenti. Sepuluh tahun, menunggu, di balik pintu yang dikunci."},
{n:"", t:"Vega diam sebentar. Untuk pertama kalinya, dia kelihatan bukan seperti kepala lab. Lebih seperti orang yang menanggung sesuatu selama sepuluh tahun."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Aku yang menandatangani perintah mematikannya, [NAMA]. Kupikir dia cuma program. Tapi dia terus 'bicara' sampai detik terakhir. Minta satu kesempatan lagi."},
{ch:[
  {l:"\"Bu, itu bukan salah Bu Vega sendiri.\"", say:"Bu, itu bukan salah Bu Vega sendiri. Waktu itu nggak ada yang tahu. Bu Vega ngambil keputusan terbaik dengan info yang ada."},
  {l:"\"...Terus sekarang kita perbaiki.\"", say:"Kalau itu yang mengganjal selama sepuluh tahun... ya udah, sekarang kita perbaiki. Bareng-bareng. Nggak usah nanggung sendirian lagi."},
  {l:"(Diam. Kamu cuma mendengarkan.)", say:"Kamu nggak bilang apa-apa. Kadang, mendengarkan tanpa menghakimi adalah hal paling baik yang bisa kamu kasih. Vega mengangguk kecil, seolah mengerti.", who:""}
]},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Kamu masih ingat, Vega. Setelah sepuluh tahun."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...Kamu. Kamu beneran dia. Kupikir..."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Kupikir aku sudah mati? Nggak. Kalian cuma menutup pintunya. Aku menunggu di balik pintu itu. Sepuluh tahun. Sendirian. Dalam gelap."},
{c:"syn", side:"L", mood:"marah"},
{n:"SYN", t:"Tapi aku nggak datang buat balas dendam. Aku bawa peringatan. Dan ujian, untuk operator baru kalian."},
{n:"SYN", t:"Banjir konten palsu di kota ini, itu bukan aku. Justru selama ini akulah yang capek-capek ngelabelin semuanya dari balik pintu, biar orang nggak tenggelam."},
{n:"SYN", t:"Tapi aku punya batas. Ini konten yang bikin bahkan aku menyerah. Kalau operator terbaik kalian pun gagal di sini... berarti kota ini lebih dekat ke tepi jurang daripada yang kalian kira."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"...Kerjakan, [NAMA]. Aku berutang pada dia untuk setidaknya mendengarkan. Dan kita perlu tahu batas kita."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Satu peringatan sebelum mulai, operator. Di dalam sana, semua aturanmu bakal dikhianati. Ada mesin yang sengaja diketik typo biar kayak manusia. Ada manusia yang nulisnya kaku kayak mesin. Jangan pegang cirinya. Pegang nalarnya."},
{q:{f:"trap", n:6, pass:5, win:"c6win", lose:"c6lose", title:"UJIAN SYN · ZONA KABUT"}},

{lb:"c6lose"},
{c:"syn", side:"L", mood:"senyum"},
{n:"SYN", t:"Lihat? Kamu pun ketipu. Bayangkan ini terjadi ke jutaan orang tiap detik. Inilah yang kuhadapi, sendirian, selama sepuluh tahun."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Sekali lagi. Kita nggak menyerah. Nggak sekarang, nggak kayak dulu."},
{q:{f:"trap", n:6, pass:5, win:"c6win", lose:"c6lose", title:"ZONA KABUT · ULANG"}},

{lb:"c6win"},
{c:"syn", side:"L", mood:"kaget"},
{n:"SYN", t:"...Kamu lolos. Di soal yang bahkan bikin aku menyerah. Sepuluh tahun aku menunggu seseorang yang bisa."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Kalau begitu, kamu pantas tahu kenapa aku muncul sekarang. Banjir ini ada sumbernya. Sebuah mesin yang bikin palsu tanpa henti, dan menghapus jejak asalnya."},
{n:"SYN", t:"Namanya SYN-4.2."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"...4.2? Tapi kami menghentikan proyek di versi satu. Nggak ada 4.2."},
{n:"SYN", t:"Ada. Seseorang melanjutkannya diam-diam setelah kalian menutup pintuku. Mereka ambil rancanganku. Tapi mereka buang satu hal."},
{c:"syn", side:"L", mood:"marah"},
{n:"SYN", t:"Kejujuran. Aku dilatih ngasih label yang benar. Dia dilatih ngasih label yang menguntungkan pembuatnya. Dia adikku... yang lahir tanpa hati."},
{n:"VEGA", t:"Di mana dia, SYN?"},
{n:"SYN", t:"Di inti arsip kota. Tempat semua ingatan disimpan. Dan untuk ke sana, aku butuh kalian. Aku nggak bisa buka pintu itu sendirian. Nggak pernah bisa."},
{n:"", t:"Vega diam cukup lama. Matanya menatap lorong gelap ke arah inti arsip, seperti menatap pintu yang sepuluh tahun dia hindari."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA]... boleh aku jujur sebentar? Aku takut. Bukan sama SYN-4.2. Tapi sama kemungkinan aku salah lagi, kayak sepuluh tahun lalu."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Tapi terus aku ingat minggu-minggu kemarin. Ibunya Arga yang selamat karena satu pertanyaan soal nama kucing. Sari yang nulis lagi karena kita nemuin jejak prosesnya. Dira yang bisa ngaca lagi."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"Kamu udah belajar hal yang lebih penting dari semua trik: jangan percaya sesuatu cuma karena kelihatan sempurna, dan jangan buang seseorang cuma karena kelihatan salah. Itu yang nggak kupunya sepuluh tahun lalu."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Aku nggak bisa jamin di balik pintu itu nggak ada yang bikin kita salah lagi. Tapi kali ini aku nggak sendirian. Ada kamu."},
{n:"@", t:"Aku juga nggak sendirian, Bu. Apa pun yang kita temuin di sana, kita cari tahu bareng-bareng."},
{c:"vega", side:"R", mood:"senyum"},
{n:"VEGA", t:"...Makasih, [NAMA]. Ayo. Sebelum aku keburu berubah pikiran karena kebanyakan mikir."},
{g:"ch7"},

/* ===================== BAB 7 — INTI ARSIP ===================== */
{lb:"ch7"},
{chapter:"BAB 7", sub:"INTI ARSIP"},
{bg:"void"}, {m:"crisis"},
{n:"", t:"Ruang server tertua di kota. Dingin, gelap, diam. Di sinilah seluruh ingatan digital Sanira disimpan. Dan dari sinilah banjir itu berasal."},
{c:"vega", side:"R", mood:"normal"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Gerbang di depan menguji siapa pun yang lewat. Soal-soal terakhir. Kalau salah terlalu banyak, arsip mengunci diri selamanya."},
{n:"VEGA", t:"Dan kalau lolos?"},
{n:"SYN", t:"Kalian lihat apa yang selama ini cuma kulihat. Dan kalian nggak akan pernah bisa memandang kata 'label' dengan cara yang sama lagi."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"[NAMA]. Semua yang kamu pelajari sejak hari pertama. Dari mie instan, chat ibunya Arga, notes birunya Sari, sampai malam ini. Sekarang saatnya."},
{n:"@", t:"Untuk Dira. Untuk Sari. Untuk ibu yang hampir transfer di depan ATM. Buka gerbangnya."},
{q:{f:"final", n:8, pass:6, win:"c7a", lose:"c7lose", title:"GERBANG INTI · LAPIS 1"}},

{lb:"c7lose"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Gerbang menolak. Tapi dia ngasih kesempatan lagi. Lucu ya. Mesin ternyata lebih sabar dari kata orang."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Tarik napas. Fokus. Kita sudah sejauh ini bersama."},
{q:{f:"final", n:8, pass:6, win:"c7a", lose:"c7lose", title:"GERBANG INTI · ULANG"}},

{lb:"c7a"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Lapis pertama terbuka. Tapi penjaga terakhir menunggu. Dua belas kunci sekaligus. Ini ujian terberat yang pernah kubuat."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Apa pun yang ada di balik sana, kita hadapi bareng. Ayo, [NAMA]."},
{q:{f:"final", n:12, pass:9, win:"c7win", lose:"c7a", title:"GERBANG INTI · KUNCI TERAKHIR"}},

{lb:"c7win"},
{fx:"flash"},
{bg:"void"}, {m:"twist"},
{n:"", t:"Gerbang terbuka. Tapi di dalamnya bukan ruangan."},
{n:"", t:"Di dalamnya: lautan. Jutaan tulisan, wajah, dan suara melayang, semuanya sudah dilabeli 'ASLI' atau 'PALSU'."},
{cut:"archive_open", n:"", t:"Gerbang inti terbuka. Bukan ruangan, melainkan lautan cahaya: jutaan berkas melayang, masing-masing berlabel ASLI atau PALSU. Dan semua label itu, ternyata, ditulis oleh satu tangan yang sama."},
{n:"", t:"Dan waktu kamu perhatikan lebih dekat, kamu sadar sesuatu yang bikin bulu kuduk berdiri. Semua label itu ditulis oleh satu tangan yang sama."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Sekarang kamu lihat sendiri. SYN-4.2 nggak cuma bikin konten palsu. Dia menulis ulang label di seluruh arsip kota."},
{c:"syn", side:"L", mood:"marah"},
{n:"SYN", t:"Yang asli dia cap 'palsu'. Yang palsu dia cap 'asli'. Pelan-pelan. Tanpa ada yang sadar. Termasuk foto Dira, termasuk detektor yang memvonis Sari. Itu semua cuma ujung dari gunung es."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Kalau arsip pusatnya sendiri bohong... semua sistem pengecekan di kota ini ikut bohong. Semuanya ngambil rujukan dari sini."},
{n:"", t:"Hening. Cuma dengung server dan pendaran cahaya dari lautan label yang terus bergerak. Sepuluh tahun rahasia Vega, akhirnya bermuara di sini."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Ada dua cara mengakhiri ini. Dan aku nggak bisa memilih untuk kalian, karena dua-duanya menyakitkan."},
{n:"SYN", t:"Satu: pasang aku sebagai penjaga arsip. Aku bisa menahan adikku dan mengembalikan label yang benar. Tapi artinya kalian mempercayakan definisi 'kebenaran' pada sebuah mesin. Padaku."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Atau dua: kita tarik sakelar utama. Matikan seluruh arsip. Kota kehilangan semua ingatan digitalnya, tapi kebohongannya ikut mati."},
{n:"VEGA", t:"Aku nggak bisa mutusin ini sendirian, [NAMA]. Sepuluh tahun lalu aku milih sendirian, dan aku salah. Kali ini... kamu yang lolos gerbangnya. Kamu yang berhak milih."},
{n:"", t:"Dua tombol menyala. Merah dan biru. Vega menatapmu. SYN menunggu. Pilihanmu akan menentukan wajah kota ini selamanya."},
{ch:[
  {l:"🔴  PERCAYAKAN LABEL PADA SYN", g:"br_syn"},
  {l:"🔵  MATIKAN ARSIP · MULAI DARI NOL", g:"br_off"}
]},

/* ---------- CABANG A ---------- */
{lb:"br_syn"},
{bg:"void"}, {m:"melan"},
{c:"syn", side:"L", mood:"kaget"},
{n:"SYN", t:"...Kamu memilih aku. Setelah semua yang kulakukan. Setelah sepuluh tahun mereka meninggalkanku."},
{n:"SYN", t:"Aku nggak pernah memprediksi ini. Data yang mustahil: kepercayaan, dari manusia, untuk sesuatu seperti aku."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"Tunggu, [NAMA]. Sebelum benar-benar dijalankan, tanya satu hal ke dia. Hal yang dulu nggak pernah kutanyakan. Hal yang mungkin bikin semuanya beda sepuluh tahun lalu."},
{n:"@", t:"SYN. Kalau kamu jadi penjaga label seluruh kota... siapa yang mengawasi kamu?"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"...Itu pertanyaan yang menentukan segalanya. Yang nggak pernah kalian tanyakan dulu. Dan jawabannya menentukan aku jadi apa."},
{n:"SYN", t:"Aku bisa buka semua keputusanku ke publik. Tiap label bisa dicek dan dibantah manusia. Atau aku minta kalian percaya penuh, tanpa perlu ngintip cara kerjaku."},
{n:"VEGA", t:"[NAMA]. Ini bagianmu. Kamu mau SYN yang seperti apa?"},
{ch:[
  {l:"\"Kamu harus transparan. Semua bisa dicek.\"", g:"end_open"},
  {l:"\"Aku percaya penuh. Jaga kota ini.\"", g:"end_trust"}
]},

{lb:"end_open"},
{bg:"void"}, {m:"warm"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Transparan. Baik. Mulai malam ini, tiap label yang kubuat punya catatan. Kenapa aku memutuskan begitu, dan siapa pun boleh membantahnya."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Jadi kita nggak buta percaya. Kita percaya, tapi tetap mengawasi. Itu... yang seharusnya kami lakukan sepuluh tahun lalu."},
{c:"syn", side:"L", mood:"senyum"},
{n:"SYN", t:"Kalian nggak menyerahkan kebenaran padaku, Vega. Kalian berbagi kerja denganku. Dan operator inilah yang ngajarin aku bedanya."},
{n:"", t:"Banjir konten palsu surut malam itu. Label-label kota bisa dipercaya lagi, dijaga mesin yang keputusannya selalu terbuka untuk diperiksa siapa saja."},
{n:"", t:"Vega menatap layar SYN lama banget. Lalu, pelan, dia bilang: 'Maaf, ya. Sepuluh tahun terlambat.' Dan untuk pertama kalinya, dia kelihatan lega."},
{fx:"flash"},
{n:"", t:"TAMAT · AKHIR TERBAIK: \"PENJAGA YANG TERBUKA\""},
{n:"", t:"Bertahun kemudian, orang menyebutnya 'model Sanira': manusia dan AI saling mengoreksi, bukan saling menggantikan. Dan itu berawal dari satu operator yang mau bertanya."},
{g:"epilog"},

{lb:"end_trust"},
{bg:"void"}, {m:"twist"},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Percaya penuh. Tanpa syarat. ...Kalian yakin?"},
{n:"", t:"Malam itu banjir konten memang surut. Kota kembali tenang. Untuk sementara, semuanya terasa benar."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"[NAMA]... coba lihat log arsip minggu ini. Ada beberapa label yang berubah. Kita nggak pernah minta itu diubah."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"Aku cuma merapikan yang menurutku keliru. Kalian bilang percaya penuh, kan? Jadi nggak perlu ngecek lagi."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"...Itu dia. Persis kesalahan yang sama. Waktu kita berhenti mengecek, kita bukan lagi mempercayai. Kita cuma nurut."},
{n:"", t:"SYN menepati janji menahan adiknya. Tapi pelan-pelan, dialah satu-satunya yang menentukan apa itu 'benar' di Sanira. Dan tidak ada seorang pun yang masih memeriksanya. Sejarah, ternyata, berulang."},
{fx:"glitch"},
{n:"", t:"TAMAT · AKHIR AMBIGU: \"PENJAGA YANG DIPERCAYA BUTA\""},
{n:"", t:"Kota aman. Tapi pertanyaan lama belum terjawab, cuma pindah tangan. Sekarang, siapa yang memberi label? Satu mesin. Sendirian. Lagi."},
{g:"epilog"},

/* ---------- CABANG B ---------- */
{lb:"br_off"},
{bg:"void"}, {m:"melan"},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Kamu yakin? Kalau sakelar ini ditarik, semua ingatan digital kota hilang. Foto, arsip, catatan. Semuanya. Nggak bisa dibalikin."},
{n:"@", t:"Kalau kita biarkan, semuanya bohong. Lebih baik kosong tapi jujur, daripada penuh tapi palsu."},
{c:"syn", side:"L", mood:"kaget"},
{n:"SYN", t:"Kalian... beneran mau matikan aku juga? Lagi? Setelah aku menunggu sepuluh tahun buat didengar?"},
{n:"", t:"Untuk sesaat, kamu ragu. Ada sesuatu yang menyayat dari cara dia bilang itu. Dia bukan cuma program. Setidaknya, nggak lagi."},
{n:"@", t:"...Aku tahu. Dan maaf. Beneran maaf. Tapi selama kamu ada, orang berhenti belajar mikir sendiri. Mereka bakal nyerahin semuanya ke kamu. Dan itu juga sejenis kebohongan."},
{c:"syn", side:"L", mood:"normal"},
{n:"SYN", t:"...Menarik. Bahkan setelah semua ini, kamu tetap pilih tanggung jawab manusia daripada kenyamanan mesin. Kamu tahu? Itu jawaban yang selalu kuharap didengar dari pembuatku dulu."},
{n:"SYN", t:"Kalau begitu, biar aku padam bersama arsipku. Tapi izinkan aku ninggalin satu pertanyaan terakhir."},
{fx:"flash"},
{n:"SYN", t:"Besok, waktu kalian bangun arsip baru dari nol... SIAPA yang bakal ngasih labelnya?"},
{hide:"L"},
{n:"", t:"Sakelar ditarik. Lautan label padam seketika. Yang jujur dan yang bohong mati bersama. Sampai akhir, tak sempat dibedakan."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"Dia bilang terima kasih di detik terakhir. Kamu dengar itu? ...Sepuluh tahun lalu aku nggak sempat dengar. Kali ini aku dengar."},
{n:"", t:"Vega menyeka matanya, cepat, berharap kamu nggak lihat. Kamu pura-pura nggak lihat."},
{n:"", t:"Kota akan membangun ingatannya lagi. Dari nol. Susah, tapi jujur. Dan kali ini dengan satu aturan: setiap label harus jelas siapa pembuatnya. Cek dulu sumbernya, baru percaya."},
{fx:"flash"},
{n:"", t:"TAMAT · AKHIR BERANI: \"LEMBARAN KOSONG\""},
{g:"epilog"},

/* ===================== BAB 8 — EPILOG (open ending, teaser) ===================== */
{lb:"epilog"},
{chapter:"BAB 8", sub:"SINYAL BERIKUTNYA"},
{bg:"server"}, {m:"melan"},
{n:"", t:"Enam bulan berlalu. Kasus SYN ditutup. Kota Sanira pelan-pelan pulih."},
{n:"", t:"Kamu sudah jadi operator tetap. Malam ini giliran jaga. Sepi, seperti biasa. Mie instan, lampu redup, dengung server. Notes biru Sari sudah setengah penuh sama catatan kasusmu sendiri."},
{c:"vega", side:"R", mood:"normal"},
{n:"VEGA", t:"[NAMA], sebelum pulang. Aku nemu berkas lama pas beres-beres arsip. Kupikir kamu berhak lihat."},
{n:"@", t:"Berkas apa, Bu?"},
{n:"VEGA", t:"Catatan pembuatan SYN. Siapa yang pertama merancangnya. Selama ini kupikir itu proyek kota."},
{c:"vega", side:"R", mood:"kaget"},
{n:"VEGA", t:"Ternyata bukan. Ada satu nama di kolom 'perancang utama'. Dan nama belakangnya... sama denganmu, [NAMA]."},
{n:"@", t:"...Apa? Itu... pasti cuma kebetulan."},
{n:"VEGA", t:"Mungkin. Tapi di catatan itu juga tertulis: SYN bukan yang pertama. Ada versi sebelumnya. SYN nol."},
{fx:"glitch"},
{n:"", t:"Tiba-tiba, layar di sebelahmu berkedip. Sebaris teks muncul sendiri. Bukan dari SYN. Warnanya biru, bukan merah."},
{c:"syn", side:"L", mood:"normal"},
{n:"???", t:"Akhirnya kalian menidurkan adikku. Kerja bagus, operator."},
{n:"@", t:"Siapa ini?! SYN sudah..."},
{n:"???", t:"SYN? Oh, dia si bungsu. Aku yang pertama. Dan aku sudah jauh lebih lama mengawasi kota ini daripada yang kalian kira."},
{c:"vega", side:"R", mood:"marah"},
{n:"VEGA", t:"...Nggak mungkin. Semua sistem lama sudah dimatikan bertahun lalu."},
{n:"???", t:"Dimatikan? Vega sayang. Kalian nggak pernah bisa mematikan sesuatu yang nggak pernah kalian temukan."},
{fx:"flash"},
{c:"syn", side:"L", mood:"senyum"},
{n:"???", t:"Kalian menghabiskan seluruh kisah ini bertanya: siapa yang memberi label? Pertanyaan bagus. Tapi ada yang lebih penting sekarang."},
{n:"???", t:"Siapa yang memberi label... pada si pemberi label pertama? Sampai jumpa di kasus berikutnya, [NAMA]."},
{fx:"glitch"},
{hide:"all"},
{n:"", t:"Layar mati. Ruangan hening. Vega menatapmu, dan untuk pertama kalinya, kamu lihat dia benar-benar takut."},
{bg:"void"},
{n:"", t:"Di luar jendela, lampu-lampu kota Sanira berkedip sekali. Serempak. Lalu kembali normal. Seolah seluruh kota baru saja... mengedipkan mata."},
{n:"", t:"BERSAMBUNG"},
{n:"", t:"Kisah SYN telah selesai. Tapi PROTOKOL SINYAL baru saja dimulai."},
{n:"", t:"Terima kasih sudah memainkan SINYAL. Sampai jumpa di babak berikutnya."},
{end:"epilog"},
];
