/* ================================================================
   SINYAL — PAKET SOAL TAMBAHAN (Paket 11–20)
   ----------------------------------------------------------------
   CARA KERJA: file ini TIDAK mendeklarasikan ulang PAKET. Ia hanya
   MENAMBAHKAN (push) paket baru ke array PAKET yang sudah dibuat di
   js/paket.js. Jadi paket.js aman, tidak perlu diubah.

   URUTAN MUAT (WAJIB): di index.html letakkan tag <script> file ini
   SETELAH paket.js dan SEBELUM story.js, contoh:
       <script src="js/paket.js"></script>
       <script src="js/paket_ekstra.js"></script>   <-- di sini
       ...
       <script src="js/story.js"></script>
   Kenapa? story.js membangun kolam soal cerita (VN_POOL) sekali saat
   dimuat. Kalau file ini dimuat setelah story.js, mode Tanding/Online
   tetap dapat paket baru (mereka baca PAKET saat dipakai), tapi mode
   Story tidak. Menaruhnya sebelum story.js membuat SEMUA mode dapat.

   ID: paket baru memakai id 11–20 supaya tidak bentrok dengan id 1–10
   (online.js mencari paket lewat PAKET.find(x=>x.id===...)).

   SKEMA SOAL (sama persis dengan paket.js):
     { isAI, level(1=dasar/2=sulit), cue, text, explain, trap? }
     isAI = KUNCI JAWABAN: true = buatan AI, false = karya manusia.

   FIELD BARU (opsional): theme. Dipakai story.js untuk mengenali paket
   bertema tertentu ("berita", "chat", "akademik") agar ikut mengisi bab
   cerita yang relevan. Paket tanpa theme tetap otomatis mengisi kolam
   berdasarkan level & flag trap (pemanasan, zona kabut, gerbang final).

   CATATAN GAYA: tanda hubung em (—) di dalam contoh berlabel AI sengaja
   dipertahankan karena itu memang salah satu "sidik jari" AI yang sedang
   diajarkan. Teks berlabel manusia & semua penjelasan tetap bebas em dash.

   CATATAN INTEGRITAS (sama seperti paket.js): teks berlabel "manusia" di
   sini adalah contoh gaya buatan pengembang untuk latihan. Untuk laporan,
   ganti dengan kutipan asli bersumber + atribusi.
   ================================================================ */
const PAKET_EKSTRA = [

{ id:11, nama:"PAKET 11 — DUNIA KERJA & LAMARAN", soal:[
  { isAI:true, level:1, cue:"Cover letter template",
    text:"Dengan penuh antusias, saya mengajukan diri untuk posisi ini. Saya yakin bahwa keterampilan, pengalaman, dan dedikasi saya akan memberikan kontribusi yang berharga bagi perusahaan Anda yang terkemuka.",
    explain:"Pola tiga hal sejajar (keterampilan-pengalaman-dedikasi) + pujian kosong 'perusahaan Anda yang terkemuka' tanpa menyebut nama perusahaan. Surat lamaran hasil generate klasik." },
  { isAI:false, level:1, cue:"Alasan pindah kerja apa adanya",
    text:"jujur aku resign bukan karena gaji. lebih ke atasan yang tiap jumat sore ngasih revisi terus bilang 'santai weekend'. tiga tahun begitu terus, capek",
    explain:"Keluhan spesifik dan sedikit menahan emosi (jumat sore, 'santai weekend') yang cuma lahir dari pengalaman kerja nyata." },
  { isAI:true, level:1, cue:"Deskripsi lowongan bombastis",
    text:"Kami mencari kandidat yang proaktif, adaptif, dan berorientasi pada hasil untuk bergabung dalam tim kami yang dinamis dan penuh semangat dalam menghadapi lanskap industri yang terus berkembang.",
    explain:"Kata zombi 'lanskap' + 'terus berkembang' + rentetan kata sifat HRD generik. Tidak ada satu pun tugas konkret disebutkan." },
  { isAI:false, level:1, cue:"Update kerjaan ke grup",
    text:"tim, projectnya mundur seminggu ya. klien baru bales tadi pagi, mintanya warna biru diganti jadi 'biru tapi jangan biru banget'. iya aku jg bingung",
    explain:"Absurditas nyata dari klien ('biru tapi jangan biru banget') dan kepasrahan personal. Detail yang mustahil ditebak generator." },
  { isAI:true, level:2, cue:"Feedback manajer kosong",
    text:"Kinerjamu kuartal ini menunjukkan perkembangan yang positif. Teruslah tingkatkan komunikasi, kolaborasi, dan inisiatif agar dapat mencapai potensi maksimal serta memberikan dampak yang lebih signifikan bagi tim.",
    explain:"Evaluasi tanpa satu contoh konkret. Trio komunikasi-kolaborasi-inisiatif + 'potensi maksimal' adalah bahasa penilaian yang bisa ditempel ke siapa saja." },
  { isAI:false, level:2, cue:"Negosiasi gaji riil",
    text:"Untuk angka yang Bapak tawarkan, sebenarnya masih di bawah ekspektasi saya sekitar 1,5 juta. Tapi kalau ada opsi WFH dua hari seminggu, saya bisa pertimbangkan lagi. Bagaimana menurut Bapak?",
    explain:"Angka spesifik (1,5 juta), tawaran alternatif konkret (WFH dua hari), dan giliran bicara yang wajar. Negosiasi manusia yang punya kepentingan nyata." },
  { isAI:true, level:2, cue:"Motivasi kerja puitis",
    text:"Bekerja bukan sekadar mencari nafkah, melainkan sebuah perjalanan untuk menyelami makna dan menemukan versi terbaik dari diri kita. Setiap tantangan adalah peluang yang menanti untuk diungkap.",
    explain:"'Bukan sekadar X melainkan Y' + kata zombi 'menyelami' dan 'diungkap'. Renungan kerja generik tanpa penulis yang terlihat." },
  { isAI:false, level:2, cue:"Serah terima pekerjaan",
    text:"Kalau nanti aku udah nggak di sini: password wifi ada di tempel bawah router, jangan percaya kata mas IT soal printer lantai 2 (bohong, itu nggak akan pernah beres), dan file klien Astra ada di folder 'FINAL FIX FIX beneran'.",
    explain:"Penamaan folder kacau, sarkasme soal printer, pengetahuan orang dalam. Tekstur tempat kerja asli yang tak bisa dipalsukan pola." },
  { isAI:true, level:2, cue:"Email follow-up sopan",
    text:"Menindaklanjuti percakapan kita sebelumnya, saya ingin menegaskan kembali ketertarikan saya. Saya sangat terbuka untuk mendiskusikan lebih lanjut kapan pun waktunya sesuai bagi Anda. Terima kasih atas perhatian dan waktunya.",
    explain:"Email tindak lanjut mulus tanpa satu detail pun soal apa yang dibahas 'sebelumnya'. Kesopanan prosedural yang seragam khas asisten AI." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis rapi profesional",
    text:"Sehubungan dengan hasil wawancara pada 12 Juli, kami menyampaikan bahwa Saudara belum dapat kami terima pada posisi ini. Keputusan didasarkan pada kebutuhan pengalaman minimal 3 tahun di bidang serupa. Kami menyimpan data Saudara untuk kesempatan mendatang.",
    explain:"JEBAKAN. Surat penolakan MANUSIA (HRD): rapi karena genre menuntut rapi. Petunjuk kemanusiaan justru di detail spesifik (tanggal 12 Juli, syarat 3 tahun) yang bukan tempelan kosong." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru curhat kerja",
    text:"hari ini di kantor lumayan berat sih. banyak deadline numpuk 😮‍💨 tapi aku belajar buat lebih menghargai proses dan tetap bersyukur. semangat ya buat kita semua yang lagi berjuang di dunia kerja! 💪",
    explain:"JEBAKAN. AI meniru curhat kerja: keluhan umum, emoji, ditutup penyemangat kolektif. Terlalu rapi arc emosinya, tanpa satu kejadian spesifik pun." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis notulen kaku",
    text:"Notulen rapat 14/07. Hadir: 6 dari 8. Poin 1: budget desain disetujui Rp8jt (Rani). Poin 2: launching diundur ke Agustus (belum fix, tunggu vendor). Action: Dimas kirim brief ke vendor sebelum Kamis. Selesai 15.40.",
    explain:"JEBAKAN sebaliknya: notulen MANUSIA yang memang kaku dan padat. Singkatan lokal, penanggung jawab per poin, jam selesai. Kekakuannya fungsional, bukan mesin." }
]},

{ id:12, nama:"PAKET 12 — TEKNOLOGI & GADGET", soal:[
  { isAI:true, level:1, cue:"Review gadget mulus",
    text:"Ponsel ini menawarkan performa yang luar biasa dengan desain yang elegan dan fitur yang inovatif. Layarnya yang jernih memanjakan mata, sementara baterainya yang tahan lama mendukung aktivitas harian Anda tanpa hambatan.",
    explain:"Rangkaian pujian tanpa satu angka pun: berapa inci, berapa mAh, chipset apa. 'Memanjakan mata', 'tanpa hambatan' adalah bahasa iklan generik." },
  { isAI:false, level:1, cue:"Keluhan teknis spesifik",
    text:"update terbaru malah bikin baterai boros parah. dari 100 ke 60 cuma buka wa sejam. udah clear cache, restart, sama aja. mau balik ke versi lama tapi takut malah brick",
    explain:"Angka penurunan spesifik (100 ke 60), langkah yang sudah dicoba, dan kekhawatiran teknis nyata ('brick'). Frustrasi pengguna asli." },
  { isAI:true, level:1, cue:"Tutorial kaku",
    text:"Untuk mengoptimalkan performa perangkat Anda, ikuti langkah-langkah berikut: bersihkan cache secara berkala, hapus aplikasi yang tidak digunakan, dan pastikan sistem operasi selalu diperbarui ke versi terbaru.",
    explain:"Daftar tips universal (rule of three) tanpa konteks perangkat spesifik. 'Optimalkan performa' adalah frasa jargon yang dipakai berlebihan oleh AI." },
  { isAI:false, level:1, cue:"Reaksi rilis produk",
    text:"HAH harganya naik 3 juta cuma buat nambah satu kamera?? mending duitnya buat DP motor bro. ini mah bukan upgrade, ini perampokan berkedok teknologi",
    explain:"Kemarahan konsumen dengan perbandingan absurd (DP motor) dan istilah bikinan sendiri. Spontanitas dan sudut pandang personal." },
  { isAI:true, level:2, cue:"Artikel tren teknologi",
    text:"Kecerdasan buatan telah merevolusi berbagai aspek kehidupan modern. Dari kesehatan hingga pendidikan, teknologi ini membuka peluang baru yang sebelumnya tak terbayangkan, mengubah cara kita bekerja, belajar, dan berinteraksi.",
    explain:"Klaim besar tanpa contoh konkret, pola tiga sejajar (bekerja-belajar-berinteraksi), 'membuka peluang'. Artikel tren yang bisa ditulis tanpa riset apa pun." },
  { isAI:false, level:2, cue:"Diskusi teknis di forum",
    text:"masalahnya bukan di RAM-nya bang. coba cek thermal throttling pas main 30 menit, punyaku drop dari 2,8GHz ke 1,9GHz gara2 pasta prosesornya udah kering. repaste dulu baru komplain",
    explain:"Diagnosis presisi dengan angka clock speed dan penyebab fisik (pasta kering). Pengetahuan teknis berbasis pengalaman langsung." },
  { isAI:true, level:2, cue:"Penjelasan konsep bertele",
    text:"Blockchain adalah teknologi buku besar terdistribusi yang memungkinkan pencatatan transaksi secara aman, transparan, dan tidak dapat diubah, sehingga menciptakan kepercayaan tanpa perlu perantara pihak ketiga yang terpusat.",
    explain:"Definisi textbook dengan trio 'aman-transparan-tidak dapat diubah'. Benar secara teknis tapi kompilasi mekanis tanpa sudut pandang." },
  { isAI:false, level:2, cue:"Kesan jujur setelah beli",
    text:"udah sebulan pakai. yang bagus: kameranya emang oke buat foto anak. yang nyebelin: speakernya di bawah, jadi ketutup tangan tiap main game landscape. designernya kayaknya nggak pernah main game",
    explain:"Penilaian berimbang dengan use case spesifik (foto anak), cacat konkret (posisi speaker), dan sindiran personal. Ulasan pemakai sungguhan." },
  { isAI:true, level:2, cue:"Prediksi masa depan generik",
    text:"Di masa depan, teknologi akan semakin terintegrasi dalam kehidupan sehari-hari kita. Rumah pintar, kendaraan otonom, dan asisten virtual akan menjadi hal yang lumrah, mengubah lanskap kehidupan manusia secara fundamental.",
    explain:"Prediksi aman dengan kata zombi 'lanskap' dan 'fundamental'. Tiga contoh futuristik standar tanpa nuansa atau keraguan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis spesifikasi rapi",
    text:"Spesifikasi unit bekas: Snapdragon 888, RAM 8/256, baterai 4500mAh (kesehatan 89%), layar mulus tanpa dead pixel, minus lecet halus di frame kanan bawah. Nego tipis buat yang serius, COD area Depok.",
    explain:"JEBAKAN. Iklan jual MANUSIA yang rapi karena harus meyakinkan pembeli. Kejujuran soal cacat (lecet, baterai 89%) dan lokasi COD adalah tanda penjual nyata." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru review kecewa",
    text:"kecewa banget sama produk ini. udah nunggu lama, ekspektasi tinggi, ternyata biasa aja. mungkin ekspektasiku yang ketinggian ya. tapi tetep aja rugi rasanya. semoga next gen lebih baik.",
    explain:"JEBAKAN. AI meniru review kecewa: emosi umum tanpa detail produk spesifik, lalu menyalahkan diri sendiri secara sopan. Terlalu mulus untuk orang yang benar-benar kesal." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis penjelasan runtut",
    text:"Singkatnya: kalau cuma buat sosmed dan chat, chip lama sudah lebih dari cukup. Beda harga 2 jutanya lebih baik dialihkan ke penyimpanan yang lebih besar. Upgrade chip baru relevan hanya kalau kamu editing video 4K rutin.",
    explain:"JEBAKAN sebaliknya: penjelasan MANUSIA yang runtut dan rapi karena memang paham. Petunjuknya: rekomendasi bersyarat spesifik (editing 4K rutin), bukan pujian kosong." }
]},

{ id:13, nama:"PAKET 13 — BERITA & JURNALISME LANJUTAN", theme:"berita", soal:[
  { isAI:true, level:1, cue:"Lead tanpa 5W1H",
    text:"Sektor pariwisata menunjukkan tren pemulihan yang menggembirakan dalam beberapa waktu terakhir. Berbagai pihak menyambut positif perkembangan ini yang diharapkan dapat mendorong pertumbuhan ekonomi secara berkelanjutan.",
    explain:"'Beberapa waktu terakhir', 'berbagai pihak', 'diharapkan dapat' semuanya kabur. Berita tanpa siapa, kapan, di mana, atau angka. Ciri lead generate." },
  { isAI:false, level:1, cue:"Lead berita berdata",
    text:"Dinas Perhubungan mencatat 1.240 pelanggaran ganjil-genap pada H+2 lebaran, naik 18% dari tahun lalu. Mayoritas terjadi di ruas tol Cikampek KM 47 antara pukul 05.00 dan 07.00.",
    explain:"Sumber jelas (Dishub), angka spesifik (1.240, 18%, KM 47), waktu presisi. Lead yang menjawab pertanyaan wartawan sungguhan." },
  { isAI:true, level:1, cue:"Kutipan narasumber template",
    text:"\"Kami berkomitmen untuk terus meningkatkan pelayanan demi kepuasan masyarakat,\" ujar seorang pejabat terkait. Ia menambahkan bahwa berbagai upaya akan dilakukan untuk memastikan program berjalan optimal.",
    explain:"'Seorang pejabat terkait' tanpa nama, kutipan klise 'berkomitmen meningkatkan pelayanan'. Narasumber hantu yang tidak pernah ada." },
  { isAI:false, level:1, cue:"Kutipan hidup",
    text:"\"Ya mau gimana lagi, mas. Sudah tiga hari nggak jualan. Gerobak saya diangkut, katanya nunggu sidang. Anak saya nanya kok bapak nggak bawa dagangan,\" kata Warno sambil menunjuk lapaknya yang kosong.",
    explain:"Nama konkret (Warno), detail yang menyayat (anak bertanya), gestur (menunjuk lapak). Kutipan hasil liputan lapangan nyata." },
  { isAI:true, level:2, cue:"Analisis politik netral",
    text:"Dinamika politik menjelang pemilu semakin memanas. Para pengamat menilai bahwa peta koalisi masih cair dan dapat berubah sewaktu-waktu, tergantung pada berbagai faktor yang saling memengaruhi dalam konstelasi politik nasional.",
    explain:"'Semakin memanas', 'masih cair', 'berbagai faktor', 'konstelasi'. Analisis yang tidak menyatakan apa pun secara pasti. Kekaburan aman khas AI." },
  { isAI:false, level:2, cue:"Investigasi dengan temuan",
    text:"Dari 14 dokumen pengadaan yang kami telusuri, tujuh menggunakan vendor dengan alamat yang sama: sebuah ruko kosong di Jalan Melati. Pemiliknya, menurut akta, adalah adik ipar kepala dinas.",
    explain:"Angka spesifik (14, tujuh), temuan janggal konkret (ruko kosong, alamat sama), relasi terungkap. Kerja investigasi yang tidak bisa dikarang mesin tanpa data." },
  { isAI:true, level:2, cue:"Penutup berita menggantung",
    text:"Kasus ini masih terus bergulir dan menjadi perhatian publik. Penting untuk diingat bahwa masyarakat menantikan transparansi serta penyelesaian yang adil demi terciptanya kepercayaan terhadap institusi terkait.",
    explain:"Penutup 'penting untuk diingat bahwa' yang khas AI + 'menjadi perhatian publik'. Kalimat pengisi yang tidak menambah informasi apa pun." },
  { isAI:false, level:2, cue:"Koreksi redaksi",
    text:"RALAT: Pada artikel 11 Juli kami menulis korban berjumlah 12 orang. Yang benar 21 orang, sesuai data RS Bhayangkara pukul 20.00. Kesalahan pengetikan angka ini murni kelalaian redaksi. Kami mohon maaf.",
    explain:"Pengakuan kesalahan spesifik (12 vs 21, tanggal, sumber koreksi) dan permintaan maaf. Genre yang menandakan pertanggungjawaban manusia." },
  { isAI:true, level:2, cue:"Berita ekonomi hampa",
    text:"Nilai tukar rupiah mengalami fluktuasi di tengah ketidakpastian global. Para analis memperkirakan bahwa kondisi ini akan terus dipengaruhi oleh sentimen pasar dan kebijakan moneter, sehingga pelaku usaha diimbau tetap waspada.",
    explain:"'Fluktuasi', 'ketidakpastian global', 'sentimen pasar' tanpa satu angka kurs pun. Berita ekonomi yang isinya nol informasi." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — siaran pers manusia yang kaku",
    text:"Melalui siaran pers ini, PT Sinar Abadi menyampaikan bahwa produk batch LX-2231 ditarik dari peredaran secara sukarela menyusul temuan cacat pada segel tutup. Konsumen dapat menukar produk di gerai resmi dengan menunjukkan struk.",
    explain:"JEBAKAN. Siaran pers MANUSIA (humas): kaku karena genre korporat. Tanda kemanusiaan di detail teknis spesifik (batch LX-2231, cacat segel) dan prosedur konkret." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru berita hoaks meyakinkan",
    text:"Warga dihebohkan dengan penemuan sumur tua di Desa Sukamaju yang konon mengeluarkan suara aneh setiap malam Jumat. Beberapa warga mengaku melihat cahaya misterius. Pihak berwenang belum memberikan keterangan resmi.",
    explain:"JEBAKAN. Berita hoaks buatan AI: 'konon', 'beberapa warga mengaku', 'belum ada keterangan resmi' membuat klaim tanpa bisa diverifikasi. Struktur clickbait yang mulus." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — feature manusia bergaya sastra",
    text:"Pagi belum benar-benar terang ketika Bu Inah sudah mengaduk dodol di kuali raksasa itu. Empat jam, tanpa berhenti. Tangannya yang keriput bergerak seperti sudah hafal luar kepala, warisan gerakan dari ibunya, dari nenek ibunya.",
    explain:"JEBAKAN sebaliknya: feature jurnalistik MANUSIA yang puitis. Gaya sastrawi sering dituduh AI, padahal detail sensorik (kuali raksasa, empat jam) menandakan pengamatan langsung." }
]},

{ id:14, nama:"PAKET 14 — KULINER & RESEP", soal:[
  { isAI:true, level:1, cue:"Deskripsi menu restoran",
    text:"Hidangan ini memadukan cita rasa autentik dengan sentuhan modern yang memanjakan lidah. Setiap suapan menghadirkan harmoni rasa yang sempurna, menciptakan pengalaman kuliner yang tak terlupakan bagi para penikmatnya.",
    explain:"'Memanjakan lidah', 'harmoni rasa yang sempurna', 'tak terlupakan'. Deskripsi tanpa menyebut satu bahan atau rasa spesifik. Menu hasil generate." },
  { isAI:false, level:1, cue:"Review makanan jujur",
    text:"seblaknya enak sih pedesnya nampol, tapi ceker nya masih ada bulu-bulu halusnya gitu. jadi agak eneg pas ngunyah. sambel nya juara tapi, mau balik lagi cuma minta ceker nya dibersihin bener",
    explain:"Detail yang tidak enak dibahas (bulu ceker), penilaian berlapis (enak tapi eneg), keinginan spesifik. Ulasan pemakan sungguhan." },
  { isAI:true, level:1, cue:"Tips masak generik",
    text:"Untuk menghasilkan masakan yang lezat, gunakan bahan-bahan segar dan berkualitas. Jangan lupa menyeimbangkan bumbu serta memasak dengan penuh cinta agar hasilnya maksimal dan disukai seluruh keluarga.",
    explain:"'Bahan segar berkualitas', 'penuh cinta', 'hasil maksimal'. Nasihat masak yang bisa ditempel ke resep apa pun. Tanpa takaran atau teknik." },
  { isAI:false, level:1, cue:"Resep turun-temurun",
    text:"rahasia rendang mama: apinya kecil terus, aduk pakai centong kayu jangan besi biar nggak amis, dan sabar 4 jam. mama selalu bilang 'rendang buru-buru itu cuma daging bumbu, bukan rendang'",
    explain:"Teknik spesifik (centong kayu, api kecil 4 jam), kutipan personal ibu. Pengetahuan dapur yang diwariskan, bukan dirangkai mesin." },
  { isAI:true, level:2, cue:"Artikel food blog",
    text:"Kopi bukan sekadar minuman, melainkan sebuah ritual yang menemani perjalanan hari kita. Dari biji yang disangrai dengan cermat hingga tetesan terakhir, setiap cangkir menyimpan cerita dan kehangatan yang menenangkan jiwa.",
    explain:"'Bukan sekadar X melainkan Y' + 'menyimpan cerita' + 'menenangkan jiwa'. Prosa food blog puitis yang generik, tanpa asal biji atau metode spesifik." },
  { isAI:false, level:2, cue:"Kegagalan masak",
    text:"percobaan bikin macaron ke-5 dan masih retak semua. udah ikutin suhu 150 derajat, resting 40 menit, tapi tetep. kayaknya oven rumahku emang panasnya nggak rata sebelah kiri. nyerah dulu, mahal almond flour nya",
    explain:"Angka teknis (150 derajat, 40 menit, percobaan ke-5), diagnosis realistis (oven tidak rata), kepasrahan berbiaya. Perjuangan dapur nyata." },
  { isAI:true, level:2, cue:"Rekomendasi tempat makan",
    text:"Kota ini menawarkan beragam pilihan kuliner yang menggugah selera untuk setiap kalangan. Mulai dari jajanan kaki lima yang autentik hingga restoran mewah yang elegan, semua tersedia untuk memuaskan hasrat kuliner Anda.",
    explain:"'Menggugah selera', 'setiap kalangan', 'memuaskan hasrat'. Rekomendasi tanpa nama satu tempat pun. Bahasa katalog wisata generate." },
  { isAI:false, level:2, cue:"Instruksi resep spesifik",
    text:"Kalau minyaknya belum cukup panas, tahu bakal nyerep minyak dan jadi berat. Tes pakai ujung tusuk gigi: kalau langsung muncul gelembung rapat, baru masukin. Api sedang, jangan sering dibalik, biar kulitnya set dulu.",
    explain:"Teknik konkret (tes tusuk gigi, gelembung rapat) dan penjelasan sebab-akibat. Instruksi dari orang yang benar-benar pernah menggoreng." },
  { isAI:true, level:2, cue:"Manfaat makanan listicle",
    text:"Mengonsumsi sayuran hijau memberikan banyak manfaat bagi kesehatan tubuh. Selain kaya akan vitamin dan mineral, sayuran hijau juga membantu melancarkan pencernaan, meningkatkan imunitas, serta menjaga kesehatan kulit.",
    explain:"Manfaat berderet (rule of three) dengan bahasa artikel kesehatan template. Benar tapi tanpa sumber, tanpa nuansa. Konten SEO generate." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis resep rapi terstruktur",
    text:"Bahan: 250g tepung, 2 butir telur, 180ml susu, sejumput garam. Cara: kocok telur, masukkan susu, ayak tepung bertahap sambil aduk searah. Diamkan adonan 30 menit sebelum dituang. Kunci: jangan overmix, gumpalan kecil justru bagus.",
    explain:"JEBAKAN. Resep MANUSIA yang rapi dan terstruktur karena memang harus presisi. Petunjuknya: takaran ganjil (180ml) dan tips kontra-intuitif dari pengalaman ('gumpalan justru bagus')." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru review antusias",
    text:"OMG ini enak banget sumpah!! teksturnya lembut, rasanya pas, harganya juga worth it. pokoknya wajib coba deh kalau ke sini. dijamin nggak nyesel! 10/10 bakalan balik lagi pasti!!",
    explain:"JEBAKAN. AI meniru review antusias: seru tapi kosong. 'Teksturnya lembut, rasanya pas' terlalu umum, tidak ada nama menu atau detail yang cuma diketahui orang yang benar-benar makan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis deskripsi menu apik",
    text:"Nasi kucing kami: porsi kecil, tapi sambal teri kacangnya kami ulek pagi hari, bukan semalam. Dibungkus daun pisang asli biar wangi. Bukan buat kenyang, tapi buat teman ngobrol sampai pagi di angkringan.",
    explain:"JEBAKAN sebaliknya: deskripsi menu MANUSIA yang apik dan sedikit puitis. Detail proses (diulek pagi, bukan semalam) dan fungsi sosial (teman ngobrol) menandakan pemilik warung asli." }
]},

{ id:15, nama:"PAKET 15 — KESEHATAN & GAYA HIDUP", soal:[
  { isAI:true, level:1, cue:"Artikel kesehatan generik",
    text:"Menjaga kesehatan tubuh sangatlah penting di era modern ini. Dengan menerapkan pola hidup sehat, seperti makan bergizi, olahraga teratur, dan istirahat cukup, kita dapat meningkatkan kualitas hidup secara menyeluruh.",
    explain:"Trio makan-olahraga-istirahat + 'kualitas hidup secara menyeluruh'. Nasihat kesehatan yang benar tapi hampa, bisa ditempel di mana saja." },
  { isAI:false, level:1, cue:"Pengalaman sakit personal",
    text:"vertigo kambuh lagi pagi ini. bangun tidur langsung muter kayak abis naik gasing. sampai harus rambatan ke kamar mandi. yang begini nih orang sering kira cuma pusing biasa, padahal rasanya dunia beneran muter",
    explain:"Deskripsi sensasi yang spesifik dan personal (naik gasing, rambatan), plus kekesalan pada kesalahpahaman umum. Pengalaman tubuh nyata." },
  { isAI:true, level:1, cue:"Motivasi olahraga",
    text:"Setiap langkah kecil menuju hidup sehat adalah investasi berharga untuk masa depan Anda. Jangan menyerah, teruslah bergerak, dan percayalah bahwa tubuh yang sehat adalah kunci menuju kebahagiaan sejati.",
    explain:"'Investasi berharga', 'kunci menuju kebahagiaan sejati'. Motivasi generik tanpa saran konkret. Caption gym yang bisa digenerate massal." },
  { isAI:false, level:1, cue:"Curhat diet realistis",
    text:"day 3 diet dan aku udah hampir bunuh orang gara-gara dia makan gorengan di depanku. katanya sih minggu pertama emang paling susah. semoga bener, soalnya sekarang aku ngiler liat iklan mie doang",
    explain:"Hiperbola lucu (hampir bunuh orang), godaan spesifik (gorengan, iklan mie), keraguan. Perjuangan diet dengan humor manusia yang lelah." },
  { isAI:true, level:2, cue:"Penjelasan medis aman",
    text:"Stres dapat berdampak signifikan terhadap kesehatan fisik dan mental. Oleh karena itu, penting untuk mengelola stres dengan baik melalui teknik relaksasi, dukungan sosial, dan gaya hidup seimbang demi kesejahteraan optimal.",
    explain:"'Berdampak signifikan', trio teknik-dukungan-gaya hidup, 'kesejahteraan optimal'. Penjelasan aman tanpa mekanisme atau contoh spesifik." },
  { isAI:false, level:2, cue:"Cerita pemulihan spesifik",
    text:"6 bulan pasca operasi lutut. fisioterapisku galak banget tapi berkat dia sekarang udah bisa naik tangga tanpa pegangan. masih ngilu kalau hujan sih. dokter bilang wajar, besi di dalam lututku 'ngerasain' cuaca katanya",
    explain:"Kronologi spesifik (6 bulan), detail unik (besi merasakan cuaca), relasi personal (fisioterapis galak). Kisah pemulihan yang dijalani sungguhan." },
  { isAI:true, level:2, cue:"Tips tidur listicle",
    text:"Tidur yang berkualitas merupakan fondasi kesehatan yang sering terabaikan. Untuk memperbaikinya, hindari layar sebelum tidur, ciptakan lingkungan yang nyaman, dan pertahankan jadwal tidur yang konsisten setiap harinya.",
    explain:"'Fondasi kesehatan', tiga tips standar. Artikel wellness template. Bahasanya rapi seragam tanpa satu pun pengalaman penulis." },
  { isAI:false, level:2, cue:"Keputusasaan lembut",
    text:"udah coba ke 4 dokter beda buat keluhan yang sama. yang satu bilang asam lambung, yang lain bilang cemas, yang lain nyuruh tes darah lagi. capek nya bukan cuma badan, tapi harus jelasin ulang dari awal terus tiap ganti dokter",
    explain:"Frustrasi berlapis yang spesifik (4 dokter, diagnosis beda), kelelahan yang bukan cuma fisik. Nuansa emosional yang tak dihasilkan generator netral." },
  { isAI:true, level:2, cue:"Ajakan hidup sehat",
    text:"Mari mulai perjalanan menuju versi terbaik dari diri kita! Dengan komitmen, konsistensi, dan disiplin, kita dapat meraih tubuh yang ideal dan pikiran yang jernih. Ingat, perubahan dimulai dari langkah pertama hari ini.",
    explain:"'Versi terbaik dari diri kita', trio komitmen-konsistensi-disiplin, 'langkah pertama'. Ajakan penuh klise motivasi tanpa isi praktis." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis edukasi kesehatan rapi",
    text:"Perlu dipahami, antibiotik tidak bekerja pada infeksi virus seperti flu biasa. Menghabiskan antibiotik untuk keluhan yang salah justru memicu resistensi. Konsultasikan dulu, karena batuk lebih dari 2 minggu punya banyak kemungkinan penyebab.",
    explain:"JEBAKAN. Edukasi MANUSIA (mungkin nakes) yang rapi karena memang paham. Petunjuknya: klaim spesifik dan benar (resistensi, batas 2 minggu), bukan generalisasi kosong." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru testimoni personal",
    text:"aku dulu sempat insecure sama berat badanku. tapi setelah mulai journaling dan lebih mencintai diri sendiri, aku sadar bahwa kesehatan mental sama pentingnya. sekarang aku belajar bersyukur setiap hari. kalian juga bisa kok!",
    explain:"JEBAKAN. AI meniru testimoni: arc 'dulu insecure, sekarang bersyukur' yang terlalu rapi. Tidak ada detail spesifik, ditutup ajakan kolektif. Emosi template." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis renungan tenang",
    text:"Ada hari-hari ketika bangun dari kasur saja terasa seperti mendaki. Aku belajar berhenti memaksakan produktif. Kadang mandi dan makan satu piring penuh sudah cukup jadi pencapaian. Pelan-pelan tidak apa-apa.",
    explain:"JEBAKAN sebaliknya: renungan MANUSIA soal kesehatan mental. Gaya reflektif sering dituduh AI, tapi metafora spesifik (bangun terasa mendaki) dan definisi pencapaian yang jujur menandakan pengalaman nyata." }
]},

{ id:16, nama:"PAKET 16 — PERCAKAPAN & CHAT LANJUTAN", theme:"chat", soal:[
  { isAI:false, level:1, cue:"Chat pasangan receh",
    text:"yaudah kamu tidur duluan aja. iya aku gapapa. (10 menit kemudian) eh belum tidur kan? aku laper. jajan yuk. yang bakso depan komplek itu loh yang tadi kamu bilang mahal",
    explain:"Perubahan pikiran yang khas (gapapa lalu ngajak jajan), referensi obrolan sebelumnya. Dinamika pasangan asli yang mustahil ditebak mesin." },
  { isAI:true, level:1, cue:"Bot layanan pelanggan",
    text:"Halo Kak! Terima kasih telah menghubungi layanan kami 😊 Untuk membantu proses lebih lanjut, mohon Kakak berkenan menyertakan nomor pesanan serta kendala yang dialami. Kami siap membantu menyelesaikannya. Terima kasih! 🙏",
    explain:"Struktur bot CS: sapaan 'Kak', permintaan data terstruktur, penutup 'siap membantu'. Keramahan prosedural dan seragam yang tak pernah kesal." },
  { isAI:false, level:1, cue:"Grup alumni ricuh",
    text:"woy yang minjem proyektor angkatan 2019 balikin dong udah 2 tahun. iya kamu Bud, jangan pura2 gabaca. kabinet aja udah ganti 3x proyektor belum balik jg",
    explain:"Tuduhan spesifik dengan nama (Bud), referensi waktu absurd (2 tahun, ganti kabinet 3x). Konflik grup nyata yang tak bisa dikarang generator." },
  { isAI:true, level:1, cue:"Balasan asisten AI",
    text:"Tentu, saya dengan senang hati membantu Anda! Berikut adalah beberapa saran yang dapat Anda pertimbangkan. Apabila ada hal lain yang ingin ditanyakan, jangan ragu untuk menyampaikannya. Saya siap membantu kapan saja.",
    explain:"'Dengan senang hati', 'jangan ragu', 'siap membantu kapan saja'. Antusiasme prosedural tanpa lelah adalah tanda asisten AI, bukan teman." },
  { isAI:false, level:2, cue:"Minta tolong berjenjang",
    text:"bro bisa titip absen gak besok? sekali ini aja sumpah. gantiannya nanti aku yang jagain hp kamu pas kamu tidur di kelas pak Anwar. deal? jangan lupa duduk deket jendela biar keliatan aku dateng",
    explain:"Barter sosial spesifik (titip absen tukar jaga hp), pengetahuan kelas (Pak Anwar, jendela). Negosiasi pertemanan yang punya sejarah nyata." },
  { isAI:true, level:2, cue:"Chat pura-pura akrab",
    text:"hai! apa kabar? semoga harimu menyenangkan ya. aku cuma mau bilang kamu itu orang yang luar biasa dan pantas mendapat yang terbaik. tetap semangat dan jangan lupa bahagia! kamu berharga kok 💕",
    explain:"Pujian umum tanpa alasan spesifik, ditutup afirmasi generik. Terlalu manis dan sempurna. Teman beneran menyelipkan konteks atau ejekan." },
  { isAI:false, level:2, cue:"Kesalahpahaman chat",
    text:"maksudku bukan gitu. tadi tuh aku bilang 'ya' sambil ngetik hal lain, jadi keliatannya aku setuju padahal aku belum baca lengkap. sori. ini gara2 aku sambil nyetir tadi. telfon aja deh biar clear",
    explain:"Penjelasan miskomunikasi yang berantakan dan spesifik (ngetik sambil nyetir), inisiatif menelepon. Perbaikan hubungan real-time khas manusia." },
  { isAI:true, level:2, cue:"Ucapan selamat template",
    text:"Selamat atas pencapaian yang luar biasa ini! Kerja keras dan dedikasimu akhirnya membuahkan hasil yang membanggakan. Semoga ini menjadi awal dari kesuksesan-kesuksesan berikutnya. Kamu memang pantas mendapatkannya!",
    explain:"'Pencapaian luar biasa', 'kerja keras dan dedikasi', 'awal kesuksesan'. Ucapan yang bisa dikirim ke siapa saja untuk apa saja. Nol personalisasi." },
  { isAI:false, level:2, cue:"Chat kondangan realistis",
    text:"eh yang dateng kondangan sabtu pake baju warna apa? jangan sampe samaan lg kaya kemaren malu bgt kita berdua item semua kaya mau melayat. aku udah booking kebaya ijo, kamu jangan ijo ya awas",
    explain:"Referensi kejadian memalukan spesifik (item semua kayak melayat), koordinasi warna dengan ancaman bercanda. Percakapan yang punya masa lalu bersama." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru chat singkat",
    text:"iya bener bgt sih. wkwk sama. eh btw udah makan? jgn lupa istirahat ya, jaga kesehatan. nanti kabarin kalau ada apa2. semangat terus pokoknya!",
    explain:"JEBAKAN. AI meniru chat santai teman: singkatan, 'wkwk', perhatian umum. Petunjuk halus: terlalu kooperatif, tanpa ego atau topik konkret, semua balasan seragam manisnya." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis pesan formal ke dosen",
    text:"Selamat sore Bu. Mohon maaf mengganggu waktunya. Saya Rina dari kelas Metode Penelitian Selasa pagi. Izin bertanya, apakah pengumpulan proposal masih dibuka sampai Jumat? Saya terkendala revisi bab 3. Terima kasih Bu.",
    explain:"JEBAKAN sebaliknya: pesan MANUSIA ke dosen yang formal karena sopan-santun akademik. Detail identitas spesifik (Rina, kelas Selasa pagi) dan kendala nyata (revisi bab 3) menandakan mahasiswa asli." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru drama chat",
    text:"aku kecewa sih sama sikap kamu tadi. bukannya aku baperan, tapi kadang aku ngerasa nggak dihargai. mungkin aku kebanyakan berharap ya. yaudah gapapa, aku ngerti kok kamu sibuk. aku belajar buat lebih legowo.",
    explain:"JEBAKAN. AI meniru drama pertemanan: emosi yang mengalir terlalu rapi dari kecewa ke legowo dalam satu tarikan. Manusia yang benar-benar kesal biasanya lebih meledak atau menggantung, bukan seresolusi ini." }
]},

{ id:17, nama:"PAKET 17 — TRAVEL & TEMPAT", soal:[
  { isAI:true, level:1, cue:"Deskripsi destinasi generik",
    text:"Destinasi ini menawarkan pesona alam yang memukau dengan pemandangan yang menakjubkan. Cocok bagi Anda yang ingin melepas penat dari rutinitas dan menikmati ketenangan yang jauh dari hiruk-pikuk perkotaan.",
    explain:"'Pesona memukau', 'melepas penat', 'hiruk-pikuk perkotaan'. Deskripsi wisata yang bisa dipakai untuk ribuan tempat berbeda. Nol detail spesifik." },
  { isAI:false, level:1, cue:"Tips traveler jujur",
    text:"jangan percaya foto instagram air terjunnya. aslinya buat ke situ harus trekking 2 jam lewat kebun warga, dan pas nyampe ternyata rame banget sama rombongan study tour. mending subuh kalau mau sepi",
    explain:"Peringatan realistis (foto menipu), detail perjalanan spesifik (2 jam, kebun warga, study tour), saran waktu. Pengalaman traveler nyata." },
  { isAI:true, level:1, cue:"Ajakan liburan",
    text:"Sudah saatnya Anda memanjakan diri dengan liburan impian! Ciptakan kenangan tak terlupakan bersama orang-orang tersayang di destinasi yang memukau. Pesan sekarang dan wujudkan petualangan yang menanti Anda!",
    explain:"'Memanjakan diri', 'kenangan tak terlupakan', 'petualangan yang menanti'. Copywriting travel agent template dengan ajakan generik." },
  { isAI:false, level:1, cue:"Cerita nyasar",
    text:"gara2 ikutin gmaps malah nyasar ke gang buntu terus disamperin bapak2 warung. eh malah dikasih tau jalan tikus sama ditawarin kopi. akhirnya nyampe pantai telat tapi dapet cerita sama temen baru",
    explain:"Kejadian tak terduga yang spesifik (gang buntu, bapak warung, jalan tikus), akhir yang manusiawi. Anekdot perjalanan yang tak bisa dikarang." },
  { isAI:true, level:2, cue:"Artikel wisata SEO",
    text:"Kota ini menyimpan sejuta pesona yang menanti untuk diungkap. Perpaduan antara warisan sejarah yang kaya, budaya yang autentik, dan keindahan alam yang mempesona menjadikannya destinasi yang wajib masuk daftar kunjungan Anda.",
    explain:"'Menyimpan sejuta pesona menanti diungkap', trio sejarah-budaya-alam, 'wajib masuk daftar'. Artikel SEO wisata yang isinya kata kunci belaka." },
  { isAI:false, level:2, cue:"Review penginapan detail",
    text:"kamarnya bersih, view sawah beneran kayak di foto. tapi dinding tipis banget, semalaman denger tetangga ngorok. air panas cuma nyala jam 6-9 pagi. worth it buat harganya, asal bawa earplug dan mandi pagi",
    explain:"Penilaian berimbang dengan cacat spesifik (dinding tipis, jam air panas) dan saran praktis. Ulasan tamu yang benar-benar menginap." },
  { isAI:true, level:2, cue:"Itinerary kaku",
    text:"Hari pertama, Anda dapat mengeksplorasi keindahan pusat kota yang menawan. Hari kedua, nikmati wisata alam yang menyegarkan. Hari ketiga, sempurnakan perjalanan Anda dengan berbelanja oleh-oleh khas yang beragam.",
    explain:"Itinerary tanpa nama tempat, jam, atau biaya. 'Menawan', 'menyegarkan', 'beragam' adalah pengisi. Rencana perjalanan hasil generate." },
  { isAI:false, level:2, cue:"Kekecewaan wisata",
    text:"jauh-jauh ke sana ternyata pantainya lagi surut parah dan banyak sampah kiriman. mungkin salah aku juga sih dateng pas musim angin barat. yang jual es kelapa aja sampe bilang 'mas salah bulan'",
    explain:"Kekecewaan dengan konteks spesifik (surut, angin barat), refleksi diri, kutipan lokal yang jenaka. Pengalaman apes yang otentik." },
  { isAI:true, level:2, cue:"Penutup travel blog",
    text:"Pada akhirnya, perjalanan bukanlah tentang tujuan, melainkan tentang proses menemukan diri sendiri. Setiap langkah mengajarkan kita untuk lebih menghargai keindahan dunia dan makna dari setiap pertemuan yang berharga.",
    explain:"'Bukan tentang tujuan melainkan proses' + 'menemukan diri sendiri'. Penutup travel blog paling klise dan generik. Kebijaksanaan tempelan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis panduan rapi",
    text:"Transport dari bandara: taksi bandara resmi Rp150rb fix, atau bus Damri Rp40rb tiap 30 menit sampai jam 21.00. Hindari calo di pintu keluar yang nawarin Rp80rb, biasanya argo kuda. Simpan struk parkir kalau dijemput.",
    explain:"JEBAKAN. Panduan MANUSIA yang rapi karena ingin membantu. Petunjuknya: angka spesifik (Rp150rb, tiap 30 menit) dan peringatan berdasar pengalaman ('argo kuda') yang tak dikarang mesin." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru caption travel",
    text:"tersesat di keindahan kota tua ✨ kadang hal terbaik dalam hidup ditemukan saat kita berhenti mencari. bersyukur bisa ada di sini, menikmati setiap momen. traveling is my therapy 🌏 #blessed #wanderlust",
    explain:"JEBAKAN. AI meniru caption traveler: aforisme 'ditemukan saat berhenti mencari', hashtag, emoji. Terdengar dalam tapi kosong, tanpa detail tempat yang benar-benar dikunjungi." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis deskriptif indah",
    text:"Dari puncak, kota tampak seperti sarang lampu yang berkedip malas. Angin di sini dingin sampai ke gigi. Aku duduk di batu yang sama tempat almarhum kakekku dulu memancing, dan untuk sesaat, rasanya beliau ikut duduk di sebelahku.",
    explain:"JEBAKAN sebaliknya: tulisan MANUSIA yang indah dan personal. Gaya deskriptif sering dituduh AI, tapi kenangan spesifik (batu kakek memancing) menandakan pengalaman dan perasaan sungguhan." }
]},

{ id:18, nama:"PAKET 18 — PENDIDIKAN & PARENTING", soal:[
  { isAI:true, level:1, cue:"Nasihat parenting generik",
    text:"Sebagai orang tua, penting untuk selalu mendampingi tumbuh kembang anak dengan penuh kasih sayang. Berikan dukungan, pahami kebutuhannya, dan jadilah teladan yang baik agar anak tumbuh menjadi pribadi yang berkarakter.",
    explain:"Trio dukungan-pahami-teladan + 'pribadi yang berkarakter'. Nasihat parenting yang benar tapi hampa, tanpa situasi konkret. Konten generate." },
  { isAI:false, level:1, cue:"Keluh kesah orang tua",
    text:"anakku yang TK tiba2 nolak sekolah, nangis tiap pagi. ternyata gara2 dia diketawain temennya waktu ngompol pas tidur siang. gimana ya, pengen marahin temennya tapi kan masih 5 tahun juga",
    explain:"Masalah spesifik (nolak sekolah, ngompol, diketawai), dilema moral orang tua yang realistis. Pergulatan parenting nyata, bukan tips template." },
  { isAI:true, level:1, cue:"Tips belajar efektif",
    text:"Belajar yang efektif membutuhkan strategi yang tepat. Buatlah jadwal yang teratur, ciptakan suasana yang kondusif, dan gunakan metode belajar yang sesuai dengan gaya belajarmu agar hasilnya optimal dan maksimal.",
    explain:"'Strategi yang tepat', trio jadwal-suasana-metode, 'optimal dan maksimal'. Tips belajar universal tanpa contoh atau teknik spesifik." },
  { isAI:false, level:1, cue:"Cerita guru",
    text:"murid paling bandel di kelasku, yang tiap hari kutegur, kemarin bawain aku kopi sachet dari kantin pake uang jajannya sendiri. cuma bilang 'buat ibu, biar nggak ngantuk ngajarin saya'. langsung mewek di toilet",
    explain:"Momen spesifik dan menyentuh (kopi sachet, uang jajan), reaksi jujur (mewek di toilet). Pengalaman mengajar yang tak bisa dikarang mesin." },
  { isAI:true, level:2, cue:"Esai pendidikan formal",
    text:"Pendidikan merupakan pilar utama dalam membangun peradaban bangsa. Melalui pendidikan yang berkualitas, generasi muda dapat mengembangkan potensi, membentuk karakter, dan mempersiapkan diri menghadapi tantangan masa depan yang semakin kompleks.",
    explain:"'Pilar utama', 'peradaban bangsa', trio potensi-karakter-masa depan. Esai pendidikan textbook yang bisa dirangkai mesin dalam sekejap." },
  { isAI:false, level:2, cue:"Refleksi mengajar jujur",
    text:"aku sadar metodeku salah pas 20 dari 32 anak dapat nilai jelek di topik yang sama. bukan mereka yang bodoh, aku yang ngajarnya kecepetan. minggu ini aku ulang dari nol, pakai analogi jualan gorengan. eh mereka ngerti",
    explain:"Angka spesifik (20 dari 32), pengakuan kesalahan diri, solusi kreatif konkret (analogi gorengan). Refleksi pedagogis dari praktik nyata." },
  { isAI:true, level:2, cue:"Kutipan motivasi pendidikan",
    text:"Ilmu adalah cahaya yang menerangi jalan menuju masa depan yang gemilang. Teruslah belajar tanpa henti, karena setiap pengetahuan yang kau raih adalah bekal berharga untuk meraih mimpi dan mengubah dunia menjadi lebih baik.",
    explain:"'Cahaya menerangi jalan', 'masa depan gemilang', 'mengubah dunia'. Kutipan motivasi penuh metafora klise tanpa isi praktis." },
  { isAI:false, level:2, cue:"Diskusi PR anak",
    text:"tolong deh soal matematika kelas 4 sekarang. 'ibu punya 3 apel, ayah beli lagi. berapa apel?'. lah berapa yang dibeli ayah nggak dikasih tau. anakku bingung, aku bingung, akhirnya kita jawab 'tergantung ayah'",
    explain:"Kritik spesifik pada soal yang ambigu, kebingungan bersama, jawaban jenaka. Momen parenting-akademik yang otentik dan tak terduga." },
  { isAI:true, level:2, cue:"Saran pola asuh",
    text:"Setiap anak adalah individu yang unik dengan potensi yang berbeda-beda. Oleh karena itu, orang tua perlu menerapkan pendekatan yang fleksibel, penuh empati, dan konsisten dalam mendidik agar anak berkembang secara optimal.",
    explain:"'Individu yang unik', trio fleksibel-empati-konsisten, 'berkembang optimal'. Saran pola asuh yang benar tapi generik. Tanpa contoh situasi." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis surat wali kelas rapi",
    text:"Kepada Bapak/Ibu wali murid Kelas 5B. Diberitahukan bahwa pengambilan rapor dijadwalkan Sabtu 20 Juli pukul 08.00-11.00. Mohon hadir tepat waktu karena ruang kelas dipakai untuk kegiatan lain pukul 11.30. Terima kasih.",
    explain:"JEBAKAN. Surat wali kelas MANUSIA yang rapi karena genre resmi sekolah. Detail spesifik (kelas 5B, jam bentrok kegiatan lain) menandakan konteks nyata, bukan generate." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru cerita parenting",
    text:"jadi ibu itu nggak pernah mudah ya. hari ini si kecil rewel seharian, aku sampai nangis diam-diam di dapur. tapi pas dia peluk dan bilang 'mama cantik', semua lelah langsung hilang. bersyukur banget dipercaya jadi ibunya 🥹",
    explain:"JEBAKAN. AI meniru cerita parenting: arc 'lelah lalu terharu' yang terlalu rapi, ditutup rasa syukur generik. Detail ('mama cantik') terasa dipilih untuk manis, bukan spontan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis renungan pendidikan",
    text:"Kadang aku ragu, apa yang kuajarkan hari ini akan berguna 20 tahun lagi ketika mereka dewasa di dunia yang bahkan belum bisa kubayangkan. Tapi mungkin bukan rumusnya yang penting. Mungkin cukup mereka ingat pernah ada yang percaya mereka bisa.",
    explain:"JEBAKAN sebaliknya: renungan guru MANUSIA yang reflektif dan agak melankolis. Gaya kontemplatif sering dituduh AI, tapi keraguan jujur dan pemikiran yang bergerak menandakan penulis nyata." }
]},

{ id:19, nama:"PAKET 19 — AKADEMIK & ILMIAH LANJUTAN", theme:"akademik", soal:[
  { isAI:true, level:1, cue:"Rumusan masalah generik",
    text:"Berdasarkan latar belakang di atas, rumusan masalah dalam penelitian ini adalah bagaimana pengaruh variabel X terhadap variabel Y, serta faktor-faktor apa saja yang memengaruhi hubungan antara kedua variabel tersebut.",
    explain:"Rumusan masalah kosong (variabel X dan Y tanpa isi), 'faktor-faktor apa saja'. Kerangka template yang bisa ditempel ke skripsi mana pun. Ciri generate." },
  { isAI:false, level:1, cue:"Rumusan masalah spesifik",
    text:"Mengapa program bank sampah di Kelurahan Sukamaju berhenti setelah 8 bulan padahal partisipasi awal mencapai 70% KK? Penelitian ini menelusuri titik putus keterlibatan warga dari sisi insentif ekonomi.",
    explain:"Pertanyaan tajam dengan data (8 bulan, 70% KK), lokasi dan fokus spesifik. Rumusan masalah yang lahir dari fenomena nyata yang diamati." },
  { isAI:true, level:1, cue:"Tinjauan pustaka merangkai",
    text:"Berbagai penelitian terdahulu telah membahas topik ini secara mendalam. Beberapa ahli berpendapat bahwa fenomena tersebut dipengaruhi oleh banyak faktor yang saling berkaitan dan memerlukan kajian lebih lanjut yang komprehensif.",
    explain:"'Berbagai penelitian', 'beberapa ahli' tanpa satu nama atau tahun. 'Kajian komprehensif lebih lanjut'. Tinjauan pustaka hantu tanpa sitasi nyata." },
  { isAI:false, level:1, cue:"Sitasi konkret",
    text:"Temuan ini sejalan dengan Wibowo (2021) yang menemukan pola serupa di Malang, namun bertentangan dengan Sari (2019) yang justru mencatat kenaikan. Perbedaan ini kemungkinan disebabkan konteks kebijakan daerah yang berbeda.",
    explain:"Nama dan tahun spesifik, lokasi (Malang), dan analisis perbedaan antar sumber. Peneliti yang benar-benar membaca dan membandingkan literatur." },
  { isAI:true, level:2, cue:"Metodologi bertele",
    text:"Penelitian ini menggunakan pendekatan kualitatif dengan metode deskriptif. Data dikumpulkan melalui observasi, wawancara, dan dokumentasi, kemudian dianalisis secara mendalam untuk memperoleh pemahaman yang holistik dan menyeluruh mengenai fenomena yang diteliti.",
    explain:"Trio observasi-wawancara-dokumentasi + 'holistik dan menyeluruh'. Metodologi textbook tanpa jumlah informan, durasi, atau teknik analisis spesifik." },
  { isAI:false, level:2, cue:"Metodologi detail",
    text:"Wawancara mendalam dilakukan terhadap 9 informan (5 pedagang, 3 pembeli, 1 petugas pasar) selama Maret-April 2024. Transkrip dikoding dengan MAXQDA menggunakan skema tema awal dari teori Ostrom, lalu direvisi setelah putaran koding kedua.",
    explain:"Jumlah dan komposisi informan spesifik, alat (MAXQDA), teori (Ostrom), proses koding iteratif. Metodologi yang benar-benar dijalankan." },
  { isAI:true, level:2, cue:"Kesimpulan mengulang",
    text:"Berdasarkan hasil penelitian, dapat disimpulkan bahwa variabel independen berpengaruh signifikan terhadap variabel dependen. Hal ini menunjukkan bahwa hipotesis penelitian diterima dan sesuai dengan teori yang telah dikemukakan sebelumnya.",
    explain:"Kesimpulan yang cuma mengulang 'berpengaruh signifikan' tanpa angka atau nuansa. 'Hipotesis diterima' generik. Penutup skripsi hasil generate." },
  { isAI:false, level:2, cue:"Temuan mengejutkan",
    text:"Yang tidak kami duga: insentif uang justru menurunkan partisipasi jangka panjang. Warga mulai memandang menabung sampah sebagai 'kerja tak dibayar layak', bukan lagi gotong royong. Ini bertolak belakang dengan asumsi awal proposal kami.",
    explain:"Temuan kontra-intuitif yang spesifik, kutipan warga, pengakuan bahwa hasil bertentangan dengan asumsi. Kejujuran ilmiah dari penelitian nyata." },
  { isAI:true, level:2, cue:"Abstrak berpola",
    text:"Penelitian ini bertujuan untuk menganalisis fenomena tersebut. Menggunakan metode kualitatif, penelitian ini menemukan bahwa terdapat pengaruh yang signifikan. Hasil ini diharapkan dapat memberikan kontribusi bagi pengembangan ilmu pengetahuan.",
    explain:"Abstrak yang setiap kalimatnya kosong: tujuan menganalisis 'fenomena tersebut', hasil 'signifikan', 'kontribusi bagi ilmu'. Nol temuan konkret." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — birokrat akademik menulis kaku",
    text:"Sehubungan dengan pengajuan proposal Saudara, dengan ini disampaikan bahwa berkas dikembalikan untuk diperbaiki pada bagian metodologi sebagaimana catatan terlampir. Batas pengumpulan revisi selambat-lambatnya 14 hari kerja sejak surat ini diterima.",
    explain:"JEBAKAN. Surat administrasi kampus MANUSIA yang kaku. 'Sebagaimana catatan terlampir', 'selambat-lambatnya 14 hari kerja' adalah bahasa birokrasi akademik yang memang beku sejak lama." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — parafrase AI di landasan teori",
    text:"Menurut para ahli, komunikasi organisasi dapat dipahami sebagai proses penyampaian dan pertukaran informasi dalam suatu struktur yang bertujuan mencapai tujuan bersama secara efektif dan efisien melalui koordinasi yang terintegrasi.",
    explain:"JEBAKAN. Parafrase AI: 'menurut para ahli' tanpa nama, definisi mulus dengan 'efektif dan efisien', 'terintegrasi'. Benar, rapi, dan tidak menambahkan pemikiran apa pun." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — mahasiswa menulis akademik rapi",
    text:"Studi ini berkontribusi pada tiga hal: memperluas teori difusi inovasi ke konteks pedesaan Indonesia, menyediakan data empiris tentang peran tokoh agama sebagai agen perubahan, dan menawarkan model insentif non-moneter yang teruji di lapangan.",
    explain:"JEBAKAN sebaliknya: kontribusi penelitian MANUSIA yang rapi dan terstruktur. Meski pakai pola tiga hal, tiap poin spesifik dan substantif (teori difusi, tokoh agama, insentif non-moneter), bukan tempelan kosong." }
]},

{ id:20, nama:"PAKET 20 — ZONA KABUT 2 (SEMUA JEBAKAN)", soal:[
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI dengan typo yang disengaja",
    text:"duh td pagi telat bgt gara2 alarm gabunyi, pdhl udh pasang 3 alarm. ujungnya sarapan cuma roti sambil lari ngejar bis. emg klo hari senin tuh musuh terbesar umat manusia ya wkwk",
    explain:"JEBAKAN. AI yang diminta 'tulis santai pakai singkatan dan typo'. Ketidaksempurnaan pun bisa dipalsukan. Petunjuk: keluhan senin terlalu 'relatable universal', tanpa detail yang benar-benar spesifik." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis sangat rapi",
    text:"Dengan hormat, saya sampaikan pengunduran diri saya dari jabatan bendahara terhitung 1 Agustus 2026. Laporan keuangan telah saya rekonsiliasi hingga Juli dan akan saya serahkan beserta bukti fisik saat serah terima. Terima kasih atas kepercayaannya.",
    explain:"JEBAKAN. Surat pengunduran diri MANUSIA yang sangat rapi karena harus formal. Komitmen konkret (rekonsiliasi sampai Juli, bukti fisik) menandakan tanggung jawab personal, bukan template." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru puisi",
    text:"Hujan turun perlahan di jendela kamarku,\nmembasuh sepi yang tak pernah kuundang.\nSetiap tetesnya berbisik tentang rindu,\nyang tumbuh diam-diam di ruang tunggu.",
    explain:"JEBAKAN. Puisi buatan AI: rima terlalu rapi, citra klise (hujan-sepi-rindu), tak ada satu detail konkret yang mengejutkan. Indah di permukaan tapi bisa digenerate ribuan versi." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — penyair amatir menulis klise",
    text:"Senja itu jingga,\nseperti hatiku yang merindukanmu.\nKau pergi tanpa kata,\nmeninggalkan luka yang tak sembuh.",
    explain:"JEBAKAN sebaliknya: puisi MANUSIA (amatir) yang penuh klise. Klise ('senja jingga', 'luka tak sembuh') sering dituduh AI, padahal manusia yang baru belajar menulis juga sering begitu." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru review kesal",
    text:"pelayanannya lama banget, nunggu 45 menit baru dianter. makanannya sih oke tapi ekspektasi jadi turun gara2 nunggu. mungkin lagi rame kali ya. tetep kasih bintang 3 lah, kasian juga yang masak.",
    explain:"JEBAKAN. AI meniru review kesal: keluhan (45 menit) lalu buru-buru memaafkan dan berempati ('kasian yang masak'). Terlalu adil dan seimbang, kekesalan manusia nyata biasanya lebih berat sebelah." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — reviewer manusia menulis profesional",
    text:"Bakmi di sini juara di teksturnya, kenyal berongga khas buatan tangan, bukan pabrikan. Kuah kaldunya bening tapi dalam, jelas rebusan lama. Minusnya cuma satu: acarnya kurang asam, jadi berlemak di suapan terakhir. Tetap rekomendasi kuat.",
    explain:"JEBAKAN sebaliknya: review MANUSIA yang profesional dan rapi. Ketajaman detail (kenyal berongga, kuah bening tapi dalam, kritik acar spesifik) menandakan pengecap yang benar-benar makan dan paham." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru chat marah",
    text:"aku kesel sih sebenernya. tapi yaudahlah ya. mungkin emang aku yang terlalu sensitif. maaf kalau aku berlebihan. aku cuma pengen didengar aja sebenernya. yaudah lupain aja, gapenting kok.",
    explain:"JEBAKAN. AI meniru chat marah: emosi yang mengalir terlalu tertata dari kesal ke menyalahkan diri ke pasrah. Manusia yang benar-benar marah biasanya lebih meledak, terputus, atau tidak seruntut ini." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis pengumuman rapi",
    text:"INFO: Air mati serentak Blok C besok 09.00-15.00 karena perbaikan pipa induk. Tampung dari sekarang. Yang punya bayi/lansia bisa ambil galon gratis di pos RW (bawa jerigen sendiri). Maaf merepotkan, kata PDAM darurat.",
    explain:"JEBAKAN sebaliknya: pengumuman warga MANUSIA yang rapi karena harus jelas. Detail spesifik (Blok C, jam, galon gratis untuk bayi/lansia) dan nada peduli menandakan penulis nyata di lapangan." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru caption reflektif",
    text:"terkadang hidup memberi kita jalan yang tak kita mengerti. namun percayalah, setiap proses pasti ada hikmahnya. tetap melangkah meski pelan, karena yang terpenting bukan seberapa cepat, tapi seberapa ikhlas kita menjalaninya.",
    explain:"JEBAKAN. AI meniru caption reflektif: aforisme berima ('bukan seberapa cepat tapi seberapa ikhlas'), bijak generik. Terdengar dalam tapi kosong, tanpa satu pengalaman spesifik penulis." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis pesan singkat kaku",
    text:"Pak, mohon maaf. Motor saya mogok di tengah jalan, sepertinya aki. Saya akan telat sekitar 40 menit. Tugas presentasi tetap saya bawa. Kalau giliran saya terlewat, mohon izin maju setelah saya tiba. Sekali lagi mohon maaf.",
    explain:"JEBAKAN sebaliknya: pesan izin MANUSIA yang kaku karena sopan pada atasan. Kendala spesifik (motor mogok, aki, 40 menit) dan komitmen konkret menandakan situasi darurat nyata." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru thread edukatif",
    text:"Banyak orang salah kaprah soal ini. Padahal faktanya sederhana. Mari kita bahas satu per satu. Pertama, penting untuk memahami dasarnya. Kedua, terapkan secara konsisten. Ketiga, evaluasi hasilnya. Semoga bermanfaat, jangan lupa share ya!",
    explain:"JEBAKAN. Thread edukatif AI: pembuka clickbait 'banyak yang salah kaprah', struktur pertama-kedua-ketiga yang kosong isi, penutup 'jangan lupa share'. Kerangka tanpa substansi." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis instruksi teknis rapi",
    text:"Kalau lampu indikator kedip merah 3x, itu bukan rusak, cuma overheat. Matikan, cabut, diamkan 15 menit di tempat teduh, jangan disemprot air (malah retak). Nyalakan lagi, biasanya normal. Kalau kedip 5x baru bawa ke servis.",
    explain:"JEBAKAN sebaliknya: instruksi teknis MANUSIA yang rapi karena paham betul. Detail spesifik (kedip 3x vs 5x, jangan disemprot air) dari pengalaman langsung, bukan generalisasi mesin." }
]}

];

/* ---------- sambungkan ke PAKET dari paket.js (tanpa mengubah paket.js) ----------
   Push additif + penjaga anti-dobel kalau file tak sengaja dimuat dua kali. */
(function mergePaketEkstra(){
  if(typeof PAKET==="undefined" || !Array.isArray(PAKET)){
    console.warn("[paket_ekstra] PAKET belum ada. Pastikan paket_ekstra.js dimuat SETELAH paket.js.");
    return;
  }
  const sudahAda = new Set(PAKET.map(p=>p.id));
  const baru = PAKET_EKSTRA.filter(p=>!sudahAda.has(p.id));
  if(baru.length) PAKET.push(...baru);
})();
