/* ================================================================
   SINYAL — PAKET SOAL TEKS (10 paket × 10 soal = 100 spesimen)
   Tiap soal: { isAI, level(1=dasar/2=sulit), cue, text, explain, trap? }
   isAI = KUNCI JAWABAN: true = buatan AI, false = karya manusia.
   CATATAN VERSI FINAL: teks "manusia" di bawah masih contoh gaya —
   ganti dengan kutipan asli bersumber + atribusi untuk laporan.
   ================================================================ */
const PAKET = [

{ id:1, nama:"PAKET 01 — KEHIDUPAN KAMPUS", soal:[
  { isAI:true, level:1, cue:"Esai tiga manfaat rapi",
    text:"Organisasi kemahasiswaan memiliki peran penting dalam pengembangan diri mahasiswa. Selain melatih kepemimpinan, organisasi juga mengasah kemampuan komunikasi serta memperluas jaringan pertemanan. Oleh karena itu, mahasiswa sebaiknya aktif berorganisasi.",
    explain:"Pola AI klasik: klaim umum + tiga manfaat seimbang + penutup 'oleh karena itu'. Tanpa pengalaman konkret." },
  { isAI:false, level:1, cue:"Keluhan spesifik",
    text:"kelas jam 7 pagi tuh harusnya ilegal. udah mandinya buru2, eh dosennya baru dateng 7.40 santai banget bawa gorengan",
    explain:"Detail remeh yang hidup (7.40, gorengan) dan kekesalan personal — tekstur pengalaman nyata." },
  { isAI:true, level:1, cue:"Nasihat generik",
    text:"Manajemen waktu adalah kunci kesuksesan mahasiswa. Dengan membuat jadwal yang teratur dan menetapkan prioritas, kita dapat menyeimbangkan antara akademik, organisasi, dan kehidupan pribadi.",
    explain:"'Kunci kesuksesan', 'menetapkan prioritas', 'menyeimbangkan' — kosakata motivasi netral tanpa penulis yang terlihat." },
  { isAI:false, level:1, cue:"Cerita gagal yang jujur",
    text:"presentasi kelompok tadi kacau. laptopku ngeblank pas slide 3, temenku panik malah nutup semua tab termasuk ppt-nya. untung dosennya ketawa",
    explain:"Kegagalan spesifik yang memalukan — manusia menceritakan aib sendiri, AI cenderung menghindarinya." },
  { isAI:true, level:1, cue:"Definisi kaku",
    text:"KKN atau Kuliah Kerja Nyata merupakan program pengabdian masyarakat yang bertujuan menerapkan ilmu pengetahuan yang diperoleh di bangku kuliah untuk memberikan manfaat nyata bagi masyarakat.",
    explain:"'Merupakan… yang bertujuan… memberikan manfaat nyata' — kalimat definisi ensiklopedis khas rangkuman AI." },
  { isAI:false, level:2, cue:"Humor observasional",
    text:"fase paling berbahaya mahasiswa itu bukan skripsi, tapi pas KRS-an. jam 00.01 satu angkatan berubah jadi atlet esport demi rebutan kelas pak dosen favorit",
    explain:"Analogi tak terduga (KRS = esport) dan timing spesifik (00.01) — kreativitas komikal khas manusia." },
  { isAI:true, level:2, cue:"Refleksi puitis kosong",
    text:"Wisuda bukan sekadar akhir dari perjalanan, melainkan awal dari petualangan baru. Setiap toga yang dikenakan menyimpan cerita perjuangan yang tak ternilai harganya.",
    explain:"Struktur 'bukan sekadar X melainkan Y' + 'tak ternilai harganya' — puitis generik tanpa detail siapa pun." },
  { isAI:false, level:2, cue:"Pesan fungsional",
    text:"bro notulen rapat kemarin ada di gdrive folder yg mana? aku cari di 'rapat fix' sama 'rapat fix 2' gaada, jgn bilang kesimpen di folder 'jgn dibuka'",
    explain:"Kekacauan penamaan folder yang sangat familiar — konteks mikro yang tidak dihasilkan AI tanpa dipancing." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI gaya curhat",
    text:"capek banget sih jadi mahasiswa semester akhir 😭 revisi mulu tiap minggu, temen udah pada lulus. tapi yaudah lah ya, pelan pelan asal sampai. semangat juga buat kalian yang lagi berjuang ✊",
    explain:"JEBAKAN. AI meniru curhat: emoji, keluhan umum, ditutup penyemangat kolektif. Terlalu 'rapi' emosinya — tapi hampir mustahil dipastikan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis formal",
    text:"Sehubungan dengan pelaksanaan ujian tengah semester, dimohon seluruh mahasiswa untuk membawa kartu ujian dan hadir 15 menit sebelum ujian dimulai. Keterlambatan lebih dari 30 menit tidak diperkenankan mengikuti ujian.",
    explain:"JEBAKAN sebaliknya: pengumuman resmi buatan MANUSIA (staf akademik). Register birokratis sering dituduh AI — padahal genre ini memang kaku sejak dulu." }
]},

{ id:2, nama:"PAKET 02 — MEDIA SOSIAL", soal:[
  { isAI:true, level:1, cue:"Caption inspiratif generik",
    text:"Jangan bandingkan perjalananmu dengan orang lain. Setiap orang memiliki waktunya masing-masing untuk bersinar. Fokus pada prosesmu, dan biarkan hasilnya berbicara. ✨",
    explain:"Rangkaian kalimat motivasi yang bisa ditempel di foto apa pun — tanpa konteks, tanpa pemilik." },
  { isAI:false, level:1, cue:"Celetukan absurd",
    text:"kenapa ya tiap mau tidur otak malah muterin kejadian malu2in tahun 2017. woy udah lewat woy",
    explain:"Self-deprecating spesifik (tahun 2017) dengan repetisi lisan 'woy… woy' — ritme bicara asli." },
  { isAI:true, level:1, cue:"Thread edukasi kaku",
    text:"5 kebiasaan kecil yang mengubah hidupmu: 1) Bangun lebih pagi 2) Membaca 10 menit sehari 3) Menulis jurnal 4) Olahraga ringan 5) Bersyukur. Mulai dari satu, konsisten adalah kuncinya.",
    explain:"Listicle self-improvement dengan penutup 'konsisten adalah kuncinya' — template konten AI paling umum di medsos." },
  { isAI:false, level:1, cue:"Reaksi spontan",
    text:"HAH indomie goreng rasa baru??? gerak cepet ini mah, kalo sold out di warung madura depan kos aku ngamuk",
    explain:"Kapital emosional, tanda tanya tiga, dan hiperlokal 'warung madura depan kos' — spontanitas manusia." },
  { isAI:true, level:1, cue:"Balasan customer service",
    text:"Halo Kak! Terima kasih sudah menghubungi kami 😊 Mohon maaf atas ketidaknyamanannya ya, Kak. Silakan kirimkan nomor pesanan Kakak melalui DM agar dapat segera kami bantu proses. Terima kasih! 🙏",
    explain:"Template CS: sapaan 'Kak', maaf standar, arahan ke DM. Kini mayoritas dijawab bot/AI — pola sangat seragam." },
  { isAI:false, level:2, cue:"Sarkasme berlapis",
    text:"suka banget sama orang yang nge-reply story cuma buat promosiin bisnisnya. iya kak, kabar aku baik, dan enggak, aku belum butuh asuransi",
    explain:"Sarkasme dua lapis dengan dialog imajiner — humor pasif-agresif yang khas manusia kesal beneran." },
  { isAI:true, level:2, cue:"Hot take simetris",
    text:"Media sosial tidak membuat kita bodoh atau pintar. Ia hanya memperbesar apa yang sudah ada dalam diri kita. Yang haus ilmu akan menemukan ilmu, yang haus drama akan menemukan drama.",
    explain:"Aforisme paralel sempurna 'yang X akan menemukan X' — kebijaksanaan simetris yang gampang digenerate." },
  { isAI:false, level:2, cue:"Utas pengalaman personal",
    text:"pernah kena hack IG tahun lalu dan yg paling nyesek bukan akunnya, tapi DM sama alm. bapak yg kesimpen di situ. sejak itu aku selalu backup. tolong kalian juga.",
    explain:"Detail emosional yang sangat spesifik dan menyakitkan (DM almarhum) — kedalaman pengalaman yang tak bisa dipalsukan pola." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru shitpost",
    text:"lagi nabung buat beli rumah. sejauh ini udah kekumpul niat sama bismillah",
    explain:"JEBAKAN. Format jokes manusia yang sudah viral berulang kali — AI sangat mahir meniru template humor yang populer. Ini hasil generate." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis 'estetik'",
    text:"Senja hari ini berwarna jingga keemasan. Kubiarkan angin membawa penat yang sejak pagi kupikul. Ternyata pulang tak selalu tentang rumah; kadang ia tentang secangkir teh dan diam yang cukup.",
    explain:"JEBAKAN sebaliknya: manusia yang menulis gaya 'sastra senja' sering terdengar seperti AI — genre ini memang penuh klise sejak sebelum AI ada." }
]},

{ id:3, nama:"PAKET 03 — BERITA & JURNALISME", soal:[
  { isAI:true, level:1, cue:"Lead berita tanpa fakta",
    text:"Perkembangan teknologi kecerdasan buatan semakin pesat dalam beberapa tahun terakhir. Berbagai sektor mulai mengadopsi teknologi ini untuk meningkatkan efisiensi dan produktivitas kerja.",
    explain:"'Semakin pesat', 'berbagai sektor', 'meningkatkan efisiensi' — lead tanpa satu pun fakta spesifik: siapa, kapan, berapa." },
  { isAI:false, level:1, cue:"Lead berita faktual",
    text:"Sebanyak 47 rumah di Kecamatan Turi, Sleman, terendam banjir lahar hujan pada Kamis (12/3) malam setelah hujan deras mengguyur lereng Merapi selama tiga jam. Tidak ada korban jiwa dalam kejadian ini.",
    explain:"Angka pasti, lokasi berjenjang, tanggal, durasi, konfirmasi korban — disiplin 5W1H jurnalis manusia (atau setidaknya, terverifikasi)." },
  { isAI:true, level:1, cue:"Kutipan pejabat hambar",
    text:"\"Kami akan terus berupaya meningkatkan pelayanan kepada masyarakat dan berkomitmen untuk melakukan perbaikan di berbagai aspek,\" ujar pejabat setempat dalam keterangannya.",
    explain:"Kutipan tanpa nama, tanpa jabatan spesifik, isi normatif murni — AI sering menghasilkan 'kutipan hantu' seperti ini." },
  { isAI:false, level:1, cue:"Detail lapangan",
    text:"Di lokasi pengungsian, Painem (63) masih mengenakan daster basah yang sama sejak semalam. \"Sing penting wedhus e slamet,\" katanya sambil menunjuk tiga kambing yang ia ikat di tiang basket.",
    explain:"Nama+usia, kutipan bahasa Jawa, kambing di tiang basket — detail lapangan absurd-nyata yang hanya didapat reporter yang hadir." },
  { isAI:true, level:2, cue:"Analisis dua sisi steril",
    text:"Kebijakan ini menuai pro dan kontra di masyarakat. Sebagian pihak menilai langkah tersebut tepat untuk jangka panjang, sementara pihak lain khawatir akan dampaknya terhadap masyarakat kecil. Pemerintah diharapkan dapat mengambil jalan tengah.",
    explain:"'Pro dan kontra', 'sebagian pihak… pihak lain', 'jalan tengah' — analisis seimbang steril tanpa satu aktor bernama." },
  { isAI:false, level:2, cue:"Kritik bernada",
    text:"Ini kali ketiga jembatan itu ambruk dalam lima tahun — dan kali ketiga pula pejabat datang, berfoto dengan helm proyek, lalu menghilang bersama janji perbaikan permanen.",
    explain:"Repetisi retoris 'kali ketiga' dan sinisme terarah — opini jurnalistik dengan sikap, bukan netralitas mesin." },
  { isAI:true, level:2, cue:"Penutup artikel menggantung",
    text:"Ke depannya, diharapkan seluruh elemen masyarakat dapat bersinergi dan berkolaborasi dalam menghadapi tantangan ini demi terwujudnya masa depan yang lebih baik.",
    explain:"'Bersinergi', 'seluruh elemen masyarakat', 'masa depan lebih baik' — penutup segala-artikel yang tidak mengatakan apa-apa." },
  { isAI:false, level:2, cue:"Koreksi redaksi",
    text:"RALAT: Pada berita edisi Selasa tertulis kerugian Rp2,3 miliar. Yang benar adalah Rp2,3 juta. Kesalahan terjadi pada proses penyuntingan. Redaksi mohon maaf kepada pembaca dan pihak terkait.",
    explain:"Pengakuan kesalahan spesifik dengan nominal — praktik akuntabilitas redaksi manusia; AI jarang 'mengaku salah' seformat ini." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — berita palsu meyakinkan",
    text:"Kementerian Pendidikan dikabarkan akan menghapus skripsi sebagai syarat kelulusan mulai tahun ajaran depan, menyusul evaluasi menyeluruh terhadap beban akademik mahasiswa di 34 provinsi. Keputusan final akan diumumkan bulan depan.",
    explain:"JEBAKAN. Struktur berita rapi + angka '34 provinsi' membuatnya kredibel — padahal fabrikasi AI. Format jurnalistik bisa dipalsukan sempurna; verifikasi sumber adalah satu-satunya penangkal." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — rilis pers manusia",
    text:"Perusahaan berkomitmen penuh mendukung program keberlanjutan melalui inovasi berkelanjutan dan kolaborasi strategis dengan berbagai pemangku kepentingan guna menciptakan nilai tambah bagi masyarakat luas.",
    explain:"JEBAKAN sebaliknya: rilis pers korporat asli buatan MANUSIA. Bahasa humas memang sudah 'seperti AI' jauh sebelum AI ada — genre paling sulit dibedakan." }
]},

{ id:4, nama:"PAKET 04 — PROMOSI & IKLAN", soal:[
  { isAI:true, level:1, cue:"Copy produk template",
    text:"Tampil percaya diri setiap hari dengan tas premium kami! Dibuat dari bahan berkualitas tinggi, desain elegan yang cocok untuk segala suasana. Jangan lewatkan promo spesial bulan ini! 🛍️",
    explain:"'Berkualitas tinggi', 'segala suasana', 'jangan lewatkan' — copywriting default AI: superlatif tanpa satu spesifikasi." },
  { isAI:false, level:1, cue:"Promosi warung jujur",
    text:"BUKA LAGI YA LUR. kmrn tutup 3 hari soale sing masak mudik. menu tetep, harga tetep, sambel tetep pedes e ora masuk akal. Gas mumpung parkiran sepi",
    explain:"Alasan tutup yang jujur, campuran Jawa, dan 'pedes e ora masuk akal' — suara pemilik warung asli, bukan agensi." },
  { isAI:true, level:1, cue:"Iklan jasa berbunga-bunga",
    text:"Wujudkan momen pernikahan impian Anda bersama tim profesional kami. Dengan pengalaman bertahun-tahun dan dedikasi tinggi, kami siap menghadirkan hari bahagia yang tak terlupakan.",
    explain:"'Momen impian', 'dedikasi tinggi', 'tak terlupakan' — tiga klise wedding dalam dua kalimat, nol portofolio konkret." },
  { isAI:false, level:1, cue:"Testimoni berantakan",
    text:"udh 3x beli disini. pengiriman emg agak lama (5 hari) tp packingnya niat bgt pake bubble 3 lapis. minus: kmrn dapet bonus stiker, skrg engga :(",
    explain:"Pujian + keluhan kecil + kekecewaan soal stiker — ketidaksempurnaan review manusia asli." },
  { isAI:true, level:2, cue:"Storytelling brand hampa",
    text:"Berawal dari mimpi sederhana di sebuah dapur kecil, kami percaya bahwa setiap tetes kopi menyimpan cerita. Kini, cerita itu kami bagikan untuk menemani setiap momen berhargamu.",
    explain:"'Dapur kecil', 'setiap tetes menyimpan cerita' — origin story template yang bisa dipakai merek kopi mana pun." },
  { isAI:false, level:2, cue:"Balasan komplain personal",
    text:"Halo kak, bener banget itu kesalahan kami — kurir kami salah tempel resi jadi ketuker sama pesanan lain. Barang kakak OTW ulang hari ini + kami selipkan ekstra. Maaf banget ya kak, ini murni human error 🙏",
    explain:"Mengakui akar masalah spesifik (salah tempel resi) — CS manusia menjelaskan kronologi, bot cenderung minta maaf generik." },
  { isAI:true, level:2, cue:"CTA urgensi palsu",
    text:"STOK TERBATAS! Hanya hari ini, dapatkan diskon hingga 70% untuk semua produk favorit pilihan! Klik link di bio sekarang sebelum kehabisan. Kesempatan tidak datang dua kali!",
    explain:"Tumpukan pemicu urgensi ('hanya hari ini', 'sebelum kehabisan', 'tidak datang dua kali') — formula scarcity yang di-generate massal." },
  { isAI:false, level:2, cue:"Iklan lowongan blak-blakan",
    text:"Cari admin online shop. Gaji UMR jogja, jam kerja jelas, gak ada 'anggap kantor rumah sendiri'. Syarat cuma dua: bisa excel dasar & gak baperan sama customer. Serius kirim CV, gak serius gak usah.",
    explain:"Menyindir klise lowongan lain ('anggap kantor rumah sendiri') — kesadaran budaya dan ketegasan pemilik usaha nyata." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru gaya jujur",
    text:"jujur produk kami gak sempurna. kemasan masih standar, pengiriman kadang telat sehari. tapi soal rasa, kami berani diadu — resep nenek yang gak kami ubah sejak 1987. beli sekali, biasanya balik lagi.",
    explain:"JEBAKAN. 'Kejujuran' pun kini jadi formula copywriting yang AI kuasai: aku kelemahan kecil, klaim keunggulan besar, detail nostalgia (1987). Ini generate-an." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — copywriter manusia profesional",
    text:"Kulit sehat dimulai dari ritual yang tepat. Formula gentle kami dengan 5% Niacinamide bekerja menyamarkan noda tanpa mengiritasi. Teruji dermatologis, cocok untuk kulit sensitif. #GlowDenganCaramu",
    explain:"JEBAKAN sebaliknya: ini gaya copywriter MANUSIA profesional industri skincare. Iklan yang dipoles rapi bukan otomatis AI — manusia dibayar untuk menulis 'seperti mesin'." }
]},

{ id:5, nama:"PAKET 05 — MOTIVASI & RENUNGAN", soal:[
  { isAI:true, level:1, cue:"Metafora perjalanan",
    text:"Hidup adalah sebuah perjalanan, bukan perlombaan. Tidak apa-apa berjalan lambat, selama kamu tidak berhenti. Setiap langkah kecil hari ini adalah investasi untuk masa depanmu.",
    explain:"Tiga klise motivasi berturut-turut (perjalanan, jalan lambat, langkah kecil) — rangkaian yang sangat sering di-generate." },
  { isAI:false, level:1, cue:"Renungan dari kejadian nyata",
    text:"tadi liat bapak2 jualan cilok ujan2an tetep senyum ngelayanin anak SD yang bayarnya pake recehan dihitung satu2. pulang2 aku mikir, keluhanku hari ini kayaknya gak ada apa2nya",
    explain:"Renungan yang lahir dari adegan spesifik (recehan dihitung satu-satu) — refleksi manusia berangkat dari peristiwa, bukan tema." },
  { isAI:true, level:1, cue:"Kutipan simetris",
    text:"Orang sukses bukan yang tidak pernah gagal, melainkan yang tidak pernah berhenti mencoba. Kegagalan hanyalah tanda bahwa kamu sedang berusaha.",
    explain:"Antitesis simetris 'bukan yang X melainkan yang Y' — arsitektur kutipan yang paling mudah diproduksi mesin." },
  { isAI:false, level:1, cue:"Nasihat spesifik keluarga",
    text:"kata bapakku dulu: \"nek utang rokok wae ora iso nyaur, ojo wani utang janji.\" baru ngerti maksudnya sekarang pas udah kerja.",
    explain:"Kutipan bahasa Jawa dari figur nyata + momen pemahaman yang datang terlambat — warisan lisan keluarga, bukan template." },
  { isAI:true, level:2, cue:"Renungan malam generik",
    text:"Malam ini, izinkan dirimu beristirahat. Kamu sudah berjuang keras hari ini, dan itu cukup. Besok adalah lembaran baru dengan kesempatan yang baru. Selamat beristirahat, pejuang kehidupan.",
    explain:"'Lembaran baru', 'pejuang kehidupan' — sapaan hangat tanpa alamat; konten self-care massal produksi AI." },
  { isAI:false, level:2, cue:"Kontra-motivasi jujur",
    text:"gak semua hal harus diambil hikmahnya sih menurutku. kadang kejadian buruk ya emang buruk aja, dan kita boleh kesel dulu tanpa harus buru2 jadi bijak",
    explain:"Menolak formula hikmah — posisi kontrarian dengan nada bicara santai; AI default-nya justru selalu 'mengambil hikmah'." },
  { isAI:true, level:2, cue:"Analogi alam sempurna",
    text:"Jadilah seperti pohon bambu. Ia membutuhkan waktu bertahun-tahun untuk menumbuhkan akarnya, namun ketika saatnya tiba, ia tumbuh menjulang dalam hitungan minggu. Prosesmu tidak terlihat, bukan berarti tidak ada.",
    explain:"Analogi bambu adalah salah satu metafora motivasi paling sering di-generate — lengkap dengan penutup 'prosesmu tidak terlihat'." },
  { isAI:false, level:2, cue:"Pengakuan rapuh",
    text:"umur 23 dan aku masih suka nangis tiap abis telfon ibu. bukan karena sedih, tapi karena suaranya makin kedengeran tua dan aku jauh",
    explain:"Kerentanan spesifik (suara yang menua di telepon) tanpa resolusi menghibur — kejujuran emosional yang tak berformula." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru renungan personal",
    text:"barusan beresin lemari dan nemu kemeja bapak yang udah gak pernah kepake. wanginya masih sama. ternyata rindu itu disimpan di tempat-tempat yang gak kita duga",
    explain:"JEBAKAN. AI kini bisa mensimulasikan renungan personal lengkap dengan detail sensorik (wangi kemeja). Kalimat penutup aforistiknya yang terlalu rapi adalah satu-satunya petunjuk samar." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis klise",
    text:"Semangat pagi! Awali hari dengan senyuman dan hati yang bersyukur. Rezeki tidak akan tertukar. Yang penting kita terus berusaha dan berdoa. Salam sukses untuk kita semua! 💪☀️",
    explain:"JEBAKAN sebaliknya: broadcast WhatsApp khas bapak/ibu paruh baya — 100% manusia. Klise bukan monopoli mesin; manusia juga menulis dengan template." }
]},

{ id:6, nama:"PAKET 06 — PERCAKAPAN SEHARI-HARI", soal:[
  { isAI:false, level:1, cue:"Chat keluarga",
    text:"Nak sudah makan? Ini ibu kirim foto masakan biar kamu ingat rumah. Jangan lupa vitamin yg kemarin ibu titip ke mbak Rara. Gpp pulangnya lebaran saja yg penting sehat",
    explain:"Alur pikiran ibu yang meloncat (makanan→vitamin→lebaran) dengan kepedulian berlapis — pola chat orang tua asli." },
  { isAI:true, level:1, cue:"Balasan chatbot ramah",
    text:"Tentu! Berikut beberapa rekomendasi tempat makan di dekat lokasi Anda. Apakah Anda memiliki preferensi tertentu, misalnya makanan pedas, manis, atau mungkin batasan anggaran? Saya siap membantu! 😊",
    explain:"Struktur 'Tentu! Berikut… Apakah Anda… Saya siap membantu' — asisten AI dengan keramahan prosedural." },
  { isAI:false, level:1, cue:"Grup RT ricuh kecil",
    text:"pak2 ibu2 mohon maaf mengganggu, kucing oren yg suka tidur di pos ronda itu punya siapa nggih? dia masuk rumah saya dan skrg gamau keluar dari kardus tv",
    explain:"Konflik mikro absurd yang sangat lokal (kucing oren, kardus TV) — kejadian nyata yang tidak terpikir oleh generator." },
  { isAI:true, level:1, cue:"Ucapan ulang tahun kaku",
    text:"Selamat ulang tahun! Semoga di usia yang baru ini, segala impian dan harapanmu dapat terwujud. Semoga selalu diberikan kesehatan, kebahagiaan, dan kesuksesan dalam setiap langkahmu.",
    explain:"Tiga paket doa standar (kesehatan-kebahagiaan-kesuksesan) tanpa satu pun sentuhan personal — ucapan hasil generate/copas." },
  { isAI:false, level:2, cue:"Negosiasi receh",
    text:"bang besok jadi nemenin ke kondangan gak. gapapa dateng bentar doang yg penting absen. nanti bensin aku ganti + traktir mixue deh. jgn php kayak minggu lalu",
    explain:"Tawar-menawar berjenjang (bensin+mixue) dan referensi utang sosial ('kayak minggu lalu') — sejarah pertemanan nyata." },
  { isAI:true, level:2, cue:"Permintaan maaf terstruktur",
    text:"Aku minta maaf atas kesalahanku kemarin. Aku menyadari bahwa perkataanku telah menyakiti perasaanmu, dan itu tidak seharusnya terjadi. Aku akan berusaha menjadi lebih baik lagi ke depannya.",
    explain:"Maaf tiga babak (akui-sadari-berjanji) yang rapi seperti template — manusia yang benar-benar merasa bersalah biasanya lebih berantakan." },
  { isAI:false, level:2, cue:"Chat berantakan bermakna",
    text:"eh btw. gajadi deng. eh jadi. bentar aku telfon aja ribet ngetiknya",
    explain:"Empat perubahan pikiran dalam satu gelembung chat — keraguan real-time yang mustahil disimulasikan dengan wajar." },
  { isAI:true, level:2, cue:"Info kesehatan sopan",
    text:"Untuk keluhan demam yang Anda alami, disarankan untuk memperbanyak istirahat dan minum air putih. Apabila demam berlanjut lebih dari tiga hari, sebaiknya segera konsultasikan ke dokter terdekat.",
    explain:"Saran medis aman berformat baku dengan disclaimer 'konsultasikan ke dokter' — jawaban khas asisten AI kesehatan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia menulis rapi",
    text:"Selamat siang Pak Hendra. Mohon izin, saya tidak dapat hadir rapat sore ini dikarenakan anak saya harus dibawa ke dokter. Notulen akan saya pelajari malam ini dan poin bagian saya tetap saya kirim sebelum pukul 20.00. Terima kasih atas pengertiannya.",
    explain:"JEBAKAN. Pesan izin profesional MANUSIA: rapi karena konteks menuntut rapi. Perhatikan detail komitmen spesifik (pukul 20.00) — tanggung jawab personal yang nyata." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru chat santai",
    text:"wkwk iya bener banget, aku juga ngerasa gitu sih. emang kadang tuh kita butuh break dulu dari semuanya. eh gimana kabar project kamu yg kemarin? semoga lancar ya!",
    explain:"JEBAKAN. AI meniru chat teman: 'wkwk', validasi, lalu balik bertanya. Petunjuk halus: terlalu kooperatif dan mulus — tanpa ego, tanpa distraksi, tanpa typo." }
]},

{ id:7, nama:"PAKET 07 — ULASAN & REKOMENDASI", soal:[
  { isAI:true, level:1, cue:"Review film aman",
    text:"Film ini menawarkan pengalaman sinematik yang memukau dengan visual yang menakjubkan dan alur cerita yang menyentuh. Para pemain berhasil menghidupkan karakter dengan sangat baik. Sangat direkomendasikan!",
    explain:"'Memukau', 'menakjubkan', 'menyentuh' — pujian tanpa satu adegan, nama, atau kritik. Review AI generik." },
  { isAI:false, level:1, cue:"Review film bersudut",
    text:"filmnya bagus SAMPAI 30 menit terakhir. kenapa sih film indo hobi banget nyelesain konflik pake adegan hujan2an nangis di jalan. padahal build up nya udah oke banget",
    explain:"Titik patah spesifik (30 menit terakhir) + kritik pola genre — penonton manusia dengan opini dan kekesalan." },
  { isAI:true, level:1, cue:"Review kuliner template",
    text:"Tempatnya cozy dan instagramable, cocok untuk nongkrong bersama teman maupun keluarga. Menu yang ditawarkan beragam dengan harga yang cukup terjangkau. Pelayanannya juga ramah dan cepat.",
    explain:"Trio 'cozy-beragam-ramah' yang menempel di ribuan review — tak satu pun menu disebut namanya." },
  { isAI:false, level:1, cue:"Review kuliner detail",
    text:"nyobain ayam geprek sambel matah nya. ayamnya juara, kriuknya awet. TAPI nasinya dikit bgt kayak nasi diet, mesti tambah (+3rb). es tehnya manis banget khas jogja. bakal balik tapi bawa bekel nasi",
    explain:"Harga tambah nasi Rp3.000 dan lelucon 'bawa bekel nasi' — granularitas pengalaman makan sungguhan." },
  { isAI:true, level:2, cue:"Rekomendasi buku hambar",
    text:"Buku ini wajib dibaca oleh siapa pun yang ingin mengembangkan diri. Penulis menyajikan gagasan yang mendalam dengan bahasa yang mudah dipahami. Setiap babnya memberikan insight baru yang aplikatif.",
    explain:"'Wajib dibaca', 'insight aplikatif' — endorsement yang cocok untuk buku apa pun berarti tidak menggambarkan buku mana pun." },
  { isAI:false, level:2, cue:"Rekomendasi buku personal",
    text:"baca Laut Bercerita jam 11 malem itu kesalahan. aku nangis di bab kedua dari belakang sampe besoknya mata bengkak dikira abis berantem. bacanya siang aja, siapin mental",
    explain:"Konsekuensi fisik yang memalukan (dikira habis berantem) + saran praktis aneh — testimoni pembaca asli." },
  { isAI:true, level:2, cue:"Perbandingan gadget simetris",
    text:"Kedua ponsel ini memiliki keunggulan masing-masing. Tipe A unggul di sektor kamera, sementara Tipe B menawarkan baterai yang lebih tahan lama. Pilihan kembali kepada kebutuhan dan preferensi masing-masing pengguna.",
    explain:"Perbandingan diplomatis sempurna ditutup 'kembali kepada kebutuhan masing-masing' — AI menghindari memihak." },
  { isAI:false, level:2, cue:"Review jujur menyakitkan",
    text:"hp nya bagus di iklan doang. baterai sehat 4 bulan, abis itu jam 3 sore udah sekarat padahal cuma buat WA. nyesel gak nambah 500rb buat merk sebelah. jangan kayak saya",
    explain:"Penyesalan finansial spesifik (nambah 500rb) dan timeline kerusakan — kepahitan konsumen nyata." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru review kesal",
    text:"kecewa banget. udah nunggu 2 minggu, pas dateng warnanya beda sama di foto. diajak komplain selernya lama bales. bintang 2 buat packingnya doang yang rapi.",
    explain:"JEBAKAN. Review marah pun kini di-generate (kadang untuk menjatuhkan kompetitor). Pola keluhannya generik: waktu-warna-CS — bisa ditempel ke toko mana pun." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — reviewer profesional",
    text:"Panel AMOLED 120Hz-nya mereproduksi warna dengan akurasi yang mengesankan di kelas harganya, meski peak brightness 800 nit membuatnya kurang optimal di bawah terik matahari. Untuk konten kreator pemula, ini kompromi yang masuk akal.",
    explain:"JEBAKAN sebaliknya: reviewer teknologi MANUSIA profesional — terminologi presisi (peak brightness 800 nit) dengan penilaian kontekstual. Keahlian sering disangka mesin." }
]},

{ id:8, nama:"PAKET 08 — PUISI & PROSA", soal:[
  { isAI:true, level:1, cue:"Puisi rima paksa",
    text:"Di ujung senja kumenanti / Bayang wajahmu hadir kembali / Rindu ini tak pernah pergi / Meski waktu terus berganti",
    explain:"Rima a-a-a-a dengan kosakata senja-bayang-rindu-waktu — kombinasi paling frekuent di puisi hasil generate." },
  { isAI:false, level:1, cue:"Puisi gambar konkret",
    text:"ibu menyimpan uang di lima tempat: / kaleng khong guan, lipatan sajadah, / bawah kasur, saku daster, / dan satu lagi hanya Tuhan yang tahu — / untuk hari ketika ayah pulang tanpa gaji.",
    explain:"Inventaris konkret (kaleng khong guan, saku daster) yang membangun narasi kelas ekonomi — imaji hidup yang berakar pengalaman." },
  { isAI:true, level:1, cue:"Prosa hujan klise",
    text:"Hujan selalu punya cara untuk membawa kenangan kembali. Setiap tetesnya seakan berbisik tentang masa lalu yang tak mungkin terulang. Dan aku, masih di sini, menikmati luka yang sama.",
    explain:"Hujan-kenangan-luka: tiga serangkai prosa melankolis yang menjadi default estetika AI berbahasa Indonesia." },
  { isAI:false, level:2, cue:"Prosa sudut tak biasa",
    text:"Nenek tidak pernah bilang rindu. Ia hanya bertanya lewat telepon apakah di kotaku ada daun singkong, lalu diam lama sekali, seolah jarak bisa diukur dengan sayur.",
    explain:"'Jarak diukur dengan sayur' — metafora yang lahir dari observasi keluarga spesifik, bukan dari bank frasa." },
  { isAI:true, level:2, cue:"Aforisme cinta simetris",
    text:"Mencintai bukan tentang memiliki, melainkan tentang merelakan. Karena cinta yang sejati tahu kapan harus menggenggam, dan kapan harus melepaskan.",
    explain:"Dua antitesis bertumpuk (memiliki/merelakan, menggenggam/melepaskan) — simetri sempurna khas mesin." },
  { isAI:false, level:2, cue:"Fragmen cerpen bertubuh",
    text:"Karsam menghitung sisa hidupnya dengan bungkus rokok: dua belas batang lagi sebelum uang habis, tiga hari lagi sebelum kontrakan ditagih, dan entah berapa lama lagi sebelum Painah berhenti menunggu.",
    explain:"Tiga hitungan mundur paralel dengan nama-nama membumi — teknik naratif yang disengaja, suara pengarang." },
  { isAI:true, level:2, cue:"Puisi alam generik",
    text:"Angin berbisik pada dedaunan / Menyampaikan salam dari kejauhan / Alam selalu punya bahasa / Bagi jiwa yang mau mendengarnya",
    explain:"Angin berbisik + alam berbahasa + jiwa yang mendengar — personifikasi stok tanpa satu spesies pohon pun disebut." },
  { isAI:false, level:2, cue:"Humor gelap berima",
    text:"katanya waktu menyembuhkan segala luka. / mungkin lukaku BPJS: / antre dulu, / sembuhnya nanti, / kalau dirujuk.",
    explain:"Menikahkan aforisme klasik dengan satir birokrasi BPJS — humor kultural yang butuh hidup di Indonesia." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — AI meniru puisi konkret",
    text:"bapak pulang membawa hujan di punggungnya, / menaruh lelah di gantungan baju, / dan tersenyum seperti gaji / yang tak pernah cukup tapi selalu ada.",
    explain:"JEBAKAN. AI yang di-prompt 'gaya puisi konkret Indonesia' bisa menghasilkan ini. Nyaris sempurna — 'tersenyum seperti gaji' sedikit terlalu kalkulatif, tapi siapa yang bisa yakin?" },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — penyair amatir klise",
    text:"Senja kembali datang membawa sejuta kenangan tentang kita. Di bangku taman ini, aku masih setia menunggu, meski tahu kau takkan pernah kembali. Biarlah rindu ini kupeluk sendiri.",
    explain:"JEBAKAN sebaliknya: MANUSIA — penulis amatir yang tumbuh dengan diksi 'senja dan sejuta kenangan'. Klise adalah bahasa bersama; manusia meminjamnya juga." }
]},

{ id:9, nama:"PAKET 09 — AKADEMIK & FORMAL", soal:[
  { isAI:true, level:1, cue:"Latar belakang sirkular",
    text:"Perkembangan teknologi informasi yang semakin pesat membawa dampak signifikan terhadap berbagai aspek kehidupan. Oleh karena itu, penelitian mengenai dampak teknologi informasi menjadi penting untuk dilakukan.",
    explain:"Logika sirkular: 'teknologi berkembang, maka meneliti teknologi itu penting' — latar belakang tanpa celah riset (research gap)." },
  { isAI:false, level:1, cue:"Latar belakang berdata",
    text:"Survei APJII 2024 mencatat 79,5% pengguna internet Indonesia pernah menerima hoaks kesehatan, namun hanya 12% yang memverifikasinya. Kesenjangan inilah yang mendorong penelitian ini menguji efektivitas program literasi digital di kalangan lansia.",
    explain:"Sitasi lembaga + dua angka yang membentuk kesenjangan + populasi spesifik (lansia) — kerangka riset yang dipikirkan." },
  { isAI:true, level:1, cue:"Abstrak tanpa temuan",
    text:"Penelitian ini bertujuan untuk menganalisis pengaruh media sosial terhadap perilaku konsumen. Metode yang digunakan adalah pendekatan kualitatif. Hasil penelitian menunjukkan bahwa media sosial memiliki pengaruh yang signifikan terhadap perilaku konsumen.",
    explain:"Kesimpulan mengulang judul ('berpengaruh signifikan') tanpa satu temuan konkret — abstrak kosong khas generate." },
  { isAI:false, level:2, cue:"Catatan pembimbing",
    text:"Bab 2 sudah lebih baik, tapi teori Uses and Gratifications-mu masih sekadar tempelan — belum kelihatan dipakai membedah data di Bab 4. Coba baca ulang McQuail hlm. 423, lalu tunjukkan gratifikasi mana yang muncul di wawancara R3 dan R7.",
    explain:"Kritik presisi (halaman buku, kode responden) dengan arahan perbaikan konkret — pembimbing manusia yang membaca naskah." },
  { isAI:true, level:2, cue:"Saran penelitian generik",
    text:"Bagi peneliti selanjutnya, disarankan untuk memperluas cakupan sampel dan menggunakan metode penelitian yang berbeda agar diperoleh hasil yang lebih komprehensif dan dapat digeneralisasikan.",
    explain:"'Perluas sampel, ganti metode' — saran universal yang menempel di ribuan skripsi; tak lahir dari keterbatasan riset spesifik." },
  { isAI:false, level:2, cue:"Email dosen singkat",
    text:"Zaki, jadwal bimbingan Kamis saya majukan ke Rabu jam 10 karena Kamis saya mendadak jadi penguji. Bawa print out Bab 3 saja, yang lain belum saya baca. -RH",
    explain:"Perubahan jadwal beralasan + instruksi selektif + inisial — efisiensi komunikasi dosen sungguhan." },
  { isAI:true, level:2, cue:"Definisi konsep bertingkat",
    text:"Literasi media dapat didefinisikan sebagai kemampuan untuk mengakses, menganalisis, mengevaluasi, dan mengkomunikasikan pesan dalam berbagai bentuk. Kemampuan ini mencakup aspek kognitif, afektif, dan psikomotorik yang saling berkaitan satu sama lain.",
    explain:"Definisi empat kata kerja + trio kognitif-afektif-psikomotorik — kompilasi textbook yang dirangkai mesin tanpa sumber." },
  { isAI:false, level:2, cue:"Pengakuan keterbatasan jujur",
    text:"Keterbatasan utama penelitian ini adalah tiga dari sepuluh informan menolak direkam sehingga peneliti mengandalkan catatan lapangan, yang berisiko kehilangan nuansa verbal. Dua wawancara juga terpaksa dilakukan daring karena informan positif COVID-19.",
    explain:"Keterbatasan yang memalukan dan spesifik (informan menolak direkam, COVID) — kejujuran metodologis peneliti yang benar-benar turun lapangan." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — parafrase AI di skripsi",
    text:"Berdasarkan pemaparan para ahli di atas, dapat disintesiskan bahwa komunikasi interpersonal merupakan proses pertukaran makna antara dua individu atau lebih yang berlangsung secara dinamis dan dipengaruhi oleh konteks sosial budaya yang melingkupinya.",
    explain:"JEBAKAN. 'Dapat disintesiskan bahwa…' — parafrase penghubung yang kini lazim di-generate mahasiswa. Mulus, benar, dan tak menambahkan pemikiran apa pun." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — birokrat menulis kaku",
    text:"Menindaklanjuti surat edaran nomor 042/SE/VII/2026 perihal tersebut pada pokok surat, bersama ini kami sampaikan bahwa pelaksanaan kegiatan dimaksud ditunda sampai dengan waktu yang akan ditentukan kemudian.",
    explain:"JEBAKAN sebaliknya: surat dinas MANUSIA tulen — 'perihal tersebut pada pokok surat', 'dimaksud', 'ditentukan kemudian'. Bahasa birokrasi Indonesia sudah robotik sejak mesin tik." }
]},

{ id:10, nama:"PAKET 10 — ZONA KABUT (SEMUA JEBAKAN)", soal:[
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — typo yang disengaja",
    text:"gilaa td hujan deres bgt pulang kerja, nekat nerobos eh kunci motor ketinggalan di jok wkwk emg klo udh capek tuh otak suka konslet sendiri ya",
    explain:"JEBAKAN. AI yang diminta 'tulis dengan typo dan singkatan' menghasilkan ini. Ketidaksempurnaan pun bisa dipalsukan — typo bukan lagi bukti kemanusiaan." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — manusia tanpa typo",
    text:"Hujan deras sekali sore ini. Saya sampai berteduh satu jam di emperan toko kelontong, dan pemiliknya menawari kursi plastik serta teh hangat tanpa saya minta. Dunia masih baik, ternyata.",
    explain:"JEBAKAN. MANUSIA yang menulis rapi — perhatikan detail non-instrumental (kursi plastik) yang diingat karena benar-benar dialami." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — opini pedas sintetis",
    text:"jujur ya konten podcast sekarang isinya itu2 aja. undang tamu, bahas masa kecil, nangis dikit, clip-in buat tiktok. formula banget. kreativitas kita mati pelan2 sama template",
    explain:"JEBAKAN. Kritik budaya bernada sinis pun kini bisa di-generate meyakinkan — ironisnya, AI fasih mengkritik 'template' dengan template." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — kutipan asli terdengar palsu",
    text:"Saya tidak takut pada orang yang berlatih 10.000 tendangan sekali. Saya takut pada orang yang berlatih satu tendangan 10.000 kali.",
    explain:"JEBAKAN. Terdengar seperti kutipan motivasi hasil generate — padahal ini kutipan MANUSIA asli (Bruce Lee, diterjemahkan). Aforisme simetris juga warisan manusia." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — detail lokal palsu",
    text:"buat anak jogja utara pasti relate: patokan pulang kampus itu bukan jam, tapi 'sebelum lampu merah kentungan macetnya ngeri'. salah itung 10 menit aja bisa kejebak setengah jam",
    explain:"JEBAKAN. AI bisa menganyam pengetahuan lokal (Kentungan memang macet) menjadi 'kenangan'. Detail lokal yang benar ≠ pengalaman yang nyata." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — cerita terlalu dramatis",
    text:"pernah ketinggalan kereta gara2 nolongin bapak2 jatuh dari tangga stasiun. besoknya baru tau kereta yg aku tinggal itu anjlok di purwokerto. sampe sekarang masih suka merinding kalo inget",
    explain:"JEBAKAN. Terdengar seperti karangan viral — tapi ini contoh cerita MANUSIA. Kebetulan dramatis sungguh terjadi; 'terlalu bagus untuk nyata' bukan alat ukur yang andal." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — kerentanan sintetis",
    text:"ternyata jadi dewasa itu bukan soal umur ya. dia dateng pas kamu belajar diem waktu dimarahin atasan padahal bukan salah kamu, karena inget tanggal 25 masih jauh dan cicilan gak peduli perasaan",
    explain:"JEBAKAN. Kerentanan finansial yang 'relatable' adalah genre yang AI pelajari dari jutaan tweet — ia tahu persis tanggal 25 dan cicilan menyentuh di mana." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — daftar rapi manusia",
    text:"Checklist sebelum pulang kampung: 1) cabut semua colokan 2) buang sampah dapur 3) titip kunci ke bu kos 4) matikan kran atas (yang suka netes) 5) bawa charger — JANGAN kayak tahun lalu.",
    explain:"JEBAKAN. Daftar bernomor rapi = manusia juga bisa. Petunjuknya justru di anomali: '(yang suka netes)' dan trauma 'tahun lalu' — memori spesifik rumah tertentu." },
  { isAI:true, level:2, trap:true, cue:"JEBAKAN — pertanyaan filosofis hangat",
    text:"pernah gak sih mikir, orang yang gak sengaja papasan sama kita di jalan hari ini mungkin lagi ngejalanin hari terberat dalam hidupnya, dan kita gak akan pernah tau. makanya aku selalu berusaha ramah ke orang asing",
    explain:"JEBAKAN. Renungan sonder ('kesadaran akan hidup orang asing') adalah tema favorit generator konten reflektif — lengkap dengan resolusi moral rapi di akhir." },
  { isAI:false, level:2, trap:true, cue:"JEBAKAN — pengumuman receh asli",
    text:"INFO KEHILANGAN: telah ditemukan satu (1) sandal swallow hijau sebelah KIRI ukuran 42 di area parkir masjid. Yang merasa kehilangan silakan hubungi takmir. Sebelah kanannya semoga segera menyusul ditemukan.",
    explain:"JEBAKAN. MANUSIA — humor takmir masjid yang tumbuh alami dari kejadian nyata paling receh. Keanehan yang tidak 'berguna' seperti ini jarang terpikir oleh mesin." }
]}

];

/* Gabungan semua soal teks (dipakai game.js) */
const PAKET_ALL = PAKET.flatMap(p => p.soal.map(s => ({ type:"teks", ...s })));
